using CommunityHub.Auth;
using CommunityHub.Core.Data;
using CommunityHub.Core.Domain.Evaluation;
using CommunityHub.Core.Evaluation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CommunityHub.Pages.Organizer;

/// <summary>
/// §743 C1 — register the feedback devices and watch their health.
/// </summary>
/// <remarks>
/// <para><b>Pre-registration IS the security model</b> (§743 item 35): ingest rejects any identifier
/// it does not already know, so the 25 units must be entered here BEFORE the event. There is no
/// self-registration and no pending-approval queue — which makes the bulk-entry box below a
/// requirement rather than a convenience.</para>
///
/// <para>🔒 <b>A key is shown ONCE and cannot be retrieved.</b> We store only a PBKDF2 hash, so
/// nobody — including us — can read a key back. Losing it means rotating it. This is stated on the
/// page rather than discovered.</para>
///
/// <para><b>Health is LAST-SEEN, never a live socket.</b> The units are battery-powered and
/// duty-cycle, so "no connection" is normal. The column that actually catches silent failure is
/// <c>cached records</c>: a device that is online and heartbeating but not draining its buffer is
/// losing data, and nothing else here would reveal it.</para>
/// </remarks>
[Authorize]
public class EvaluationDevicesModel : PageModel
{
    private readonly ICurrentParticipantAccessor _participant;
    private readonly CommunityHubDbContext _db;
    private readonly TimeProvider _clock;
    private readonly EvaluationProvisioningService _provisioning;

    public EvaluationDevicesModel(
        ICurrentParticipantAccessor participant, CommunityHubDbContext db, TimeProvider clock,
        EvaluationProvisioningService provisioning)
    {
        _participant = participant;
        _db = db;
        _clock = clock;
        _provisioning = provisioning;
    }

    public bool AccessDenied { get; private set; }
    public string? Message { get; private set; }

    /// <summary>Keys generated by THIS request — the only time they are ever visible.</summary>
    public IReadOnlyList<(string SerialNumber, string Key)> IssuedKeys { get; private set; }
        = Array.Empty<(string, string)>();

    public IReadOnlyList<EvaluationDevice> Devices { get; private set; }
        = Array.Empty<EvaluationDevice>();

    public DateTimeOffset Now { get; private set; }

    /// <summary>
    /// §743 C0/C1 alert thresholds, shown so the page and the notifications agree on what "a
    /// problem" means. Configurable later; stated here so they are not folklore.
    /// </summary>
    public const int LowBatteryPercent = 20;
    public const int CachedRecordAlert = 50;

    public async Task<IActionResult> OnGetAsync(CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) { AccessDenied = true; return Page(); }

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    /// <summary>
    /// Register one or many devices. The textarea takes ONE IDENTIFIER PER LINE so the 25 units can
    /// be entered in a single pass — reading them off enclosures one form at a time is how a
    /// pre-event task gets abandoned half-done.
    /// </summary>
    public async Task<IActionResult> OnPostAddAsync(string? identifiers, string? label, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        var ids = (identifiers ?? string.Empty)
            .Split(new[] { '\n', '\r', ',', ';' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(s => s.Trim())
            .Where(s => s.Length > 0)
            .Distinct(StringComparer.Ordinal)
            .ToList();

        if (ids.Count == 0)
        {
            Message = "Enter at least one device identifier.";
            await LoadAsync(me.EventId, ct);
            return Page();
        }

        var existing = await _db.EvaluationDevices
            .Where(d => d.EventId == me.EventId)
            .Select(d => d.SerialNumber)
            .ToListAsync(ct);
        var existingSet = existing.ToHashSet(StringComparer.Ordinal);

        var now = _clock.GetUtcNow();
        var issued = new List<(string, string)>();
        var skipped = 0;

        foreach (var id in ids)
        {
            // Re-adding an identifier must NOT silently issue a second key for a unit that is
            // already in the field — that would look like it worked and leave the device on a key
            // we no longer consider current.
            if (existingSet.Contains(id)) { skipped++; continue; }

            var key = EvaluationIngestService.NewKey();
            _db.EvaluationDevices.Add(new EvaluationDevice
            {
                EventId = me.EventId,
                SerialNumber = id,
                KeyHash = EvaluationIngestService.HashKey(key),
                Label = string.IsNullOrWhiteSpace(label) ? null : label.Trim(),
                IsActive = true,
                CreatedAt = now,
                UpdatedAt = now,
            });
            issued.Add((id, key));
        }

        await _db.SaveChangesAsync(ct);

        IssuedKeys = issued;
        Message = issued.Count == 0
            ? $"Nothing added — all {skipped} identifier(s) are already registered."
            : $"Registered {issued.Count} device(s)"
              + (skipped > 0 ? $"; skipped {skipped} already registered." : ".")
              + " Copy the keys below now — they cannot be shown again.";

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    /// <summary>
    /// Rotate a device's key. The OLD key keeps working (it moves to
    /// <see cref="EvaluationDevice.PreviousKeyHash"/>) so a staggered OTA rollout cannot brick a
    /// unit that has not updated yet.
    /// </summary>
    public async Task<IActionResult> OnPostRotateAsync(int id, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        var device = await _db.EvaluationDevices
            .FirstOrDefaultAsync(d => d.Id == id && d.EventId == me.EventId, ct);
        if (device is null) { Message = "That device no longer exists."; await LoadAsync(me.EventId, ct); return Page(); }

        var key = EvaluationIngestService.NewKey();
        device.PreviousKeyHash = device.KeyHash;
        device.KeyHash = EvaluationIngestService.HashKey(key);
        device.UpdatedAt = _clock.GetUtcNow();
        await _db.SaveChangesAsync(ct);

        IssuedKeys = new[] { (device.SerialNumber, key) };
        Message = $"New key issued for {device.SerialNumber}. The PREVIOUS key still works until you "
                  + "retire it, so a staggered firmware rollout will not lock a unit out. "
                  + "Copy it now — it cannot be shown again.";

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    /// <summary>
    /// §743 C2 — put a unit in a room. 🔑 The link is to the ROOM, never a session: a session moving
    /// to another room then re-points at that room's device automatically, and nobody has to touch
    /// hardware because a schedule changed.
    /// </summary>
    /// <remarks>
    /// Changing this does NOT re-attribute presses already collected. Responses attach to the
    /// session that was running when they were pressed, and rewriting history because a unit was
    /// carried to another room would move real feedback between speakers.
    /// </remarks>
    public async Task<IActionResult> OnPostSetRoomAsync(int id, int? roomId, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        var device = await _db.EvaluationDevices
            .FirstOrDefaultAsync(d => d.Id == id && d.EventId == me.EventId, ct);
        if (device is not null)
        {
            device.RoomId = roomId;
            device.UpdatedAt = _clock.GetUtcNow();
            await _db.SaveChangesAsync(ct);

            var roomName = roomId is null
                ? null
                : (await _db.EvaluationRooms.FirstOrDefaultAsync(r => r.Id == roomId, ct))?.Name;
            Message = roomId is null
                ? $"{device.SerialNumber} unlinked — its presses can no longer be attributed to a session."
                : $"{device.SerialNumber} is now in {roomName}.";
        }

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    /// <summary>Retire the previous key once every unit is confirmed on the new one.</summary>
    public async Task<IActionResult> OnPostRetirePreviousAsync(int id, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        var device = await _db.EvaluationDevices
            .FirstOrDefaultAsync(d => d.Id == id && d.EventId == me.EventId, ct);
        if (device is not null)
        {
            device.PreviousKeyHash = null;
            device.UpdatedAt = _clock.GetUtcNow();
            await _db.SaveChangesAsync(ct);
            Message = $"Previous key retired for {device.SerialNumber}. Only the current key is accepted now.";
        }

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    /// <summary>
    /// Revoke or restore. 🔒 Revocation is a HUB action needing no deploy — a lost unit, or one
    /// whose enclosure has been opened, is stopped here and immediately.
    /// </summary>
    public async Task<IActionResult> OnPostSetActiveAsync(int id, bool active, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        var device = await _db.EvaluationDevices
            .FirstOrDefaultAsync(d => d.Id == id && d.EventId == me.EventId, ct);
        if (device is not null)
        {
            device.IsActive = active;
            device.UpdatedAt = _clock.GetUtcNow();
            await _db.SaveChangesAsync(ct);
            Message = active
                ? $"{device.SerialNumber} restored — it can upload again."
                : $"{device.SerialNumber} revoked — every upload from it is now refused.";
        }

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    /// <summary>
    /// Delete a registration. Refused once the unit has sent anything: the responses reference the
    /// device identifier, and removing the row would leave stored feedback pointing at a unit
    /// nobody can identify. Revoke instead — that is what revocation is for.
    /// </summary>
    public async Task<IActionResult> OnPostDeleteAsync(int id, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        var device = await _db.EvaluationDevices
            .FirstOrDefaultAsync(d => d.Id == id && d.EventId == me.EventId, ct);
        if (device is not null)
        {
            var hasData = await _db.EvaluationResponses
                .AnyAsync(r => r.EventId == me.EventId && r.SerialNumber == device.SerialNumber, ct);
            if (hasData)
            {
                Message = $"{device.SerialNumber} has already collected feedback, so it cannot be "
                          + "deleted — revoke it instead, which stops it uploading while keeping "
                          + "its responses identifiable.";
            }
            else
            {
                _db.EvaluationDevices.Remove(device);
                await _db.SaveChangesAsync(ct);
                Message = $"{device.SerialNumber} removed.";
            }
        }

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    private async Task LoadAsync(int eventId, CancellationToken ct)
    {
        Now = _clock.GetUtcNow();
        Devices = await _db.EvaluationDevices
            .Where(d => d.EventId == eventId)
            .OrderBy(d => d.SerialNumber)
            .ToListAsync(ct);

        ResponseCounts = await _db.EvaluationResponses
            .Where(r => r.EventId == eventId && r.SerialNumber != null)
            .GroupBy(r => r.SerialNumber!)
            .Select(g => new { SerialNumber = g.Key, Count = g.Count() })
            .ToDictionaryAsync(x => x.SerialNumber, x => x.Count, ct);

        Rooms = await _db.EvaluationRooms
            .Where(r => r.EventId == eventId)
            .OrderBy(r => r.Name)
            .ToListAsync(ct);

        // §5.3 — presses this device collected that landed in NO session window. Surfaced per
        // device because a rising count is the earliest signal of a drifted clock or a schedule
        // that no longer matches reality, and if nobody can see it both stay silent until the
        // reports come out wrong.
        UnattributedCounts = await _db.EvaluationResponses
            .Where(r => r.EventId == eventId && r.SerialNumber != null && r.SessionId == null)
            .GroupBy(r => r.SerialNumber!)
            .Select(g => new { SerialNumber = g.Key, Count = g.Count() })
            .ToDictionaryAsync(x => x.SerialNumber, x => x.Count, ct);

        await LoadOnboardingAsync(eventId, ct);
    }

    // =====================================================================
    //  §784.7(A) — ONBOARDING, merged in from /Organizer/EvaluationOnboarding
    // =====================================================================
    //
    // Operator 2026-08-03: the two pages become ONE titled "Evaluation Devices", with onboarding as
    // a SECTION rather than a page. They were never two jobs — they are the same job (get the fleet
    // working) at two moments, and splitting them meant approving a unit here and then going
    // somewhere else to see whether it ever arrived.
    //
    // 🔴 THE SECURITY PROPERTY IS UNCHANGED AND MUST STAY THAT WAY. The provisioning endpoint is the
    // only one in the system that accepts an UNAUTHENTICATED write, and it is safe precisely because
    // everything it can do is put a row in the pending queue below. A unit there has no key, no
    // upload URL, and cannot post a single response until an organizer approves it HERE. Merging the
    // page moved the control; it did not weaken it.

    /// <summary>
    /// 🔑 Copenhagen, not UTC (operator: <i>"copenhagen time"</i>). Times are STORED in UTC and both
    /// entered and displayed in event-local time. Denmark is UTC+1 in February, so a window typed as
    /// "midnight 9 Feb" and stored naively as UTC would open an hour late — during the hour the venue
    /// opens.
    /// </summary>
    public static readonly TimeZoneInfo EventZone = ResolveZone();

    private static TimeZoneInfo ResolveZone()
    {
        // Windows and Linux disagree on the id; the container is Linux and the dev box is Windows,
        // so try both rather than assume — a throw here would take the whole page down.
        foreach (var id in new[] { "Europe/Copenhagen", "Romance Standard Time" })
        {
            try { return TimeZoneInfo.FindSystemTimeZoneById(id); }
            catch (TimeZoneNotFoundException) { }
            catch (InvalidTimeZoneException) { }
        }
        return TimeZoneInfo.Utc;
    }

    public static DateTimeOffset ToLocal(DateTimeOffset utc) => TimeZoneInfo.ConvertTime(utc, EventZone);

    public string Local(DateTimeOffset utc) => ToLocal(utc).ToString("ddd dd MMM yyyy HH:mm");

    public IReadOnlyList<EvaluationDeviceProvisionRequest> Pending { get; private set; }
        = Array.Empty<EvaluationDeviceProvisionRequest>();
    public IReadOnlyList<EvaluationTelemetryWindow> Windows { get; private set; }
        = Array.Empty<EvaluationTelemetryWindow>();

    /// <summary>True when no active window covers this moment — the fleet is silent right now.</summary>
    public bool TelemetryOffNow { get; private set; }

    /// <summary>When telemetry next turns on, if it is currently off.</summary>
    public DateTimeOffset? TelemetryNextOn { get; private set; }

    /// <summary>Set when the bootstrap secret is unconfigured — no device can provision at all.</summary>
    public bool ProvisioningUnconfigured { get; private set; }

    /// <summary>A device with its effective telemetry state and the reason for it.</summary>
    public sealed record TelemetryRow(EvaluationDevice Device, bool EffectivelyOn, string Why);

    /// <summary>
    /// The telemetry view of the same devices listed above. ⚠️ Named apart from
    /// <see cref="Devices"/> deliberately: the merge put two lists of the same units on one page, and
    /// one name for both would be the kind of collision that silently renders the wrong one.
    /// </summary>
    public IReadOnlyList<TelemetryRow> TelemetryRows { get; private set; } = Array.Empty<TelemetryRow>();

    public async Task<IActionResult> OnPostApproveAsync(int id, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) { AccessDenied = true; return Page(); }

        var ok = await _provisioning.ApproveAsync(id, me.Email ?? "organizer", ct);
        // 🔑 Say what happens NEXT, not just that it worked. The device is not live yet — it collects
        // its key on its next poll, up to an hour away — and an organizer expecting an instant green
        // light will otherwise think the approval failed.
        Message = ok
            ? "Approved. The unit collects its key on its next check-in (up to an hour) and appears "
              + "in the device list above once it does."
            : "That request was already approved.";

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    public async Task<IActionResult> OnPostRejectAsync(int id, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) { AccessDenied = true; return Page(); }

        var ok = await _provisioning.RejectAsync(id, me.Email ?? "organizer", ct);
        Message = ok
            ? "Refused. If a device row had already been created for it, that row is now revoked too."
            : "Request not found.";

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    /// <summary>Add one FROM/TO line to the telemetry schedule, entered in Copenhagen time.</summary>
    public async Task<IActionResult> OnPostAddWindowAsync(
        DateTime from, DateTime to, string? label, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) { AccessDenied = true; return Page(); }

        if (to <= from)
        {
            Message = "The end of a window must be after its start.";
            await LoadAsync(me.EventId, ct);
            return Page();
        }

        // 🔒 The typed value is Copenhagen wall-clock. Convert with the ZONE, never by adding a fixed
        // offset — Denmark is UTC+1 in February and UTC+2 in summer, and a hard-coded +1 would
        // silently shift every window added between March and October by an hour.
        var now = _clock.GetUtcNow();
        _db.EvaluationTelemetryWindows.Add(new EvaluationTelemetryWindow
        {
            EventId = me.EventId,
            FromUtc = new DateTimeOffset(from, EventZone.GetUtcOffset(from)).ToUniversalTime(),
            ToUtc = new DateTimeOffset(to, EventZone.GetUtcOffset(to)).ToUniversalTime(),
            Label = string.IsNullOrWhiteSpace(label) ? null : label.Trim(),
            IsActive = true,
            CreatedAt = now,
            UpdatedAt = now,
        });
        await _db.SaveChangesAsync(ct);

        Message = "Window added.";
        await LoadAsync(me.EventId, ct);
        return Page();
    }

    public async Task<IActionResult> OnPostToggleWindowAsync(int id, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) { AccessDenied = true; return Page(); }

        var w = await _db.EvaluationTelemetryWindows
            .FirstOrDefaultAsync(x => x.Id == id && x.EventId == me.EventId, ct);
        if (w is not null)
        {
            w.IsActive = !w.IsActive;
            w.UpdatedAt = _clock.GetUtcNow();
            await _db.SaveChangesAsync(ct);
            Message = w.IsActive ? "Window enabled." : "Window parked.";
        }

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    /// <summary>The per-device HARD switch. 🔒 Beats the schedule in both directions.</summary>
    public async Task<IActionResult> OnPostToggleDeviceHealthAsync(int id, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) { AccessDenied = true; return Page(); }

        var d = await _db.EvaluationDevices
            .FirstOrDefaultAsync(x => x.Id == id && x.EventId == me.EventId, ct);
        if (d is not null)
        {
            d.HealthTelemetryEnabled = !d.HealthTelemetryEnabled;
            d.UpdatedAt = _clock.GetUtcNow();
            await _db.SaveChangesAsync(ct);
            Message = d.HealthTelemetryEnabled
                ? "Health telemetry allowed for that unit (the schedule still applies)."
                : "Health telemetry HARD-disabled for that unit — no schedule can re-enable it.";
        }

        await LoadAsync(me.EventId, ct);
        return Page();
    }

    private async Task LoadOnboardingAsync(int eventId, CancellationToken ct)
    {
        Pending = await _db.EvaluationDeviceProvisionRequests
            .Where(r => r.EventId == eventId && r.Status == EvaluationProvisionStatus.Pending)
            .OrderByDescending(r => r.LastRequestedAt)
            .ToListAsync(ct);

        Windows = await _db.EvaluationTelemetryWindows
            .Where(w => w.EventId == eventId)
            .OrderBy(w => w.FromUtc)
            .ToListAsync(ct);

        // 🔑 The SAME policy the API answers with — never a second copy of the rule. A screen that
        // computes "on" its own way is how a GUI ends up reporting a state the fleet does not have.
        TelemetryRows = Devices.Select(d =>
        {
            var decision = EvaluationTelemetryPolicy.Evaluate(d, Windows, Now);
            return new TelemetryRow(d, decision.Enabled, decision.Why switch
            {
                EvaluationTelemetryPolicy.Reason.Enabled => "sending",
                EvaluationTelemetryPolicy.Reason.DeviceInactive => "device revoked",
                EvaluationTelemetryPolicy.Reason.HardDisabled => "hard-disabled",
                _ => "outside the schedule",
            });
        }).ToList();

        // Fleet-level answer, using a notional always-allowed device so the banner reflects the
        // SCHEDULE rather than any one unit's hard switch.
        var probe = new EvaluationDevice { Id = 0, IsActive = true, HealthTelemetryEnabled = true };
        var fleet = EvaluationTelemetryPolicy.Evaluate(
            probe, Windows.Where(w => w.EvaluationDeviceId is null), Now);
        TelemetryOffNow = !fleet.Enabled;
        TelemetryNextOn = fleet.NextOnAt;

        var secret = HttpContext.RequestServices.GetService<IConfiguration>()?
            [CommunityHub.Api.EvaluationProvisionController.SecretConfigKey];
        ProvisioningUnconfigured = string.IsNullOrWhiteSpace(secret);
    }

    public IReadOnlyList<CommunityHub.Core.Domain.Evaluation.EvaluationRoom> Rooms { get; private set; }
        = Array.Empty<CommunityHub.Core.Domain.Evaluation.EvaluationRoom>();

    /// <summary>Presses that matched no session window — the early warning for clock drift.</summary>
    public IReadOnlyDictionary<string, int> UnattributedCounts { get; private set; }
        = new Dictionary<string, int>();

    /// <summary>Responses stored per device — the "is it actually collecting?" column.</summary>
    public IReadOnlyDictionary<string, int> ResponseCounts { get; private set; }
        = new Dictionary<string, int>();

    /// <summary>
    /// online / late / silent from last-seen — never from a connection, because these units sleep.
    /// </summary>
    public string StatusOf(EvaluationDevice d)
    {
        if (d.LastSeenAt is not DateTimeOffset seen) return "never seen";
        var age = Now - seen;
        if (age < TimeSpan.FromMinutes(30)) return "online";
        if (age < TimeSpan.FromHours(2)) return "late";
        return "silent";
    }
}
