using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CommunityHub.Core.Migrations
{
    /// <inheritdoc />
    public partial class SoMeQueue : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // NOTE: ImpersonationAudits + ParticipantSecretaryTokens are created by
            // the earlier OrganizerGridV2 migration (20260615094122). This migration
            // was generated on a parallel feature branch whose base snapshot did not
            // yet include those tables, so EF re-emitted their CreateTable here. When
            // the branches merged, OrganizerGridV2 runs first and creates them, then
            // this migration failed with "There is already an object named
            // 'ImpersonationAudits'". The duplicate CreateTable/Drop + their indexes
            // are removed so this migration only does its real job: the SoMe queue
            // (SoMePosts + SoMeSettings). The model snapshot already carries each
            // table exactly once.

            migrationBuilder.CreateTable(
                name: "SoMePosts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    EventId = table.Column<int>(type: "int", nullable: false),
                    Type = table.Column<int>(type: "int", nullable: false),
                    ParticipantId = table.Column<int>(type: "int", nullable: true),
                    SessionId = table.Column<int>(type: "int", nullable: true),
                    SponsorCompanyId = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    ScheduledAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    AutoText = table.Column<string>(type: "nvarchar(max)", maxLength: 8000, nullable: false),
                    ManualTextOverride = table.Column<string>(type: "nvarchar(max)", maxLength: 8000, nullable: true),
                    ImageRef = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true),
                    Tags = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: false),
                    AutoGenerated = table.Column<bool>(type: "bit", nullable: false),
                    PublishedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    ExternalPostId = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    LastError = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true),
                    SpeakerPreAlertSent = table.Column<bool>(type: "bit", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    LastUpdatedByEmail = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SoMePosts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SoMePosts_Events_EventId",
                        column: x => x.EventId,
                        principalTable: "Events",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_SoMePosts_Participants_ParticipantId",
                        column: x => x.ParticipantId,
                        principalTable: "Participants",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_SoMePosts_Sessions_SessionId",
                        column: x => x.SessionId,
                        principalTable: "Sessions",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "SoMeSettings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    EventId = table.Column<int>(type: "int", nullable: false),
                    Enabled = table.Column<bool>(type: "bit", nullable: false),
                    CompanyPageUrlOrOrgId = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true),
                    SpeakerPreAlertOrganizerEmail = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: true),
                    NotificationEmails = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true),
                    NotifyOnPublish = table.Column<bool>(type: "bit", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    LastUpdatedByEmail = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SoMeSettings", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SoMeSettings_Events_EventId",
                        column: x => x.EventId,
                        principalTable: "Events",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_SoMePosts_EventId_Status_IsActive_ScheduledAtUtc",
                table: "SoMePosts",
                columns: new[] { "EventId", "Status", "IsActive", "ScheduledAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_SoMePosts_ParticipantId",
                table: "SoMePosts",
                column: "ParticipantId");

            migrationBuilder.CreateIndex(
                name: "IX_SoMePosts_SessionId",
                table: "SoMePosts",
                column: "SessionId");

            migrationBuilder.CreateIndex(
                name: "IX_SoMeSettings_EventId",
                table: "SoMeSettings",
                column: "EventId",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // ImpersonationAudits + ParticipantSecretaryTokens are owned by the
            // OrganizerGridV2 migration's Down(); this migration only drops what it
            // creates (the SoMe queue).
            migrationBuilder.DropTable(
                name: "SoMePosts");

            migrationBuilder.DropTable(
                name: "SoMeSettings");
        }
    }
}
