using CommunityHub.Auth;
using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CommunityHub.Pages.Organizer.SponsorAdmin;

/// <summary>
/// Sponsor tasks management — operates on the REAL per-company task rows.
///
/// Two task sources, both shown here aggregated by title:
///   - CATALOG tasks (SourceKey "sponsor:{companyId}:{slug}") — generated by
///     the nightly WooCommerce pull from sponsor.&lt;edition&gt;.json task
///     sets. Their canonical definition lives in that config file; deleting
///     them here would only last until the next pull, so delete is refused
///     with a pointer to the config. Deadline shifts DO stick — the pull
///     re-renders title/description but never touches DueDate.
///   - AD-HOC tasks (SourceKey "sponsor-adhoc:{companyId}:{slug}") — created
///     on this page, fanned out to every sponsor company of the active
///     event. Fully managed here (create / delete / shift deadline).
///
/// (This page was a scaffold writing to a stub list until 2026-06-12 —
/// create/delete/save buttons rendered but persisted nothing.)
/// </summary>
[Authorize]
public class TasksModel : PageModel
{
    private const string AdhocPrefix = "sponsor-adhoc:";

    private readonly CommunityHubDbContext _db;
    private readonly ICurrentParticipantAccessor _participant;
    private readonly TimeProvider _clock;

    public TasksModel(
        CommunityHubDbContext db,
        ICurrentParticipantAccessor participant,
        TimeProvider clock)
    {
        _db = db;
        _participant = participant;
        _clock = clock;
    }

    public bool AccessDenied { get; private set; }

    /// <summary>One row per distinct task title across all sponsor companies.</summary>
    public record TaskRow(
        string Title,
        bool IsAdhoc,
        int Companies,
        int Done,
        int Overdue,
        DateOnly? DueDate,
        bool Mandatory);

    public List<TaskRow> Tasks { get; private set; } = new();
    public int SponsorCompanies { get; private set; }

    public async Task<IActionResult> OnGetAsync(CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (me.Role != ParticipantRole.Organizer) { AccessDenied = true; return Page(); }

        var today = DateOnly.FromDateTime(_clock.GetUtcNow().UtcDateTime);

        var sponsorTasks = await SponsorTaskQuery(me.EventId)
            .Select(t => new { t.Title, t.SourceKey, t.State, t.DueDate, t.IsMandatory, t.SponsorCompanyId })
            .ToListAsync(ct);

        Tasks = sponsorTasks
            .GroupBy(t => t.Title, StringComparer.OrdinalIgnoreCase)
            .Select(g => new TaskRow(
                Title:     g.Key,
                IsAdhoc:   g.Any(t => t.SourceKey != null && t.SourceKey.StartsWith(AdhocPrefix)),
                Companies: g.Select(t => t.SponsorCompanyId ?? "?").Distinct().Count(),
                Done:      g.Count(t => t.State == TaskState.Done),
                Overdue:   g.Count(t => t.State != TaskState.Done && t.DueDate is not null && t.DueDate.Value < today),
                DueDate:   g.Max(t => t.DueDate),
                Mandatory: g.Any(t => t.IsMandatory)))
            .OrderBy(r => r.DueDate is null)        // dated first
            .ThenBy(r => r.DueDate)
            .ThenBy(r => r.Title, StringComparer.OrdinalIgnoreCase)
            .ToList();

        SponsorCompanies = await SponsorCompanyIdsQuery(me.EventId).CountAsync(ct);
        return Page();
    }

    /// <summary>
    /// Create an ad-hoc task and fan it out to every sponsor company of the
    /// active event. Idempotent per company (SourceKey-keyed), so re-posting
    /// the same title only fills gaps (e.g. a company onboarded later).
    /// </summary>
    public async Task<IActionResult> OnPostCreateAsync(
        string title, DateOnly? deadline, string? notes, bool mandatory, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        title = (title ?? string.Empty).Trim();
        if (title.Length == 0)
        {
            TempData["Notice"] = "Title is required.";
            return RedirectToPage();
        }

        var companies = await SponsorCompanyIdsQuery(me.EventId).ToListAsync(ct);
        if (companies.Count == 0)
        {
            TempData["Notice"] = "No sponsor companies found for the active event — nothing to create. Companies appear after the first WooCommerce order pull.";
            return RedirectToPage();
        }

        var slug = Slug(title);
        var existingKeys = await _db.Tasks
            .Where(t => t.EventId == me.EventId
                        && t.SourceKey != null
                        && t.SourceKey.EndsWith(":" + slug)
                        && t.SourceKey.StartsWith(AdhocPrefix))
            .Select(t => t.SourceKey!)
            .ToListAsync(ct);
        var existing = existingKeys.ToHashSet(StringComparer.OrdinalIgnoreCase);

        var created = 0;
        foreach (var companyId in companies)
        {
            var sourceKey = $"{AdhocPrefix}{companyId}:{slug}";
            if (existing.Contains(sourceKey)) continue;

            _db.Tasks.Add(new ParticipantTask
            {
                EventId = me.EventId,
                Title = title,
                Description = (notes ?? string.Empty).Trim(),
                DueDate = deadline,
                State = TaskState.Open,
                SourceKey = sourceKey,
                SponsorCompanyId = companyId,
                IsMandatory = mandatory,
            });
            created++;
        }

        if (created > 0) await _db.SaveChangesAsync(ct);
        TempData["Notice"] = $"Created '{title}' for {created} sponsor compan{(created == 1 ? "y" : "ies")}"
                             + (companies.Count - created > 0 ? $" ({companies.Count - created} already had it)." : ".");
        return RedirectToPage();
    }

    /// <summary>
    /// Delete an ad-hoc task across all companies. Catalog tasks are refused:
    /// the nightly pull would recreate them — their definition lives in
    /// sponsor.&lt;edition&gt;.json task sets.
    /// </summary>
    public async Task<IActionResult> OnPostDeleteAsync(string title, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        var rows = await SponsorTaskQuery(me.EventId)
            .Where(t => t.Title == title)
            .ToListAsync(ct);

        if (rows.Count == 0)
        {
            TempData["Notice"] = $"No tasks titled '{title}' found.";
            return RedirectToPage();
        }

        var adhoc = rows.Where(t => t.SourceKey != null && t.SourceKey.StartsWith(AdhocPrefix)).ToList();
        if (adhoc.Count == 0)
        {
            TempData["Notice"] = $"'{title}' is a catalog task generated from sponsor.<edition>.json — deleting it here would only last until the next nightly pull. Remove it from the task set in that config file instead.";
            return RedirectToPage();
        }

        _db.Tasks.RemoveRange(adhoc);
        await _db.SaveChangesAsync(ct);
        TempData["Notice"] = $"Deleted '{title}' from {adhoc.Count} sponsor compan{(adhoc.Count == 1 ? "y" : "ies")}.";
        return RedirectToPage();
    }

    /// <summary>
    /// Shift the deadline for a task title across all sponsor companies.
    /// Works for catalog AND ad-hoc tasks — the nightly pull re-renders
    /// title/description but never overwrites DueDate, so the shift sticks.
    /// </summary>
    public async Task<IActionResult> OnPostChangeDeadlineAsync(string title, DateOnly deadline, CancellationToken ct)
    {
        var me = _participant.Current;
        if (me is null) return RedirectToPage("/Login");
        if (!OrganizerAuth.IsRealOrganizer(me)) return Forbid();

        var rows = await SponsorTaskQuery(me.EventId)
            .Where(t => t.Title == title)
            .ToListAsync(ct);

        foreach (var t in rows) t.DueDate = deadline;
        if (rows.Count > 0) await _db.SaveChangesAsync(ct);

        TempData["Notice"] = rows.Count > 0
            ? $"Deadline for '{title}' set to {deadline:yyyy-MM-dd} across {rows.Count} task row(s)."
            : $"No tasks titled '{title}' found.";
        return RedirectToPage();
    }

    /// <summary>Sponsor tasks of one event — same predicate the dashboard + exports use.</summary>
    private IQueryable<ParticipantTask> SponsorTaskQuery(int eventId) =>
        _db.Tasks.Where(t => t.EventId == eventId
                             && (t.SponsorCompanyId != null
                                 || (t.SourceKey != null
                                     && (t.SourceKey.StartsWith("sponsor:") || t.SourceKey.StartsWith(AdhocPrefix)))));

    /// <summary>Distinct sponsor company ids for one event (from sponsor participants).</summary>
    private IQueryable<string> SponsorCompanyIdsQuery(int eventId) =>
        _db.Participants
            .Where(p => p.EventId == eventId
                        && p.Role == ParticipantRole.Sponsor
                        && p.SponsorCompanyId != null)
            .Select(p => p.SponsorCompanyId!)
            .Distinct();

    /// <summary>Same slug shape as SponsorOrderPullService so key formats line up.</summary>
    private static string Slug(string title)
    {
        var chars = title.ToLowerInvariant()
            .Where(c => char.IsLetterOrDigit(c) || c == ' ')
            .ToArray();
        var slug = new string(chars).Replace(' ', '-');
        return slug.Length > 60 ? slug[..60] : slug;
    }
}
