namespace CommunityHub.Core.Domain;

/// <summary>
/// What a <see cref="GraphicAsset"/> depicts. Drives the release-gate / visibility
/// rules (REQUIREMENTS §18):
///  - <see cref="Speaker"/> / <see cref="Session"/> graphics are speaker-facing but
///    ONLY after an organizer RELEASES them;
///  - <see cref="Sponsor"/> graphics are INTERNAL-ONLY (organizers' own SoMe posts)
///    and are NEVER shown in the sponsor view.
/// </summary>
public enum GraphicAssetType
{
    /// <summary>A speaker headshot graphic (template + photo + name).</summary>
    Speaker = 0,

    /// <summary>A sponsor graphic (template + logo). INTERNAL-ONLY — never shown to the sponsor.</summary>
    Sponsor = 1,

    /// <summary>A per-session graphic linked to a session the speaker is on (download/share).</summary>
    Session = 2,

    /// <summary>
    /// A per-TRACK promo graphic (REQUIREMENTS §158): one operator-uploaded file shared by
    /// every session in a track (e.g. "Security"/"Azure"), matched by the session's
    /// <see cref="Session.Track"/> name (NOT by session title). Speaker-facing like a
    /// <see cref="Session"/> graphic (released through the SAME gate, never sponsor-internal),
    /// but labelled as the track graphic so the speaker can tell the two apart.
    /// </summary>
    Track = 3,

    /// <summary>
    /// §767 — a per-TRACK GIF BUNDLE: ONE animated file for the whole track, one frame per speaker
    /// in it. Distinct from <see cref="Track"/>, which is one shared still per speaker.
    /// </summary>
    /// <remarks>
    /// Operator 2026-08-01: <i>"make folder for track speakers and sponsor category sponsor (gif
    /// bundles)"</i>, and <i>"we start with tracks and category"</i>. Organizer-facing promotion
    /// material for the event's own channels — it is not per-speaker and is not released to one.
    /// </remarks>
    TrackBundle = 4,

    /// <summary>
    /// §767 — a SPONSOR GROUPING GIF bundle: one frame per sponsor in a tier (platinum, gold, …) or
    /// in a webshop-derived TYPE (beverage, ice-cream, …).
    /// </summary>
    /// <remarks>
    /// ⚠️ Tier and type are TWO DIFFERENT GROUPINGS over the same sponsors, not one list — a sponsor
    /// appears in a tier bundle AND in any type bundle it qualifies for. INTERNAL-ONLY, like every
    /// other sponsor graphic: never shown in the sponsor's own view.
    /// </remarks>
    SponsorCategory = 5,
}

/// <summary>
/// The release / review state of a generated graphic (REQUIREMENTS §18).
///
/// THE HARD GATE for speaker / session graphics: a graphic is generated as
/// <see cref="Generated"/> and is NOT visible to the speaker until an organizer
/// reviews it and explicitly flips it to <see cref="Released"/>. This mirrors the
/// <c>SpeakerProfile.SelectedForPublish</c> publish gate used for the Backstage
/// bio sync — generation never auto-exposes anything.
/// </summary>
public enum GraphicAssetStatus
{
    /// <summary>
    /// Generated by the engine, stored on SharePoint, but NOT yet released —
    /// hidden from the speaker. The default for every freshly generated graphic.
    /// </summary>
    Generated = 0,

    /// <summary>
    /// Reviewed + released by an organizer — now visible to the speaker for
    /// download / share. Sponsor graphics never need releasing to a sponsor (they
    /// are internal-only), but organizers may still mark them released for their
    /// own "ready to post" tracking.
    /// </summary>
    Released = 1,
}

/// <summary>
/// One generated (or organizer-replaced) social-media graphic, stored on
/// SharePoint and tracked in the hub (REQUIREMENTS §18). Scoped to an
/// <see cref="Event"/> edition like every other entity.
///
/// THE STABLE-KEY CONTRACT: <see cref="StableKey"/> is a deterministic,
/// edition-unique identity for "the graphic for speaker X" / "the graphic for
/// session Y" / "the sponsor graphic for company Z". The SharePoint file is
/// stored under a path derived from it, and the hub→SharePoint link is built from
/// it — so when an organizer OVERRULES the generated file with their own design,
/// the replacement keeps the SAME <see cref="StableKey"/> (and therefore the same
/// path / link). The link never breaks; only the bytes behind it change.
/// </summary>
public class GraphicAsset
{
    public int Id { get; set; }

    public int EventId { get; set; }
    public Event Event { get; set; } = null!;

    /// <summary>What the graphic depicts (drives visibility / release rules).</summary>
    public GraphicAssetType Type { get; set; }

    /// <summary>
    /// The deterministic, edition-unique key (e.g. <c>speaker:42</c>,
    /// <c>session:hub-7:speaker:42</c>, <c>sponsor:9001</c>). The SharePoint path
    /// is derived from it and stays STABLE across organizer overrules — see the
    /// class remarks. Built by <see cref="GraphicStableKey"/>.
    /// </summary>
    public string StableKey { get; set; } = string.Empty;

    /// <summary>
    /// The speaker / session-speaker this graphic belongs to (null for a sponsor
    /// graphic). Set-null on participant delete is avoided (the edition cascade
    /// covers it); kept nullable so a sponsor graphic has no participant.
    /// </summary>
    public int? ParticipantId { get; set; }
    public Participant? Participant { get; set; }

    /// <summary>The session this graphic is for (only for <see cref="GraphicAssetType.Session"/>).</summary>
    public int? SessionId { get; set; }
    public Session? Session { get; set; }

    /// <summary>The sponsor company id (only for <see cref="GraphicAssetType.Sponsor"/>).</summary>
    public string? SponsorCompanyId { get; set; }

    /// <summary>The release / review state (the hard gate). Defaults <see cref="GraphicAssetStatus.Generated"/>.</summary>
    public GraphicAssetStatus Status { get; set; } = GraphicAssetStatus.Generated;

    /// <summary>
    /// The SharePoint path the PNG is stored at, derived from <see cref="StableKey"/>
    /// and STABLE across overrules (e.g. <c>/Graphics/Speakers/speaker-42.png</c>).
    /// </summary>
    public string? SharePointPath { get; set; }

    /// <summary>
    /// The hub→SharePoint link to the stored PNG (download/preview URL). Stable
    /// because the path is stable; an overrule replaces the bytes, not the URL.
    /// </summary>
    public string? SharePointUrl { get; set; }

    /// <summary>
    /// The Graph driveItem id of the stored file, when the live store wrote it
    /// (null for the null-store / not-yet-stored case). Lets a later overrule /
    /// replace target the same item.
    /// </summary>
    public string? StorageItemId { get; set; }

    /// <summary>
    /// True when an ORGANIZER replaced the engine-generated bytes with their own
    /// design (overrule). The <see cref="StableKey"/> / path / URL stay identical
    /// so the link does not break; this flag records that the engine should NOT
    /// regenerate over a human's deliberate replacement.
    /// </summary>
    public bool IsOrganizerOverridden { get; set; }

    /// <summary>The file name (stable, derived from the key), e.g. <c>speaker-42.png</c>.</summary>
    public string? FileName { get; set; }

    /// <summary>
    /// §767 — hash of the INPUTS this graphic was composed from: the speaker set (id, name, photo),
    /// the session title or track, the sponsor's resolved logo VERSION, and the design version.
    /// </summary>
    /// <remarks>
    /// 🔒 <b>The rebuild is keyed on this, never on "does a graphic exist."</b> Keying on existence
    /// freezes the first render for ever — the §764.1 defect — so a replaced photo, a new sponsor
    /// logo version, or a speaker joining or leaving would never reach the artwork.
    /// <para>The speaker set IS part of the hash, which is what makes <i>"when chg happens like add
    /// or remove of speaker … they must be build"</i> work by construction, with nothing to
    /// remember to trigger. The design version is in it too, so locking a new design rebuilds
    /// everything ONCE instead of splitting the line-up across two looks.</para>
    /// <para>⚠️ NULL means "unknown inputs", NOT "stale": rows predating §767, and any file PULLED
    /// from SharePoint or overruled by an organizer. Those are left alone — treating unknown as
    /// stale would regenerate over the operator's own artwork every fifteen minutes.</para>
    /// </remarks>
    public string? InputHash { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>When the graphic was last (re)generated or overruled.</summary>
    public DateTimeOffset? UpdatedAt { get; set; }

    /// <summary>When an organizer released the graphic to the speaker (null while gated).</summary>
    public DateTimeOffset? ReleasedAt { get; set; }

    /// <summary>The organizer who released it (audit).</summary>
    public string? ReleasedByEmail { get; set; }
}

/// <summary>
/// Deterministic stable-key + path/file-name builders for <see cref="GraphicAsset"/>.
/// Centralised so the engine, the overrule path and the tests all derive the SAME
/// key — the contract that keeps the hub→SharePoint link stable across overrules.
/// </summary>
public static class GraphicStableKey
{
    public static string ForSpeaker(int participantId) => $"speaker:{participantId}";

    public static string ForSession(int sessionId, int participantId) =>
        $"session:{sessionId}:speaker:{participantId}";

    /// <summary>
    /// The stable key for a per-TRACK promo graphic (REQUIREMENTS §158), keyed by the
    /// track-name SLUG + speaker — NOT by session. So a speaker on two sessions in the
    /// SAME track gets ONE track graphic (idempotent), while a speaker spanning two
    /// tracks gets one per track, e.g. <c>track:security:speaker:42</c>.
    /// </summary>
    public static string ForTrack(string trackSlug, int participantId) =>
        $"track:{trackSlug}:speaker:{participantId}";

    /// <summary>
    /// §767 PHASE 2 — the ONE graphic for a whole session, keyed by session id ALONE.
    /// </summary>
    /// <remarks>
    /// 🔒 Operator 2026-08-01: <i>"should we drop speaker id and have only session id. only
    /// differentiator and we dont need speaker id"</i> — and he is right. Under the PNG/GIF rule the
    /// session graphic is ONE file for the whole session (a frame per speaker), so the speaker id in
    /// the key was never a differentiator: it produced N rows of identical content for an N-speaker
    /// session. The linked speakers are a LOOKUP, not part of the identity.
    /// <para>Key <c>session:{id}</c>, file <c>session-12.png</c> (1 speaker) or <c>session-12.gif</c>
    /// (2+), folder <c>Sessions/</c>. The EXTENSION carries single-vs-multi, which is what lets a
    /// 1→2-speaker flip UPDATE one graphic rather than create a second one.</para>
    /// <para>⚠️ A different SHAPE from the legacy per-speaker key <see cref="ForSession"/>
    /// (<c>session:12:speaker:42</c>), which the SharePoint PULL still writes for operator-uploaded
    /// artwork. They cannot collide — deliberately, so a human's uploaded file and a generated one
    /// are never the same row.</para>
    /// </remarks>
    public static string ForSessionGraphic(int sessionId) => $"session:{sessionId}";

    public static string ForSponsor(string sponsorCompanyId) => $"sponsor:{sponsorCompanyId}";

    /// <summary>§767 — the ONE track graphic, keyed by track slug alone.</summary>
    /// <remarks>
    /// 🔒 Operator 2026-08-01: <i>"we dont need word bundle as it is implicit"</i> — a track graphic
    /// with no speaker in its key IS the whole track, so saying "bundle" adds a word and no meaning.
    /// Key <c>track:{slug}</c>, file <c>track-security.gif</c>, folder <c>Tracks/</c>.
    /// <para>⚠️ Distinct from the legacy per-speaker key <c>track:{slug}:speaker:{id}</c> (§158,
    /// dropped and inert) — different shapes, so they cannot collide.</para>
    /// </remarks>
    public static string ForTrackGraphic(string trackSlug) => $"track:{trackSlug}";

    /// <summary>
    /// §767 — a sponsor grouping bundle. <paramref name="kind"/> separates the two groupings that
    /// share this key space: <c>tier</c> (platinum, gold, …) and <c>type</c> (beverage, …).
    /// </summary>
    /// <remarks>
    /// ⚠️ The kind is part of the key ON PURPOSE. Without it a tier named the same as a type would
    /// silently overwrite it — two different bundles, one file, and nobody would see which was lost.
    /// </remarks>
    public static string ForSponsorCategory(string kind, string slug) =>
        $"sponsor-{kind}:{slug}";

    /// <summary>The stable, path-safe file name for a key, e.g. <c>speaker-42.png</c>.</summary>
    /// <summary>
    /// The file name for a key. <paramref name="extension"/> carries the §767 PNG-vs-GIF rule:
    /// a session with 2+ speakers is a GIF, everything else a PNG.
    /// </summary>
    public static string FileName(string stableKey, string extension = ".png") =>
        stableKey.Replace(':', '-') + extension;
}
