namespace CommunityHub.Core.Domain;

/// <summary>
/// What a <see cref="GraphicAsset"/> depicts. Drives the release-gate / visibility
/// rules (REQUIREMENTS §18):
///  - <see cref="Speaker"/> / <see cref="Session"/> graphics are speaker-facing but
///    ONLY after an organizer RELEASES them;
///  - <see cref="Sponsor"/> graphics are INTERNAL-ONLY (organizers' own SoMe posts)
///    and are NEVER shown in the sponsor view.
/// </summary>
public enum GraphicAssetType
{
    /// <summary>A speaker headshot graphic (template + photo + name).</summary>
    Speaker = 0,

    /// <summary>A sponsor graphic (template + logo). INTERNAL-ONLY — never shown to the sponsor.</summary>
    Sponsor = 1,

    /// <summary>A per-session graphic linked to a session the speaker is on (download/share).</summary>
    Session = 2,
}

/// <summary>
/// The release / review state of a generated graphic (REQUIREMENTS §18).
///
/// THE HARD GATE for speaker / session graphics: a graphic is generated as
/// <see cref="Generated"/> and is NOT visible to the speaker until an organizer
/// reviews it and explicitly flips it to <see cref="Released"/>. This mirrors the
/// <c>SpeakerProfile.SelectedForPublish</c> publish gate used for the Backstage
/// bio sync — generation never auto-exposes anything.
/// </summary>
public enum GraphicAssetStatus
{
    /// <summary>
    /// Generated by the engine, stored on SharePoint, but NOT yet released —
    /// hidden from the speaker. The default for every freshly generated graphic.
    /// </summary>
    Generated = 0,

    /// <summary>
    /// Reviewed + released by an organizer — now visible to the speaker for
    /// download / share. Sponsor graphics never need releasing to a sponsor (they
    /// are internal-only), but organizers may still mark them released for their
    /// own "ready to post" tracking.
    /// </summary>
    Released = 1,
}

/// <summary>
/// One generated (or organizer-replaced) social-media graphic, stored on
/// SharePoint and tracked in the hub (REQUIREMENTS §18). Scoped to an
/// <see cref="Event"/> edition like every other entity.
///
/// THE STABLE-KEY CONTRACT: <see cref="StableKey"/> is a deterministic,
/// edition-unique identity for "the graphic for speaker X" / "the graphic for
/// session Y" / "the sponsor graphic for company Z". The SharePoint file is
/// stored under a path derived from it, and the hub→SharePoint link is built from
/// it — so when an organizer OVERRULES the generated file with their own design,
/// the replacement keeps the SAME <see cref="StableKey"/> (and therefore the same
/// path / link). The link never breaks; only the bytes behind it change.
/// </summary>
public class GraphicAsset
{
    public int Id { get; set; }

    public int EventId { get; set; }
    public Event Event { get; set; } = null!;

    /// <summary>What the graphic depicts (drives visibility / release rules).</summary>
    public GraphicAssetType Type { get; set; }

    /// <summary>
    /// The deterministic, edition-unique key (e.g. <c>speaker:42</c>,
    /// <c>session:hub-7:speaker:42</c>, <c>sponsor:9001</c>). The SharePoint path
    /// is derived from it and stays STABLE across organizer overrules — see the
    /// class remarks. Built by <see cref="GraphicStableKey"/>.
    /// </summary>
    public string StableKey { get; set; } = string.Empty;

    /// <summary>
    /// The speaker / session-speaker this graphic belongs to (null for a sponsor
    /// graphic). Set-null on participant delete is avoided (the edition cascade
    /// covers it); kept nullable so a sponsor graphic has no participant.
    /// </summary>
    public int? ParticipantId { get; set; }
    public Participant? Participant { get; set; }

    /// <summary>The session this graphic is for (only for <see cref="GraphicAssetType.Session"/>).</summary>
    public int? SessionId { get; set; }
    public Session? Session { get; set; }

    /// <summary>The sponsor company id (only for <see cref="GraphicAssetType.Sponsor"/>).</summary>
    public string? SponsorCompanyId { get; set; }

    /// <summary>The release / review state (the hard gate). Defaults <see cref="GraphicAssetStatus.Generated"/>.</summary>
    public GraphicAssetStatus Status { get; set; } = GraphicAssetStatus.Generated;

    /// <summary>
    /// The SharePoint path the PNG is stored at, derived from <see cref="StableKey"/>
    /// and STABLE across overrules (e.g. <c>/Graphics/Speakers/speaker-42.png</c>).
    /// </summary>
    public string? SharePointPath { get; set; }

    /// <summary>
    /// The hub→SharePoint link to the stored PNG (download/preview URL). Stable
    /// because the path is stable; an overrule replaces the bytes, not the URL.
    /// </summary>
    public string? SharePointUrl { get; set; }

    /// <summary>
    /// The Graph driveItem id of the stored file, when the live store wrote it
    /// (null for the null-store / not-yet-stored case). Lets a later overrule /
    /// replace target the same item.
    /// </summary>
    public string? StorageItemId { get; set; }

    /// <summary>
    /// True when an ORGANIZER replaced the engine-generated bytes with their own
    /// design (overrule). The <see cref="StableKey"/> / path / URL stay identical
    /// so the link does not break; this flag records that the engine should NOT
    /// regenerate over a human's deliberate replacement.
    /// </summary>
    public bool IsOrganizerOverridden { get; set; }

    /// <summary>The file name (stable, derived from the key), e.g. <c>speaker-42.png</c>.</summary>
    public string? FileName { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>When the graphic was last (re)generated or overruled.</summary>
    public DateTimeOffset? UpdatedAt { get; set; }

    /// <summary>When an organizer released the graphic to the speaker (null while gated).</summary>
    public DateTimeOffset? ReleasedAt { get; set; }

    /// <summary>The organizer who released it (audit).</summary>
    public string? ReleasedByEmail { get; set; }
}

/// <summary>
/// Deterministic stable-key + path/file-name builders for <see cref="GraphicAsset"/>.
/// Centralised so the engine, the overrule path and the tests all derive the SAME
/// key — the contract that keeps the hub→SharePoint link stable across overrules.
/// </summary>
public static class GraphicStableKey
{
    public static string ForSpeaker(int participantId) => $"speaker:{participantId}";

    public static string ForSession(int sessionId, int participantId) =>
        $"session:{sessionId}:speaker:{participantId}";

    public static string ForSponsor(string sponsorCompanyId) => $"sponsor:{sponsorCompanyId}";

    /// <summary>The stable, path-safe file name for a key, e.g. <c>speaker-42.png</c>.</summary>
    public static string FileName(string stableKey) =>
        stableKey.Replace(':', '-') + ".png";
}
