using System.ComponentModel.DataAnnotations.Schema;

namespace CommunityHub.Core.Domain;

/// <summary>
/// One scheduled LinkedIn company-page post in the social-media (SoMe) queue
/// (REQUIREMENTS §19) — the "social media calendar". A post is published by the
/// scheduling job at its <see cref="ScheduledAtUtc"/> when it is
/// <see cref="IsActive"/> and still <see cref="SoMePostStatus.Queued"/>, through
/// the gated <c>ILinkedInPostPublisher</c> seam (nothing posts until that seam is
/// wired + enabled).
///
/// <b>Auto vs static.</b> When <see cref="AutoGenerated"/> is true the text +
/// branding image are auto-populated (and re-populated) from the linked
/// sponsor/speaker; an organizer can always fine-tune. A non-blank
/// <see cref="ManualTextOverride"/> ALWAYS wins over the auto text (the override
/// is what gets published), so an organizer's edit is never flushed by a refresh.
///
/// <b>Idempotent dispatch.</b> A post is published at most once — the dispatcher
/// flips <see cref="SoMePostStatus.Queued"/> → <see cref="SoMePostStatus.Published"/>
/// and stamps <see cref="PublishedAtUtc"/> + <see cref="ExternalPostId"/>, so a
/// re-run never double-posts (the status is the sent-marker, mirroring the
/// reminder ledger pattern). A failure records <see cref="LastError"/> and flips
/// to <see cref="SoMePostStatus.Failed"/> rather than dropping the post silently.
/// </summary>
public class SoMePost
{
    public int Id { get; set; }

    /// <summary>The edition this post belongs to. Every query is scoped by this.</summary>
    public int EventId { get; set; }
    public Event Event { get; set; } = null!;

    /// <summary>Sponsor / Speaker / AdHoc — drives the tag set + auto-branding source.</summary>
    public SoMePostType Type { get; set; }

    /// <summary>
    /// The speaker/session participant a Speaker post promotes (optional; null for
    /// Sponsor / AdHoc). Soft pointer — NoAction FK, so deleting the participant
    /// never cascade-deletes the post (it carries its own captured text/tags).
    /// </summary>
    public int? ParticipantId { get; set; }
    public Participant? Participant { get; set; }

    /// <summary>The session a Speaker post promotes (optional). Soft pointer (NoAction).</summary>
    public int? SessionId { get; set; }
    public Session? Session { get; set; }

    /// <summary>
    /// The Company Manager / WooCommerce company id a Sponsor post promotes
    /// (optional; the hub has no company table — this is the external id carried
    /// for scoping, like elsewhere). The company name is always resolved through
    /// the shared public→legal→billing chain at compose/tag time.
    /// </summary>
    public string? SponsorCompanyId { get; set; }

    /// <summary>When the post should publish (UTC). The dispatcher fires at/after this.</summary>
    public DateTimeOffset ScheduledAtUtc { get; set; }

    /// <summary>Queued / Published / Failed. The status is also the no-double-post marker.</summary>
    public SoMePostStatus Status { get; set; } = SoMePostStatus.Queued;

    /// <summary>
    /// The Active/Inactive toggle (REQUIREMENTS §19). An Inactive post is NEVER
    /// published — e.g. a speaker drops out, the organizer flips it off and the
    /// dispatcher skips it. Distinct from status: an Active Queued post is the
    /// only thing that publishes.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// The auto-populated post body (set when <see cref="AutoGenerated"/> is true).
    /// What actually publishes is <see cref="EffectiveText"/> — the override wins.
    /// </summary>
    public string AutoText { get; set; } = string.Empty;

    /// <summary>
    /// The organizer's manual fine-tune of the post text. When non-blank this is
    /// what publishes (override wins); blank = use <see cref="AutoText"/>.
    /// </summary>
    public string? ManualTextOverride { get; set; }

    /// <summary>
    /// A reference (URL / SharePoint path) to the branding image attached to the
    /// post. Auto-populated when <see cref="AutoGenerated"/> is true; an organizer
    /// can replace it. Null = text-only post.
    /// </summary>
    public string? ImageRef { get; set; }

    /// <summary>
    /// The compliance-aware tag set, stored as a newline-separated list of LinkedIn
    /// member/organization handles or URNs (see <c>SoMeTagBuilder</c>). Sponsor
    /// posts tag signer + event coordinator + sponsor company; speaker posts tag
    /// organizers only.
    /// </summary>
    public string Tags { get; set; } = string.Empty;

    /// <summary>
    /// When true the text + branding image are auto-populated from the linked
    /// sponsor/speaker; when false the organizer's static/manual values win and a
    /// refresh leaves them alone. Auto-schedule branding is preferred but can be
    /// turned OFF per post.
    /// </summary>
    public bool AutoGenerated { get; set; } = true;

    // --- Dispatch audit (sent-marker / idempotency) --------------------------

    /// <summary>When the post was actually published (UTC). Null until published.</summary>
    public DateTimeOffset? PublishedAtUtc { get; set; }

    /// <summary>
    /// The LinkedIn post / share id returned by the publisher on success — the
    /// external sent-marker. Null until published (or while the seam is the null
    /// no-op publisher).
    /// </summary>
    public string? ExternalPostId { get; set; }

    /// <summary>The last publish error, recorded on a failed attempt (never dropped silently).</summary>
    public string? LastError { get; set; }

    /// <summary>
    /// True once the T-5-minute speaker pre-alert email has been sent for a
    /// Speaker post (the idempotency marker for the pre-alert, so the scheduled
    /// job emails the designated organizer exactly once). Always false for
    /// Sponsor / AdHoc posts (no pre-alert).
    /// </summary>
    public bool SpeakerPreAlertSent { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? UpdatedAt { get; set; }
    public string? LastUpdatedByEmail { get; set; }

    // --- Derived helpers ------------------------------------------------------

    /// <summary>
    /// The text that actually publishes: the manual override when set, else the
    /// auto text. The override ALWAYS wins (REQUIREMENTS §19 — "override wins").
    /// </summary>
    public string EffectiveText =>
        string.IsNullOrWhiteSpace(ManualTextOverride) ? AutoText : ManualTextOverride!.Trim();

    /// <summary>
    /// True when this is an auto post that has no branding image yet (REQUIREMENTS
    /// §18↔§19 link): the linked speaker/session graphic is missing or still behind
    /// the organizer RELEASE gate, so the auto path attached no image rather than a
    /// broken ref. A clear "awaiting approved graphic" signal for the queue UI /
    /// preview. Never true for a static post or one that already carries an image
    /// (a manual image or a released graphic clears it). Derived — not persisted.
    /// </summary>
    [NotMapped]
    public bool IsAwaitingApprovedGraphic =>
        AutoGenerated && string.IsNullOrWhiteSpace(ImageRef);

    /// <summary>The tags split into a clean, de-duplicated, non-blank list.</summary>
    public IReadOnlyList<string> TagList =>
        string.IsNullOrWhiteSpace(Tags)
            ? Array.Empty<string>()
            : Tags.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                  .Distinct(StringComparer.OrdinalIgnoreCase)
                  .ToArray();
}
