using System.ComponentModel.DataAnnotations.Schema;

namespace CommunityHub.Core.Domain;

/// <summary>
/// One scheduled LinkedIn company-page post in the social-media (SoMe) queue
/// (REQUIREMENTS §19) — the "social media calendar". A post is published by the
/// scheduling job at its <see cref="ScheduledAtUtc"/> when it is
/// <see cref="IsActive"/> and still <see cref="SoMePostStatus.Queued"/>, through
/// the gated <c>ILinkedInPostPublisher</c> seam (nothing posts until that seam is
/// wired + enabled).
///
/// <b>Auto vs static.</b> When <see cref="AutoGenerated"/> is true the text +
/// branding image are auto-populated (and re-populated) from the linked
/// sponsor/speaker; an organizer can always fine-tune. A non-blank
/// <see cref="ManualTextOverride"/> ALWAYS wins over the auto text (the override
/// is what gets published), so an organizer's edit is never flushed by a refresh.
///
/// <b>Idempotent dispatch.</b> A post is published at most once — the dispatcher
/// flips <see cref="SoMePostStatus.Queued"/> → <see cref="SoMePostStatus.Published"/>
/// and stamps <see cref="PublishedAtUtc"/> + <see cref="ExternalPostId"/>, so a
/// re-run never double-posts (the status is the sent-marker, mirroring the
/// reminder ledger pattern). A failure records <see cref="LastError"/> and flips
/// to <see cref="SoMePostStatus.Failed"/> rather than dropping the post silently.
/// </summary>
public class SoMePost
{
    public int Id { get; set; }

    /// <summary>The edition this post belongs to. Every query is scoped by this.</summary>
    public int EventId { get; set; }
    public Event Event { get; set; } = null!;

    /// <summary>Sponsor / Speaker / AdHoc — drives the tag set + auto-branding source.</summary>
    public SoMePostType Type { get; set; }

    /// <summary>
    /// The speaker/session participant a Speaker post promotes (optional; null for
    /// Sponsor / AdHoc). Soft pointer — NoAction FK, so deleting the participant
    /// never cascade-deletes the post (it carries its own captured text/tags).
    /// </summary>
    public int? ParticipantId { get; set; }
    public Participant? Participant { get; set; }

    /// <summary>The session a Speaker post promotes (optional). Soft pointer (NoAction).</summary>
    public int? SessionId { get; set; }
    public Session? Session { get; set; }

    /// <summary>
    /// The Company Manager / WooCommerce company id a Sponsor post promotes
    /// (optional; the hub has no company table — this is the external id carried
    /// for scoping, like elsewhere). The company name is always resolved through
    /// the shared public→legal→billing chain at compose/tag time.
    /// </summary>
    public string? SponsorCompanyId { get; set; }

    /// <summary>When the post should publish (UTC). The dispatcher fires at/after this.</summary>
    public DateTimeOffset ScheduledAtUtc { get; set; }

    /// <summary>Queued / Published / Failed. The status is also the no-double-post marker.</summary>
    public SoMePostStatus Status { get; set; } = SoMePostStatus.Queued;

    /// <summary>
    /// The Active/Inactive toggle (REQUIREMENTS §19). An Inactive post is NEVER
    /// published — e.g. a speaker drops out, the organizer flips it off and the
    /// dispatcher skips it. Distinct from status: an Active Queued post is the
    /// only thing that publishes.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// §848.2 — <b>Proposed</b> (the planner's, and re-plannable) or <b>Scheduled</b> (his, and
    /// locked). Defaults to Proposed: anything the planner creates is a suggestion until he accepts it.
    /// </summary>
    /// <remarks>
    /// 🔒 <b>The planner must filter on this, not on <see cref="IsActive"/>.</b> They answer
    /// different questions: <c>PlanState</c> is "whose decision is this?", <c>IsActive</c> is "may it
    /// publish?". A post can be Scheduled and switched off (he accepted the slot, then pulled the
    /// post), and that is not the same as an un-accepted proposal.
    /// </remarks>
    public SoMePostPlanState PlanState { get; set; } = SoMePostPlanState.Proposed;

    /// <summary>
    /// §853 — he deleted this post. It is gone from every view, never publishes, and — crucially —
    /// the planner will not propose that subject+occurrence again.
    /// </summary>
    /// <remarks>
    /// <para>🔴 <b>A SOFT delete, and that is the whole point.</b> Removing the row outright would
    /// not work: since §848.2 the planner re-plans its own un-accepted proposals, so a deleted
    /// proposal would reappear on the next tick (§825 runs hourly). The row survives precisely so it
    /// can say "not this one".</para>
    ///
    /// <para>⚠️ For a PUBLISHED post this removes it from CEH only — the post is already on LinkedIn
    /// and nothing here retracts it.</para>
    ///
    /// <para>🔒 Reversible: restoring clears the flag and the subject returns to the campaign.</para>
    /// </remarks>
    public bool IsDeleted { get; set; }

    /// <summary>When he deleted it, and who — a deletion should never be anonymous.</summary>
    public DateTimeOffset? DeletedAt { get; set; }
    public string? DeletedByEmail { get; set; }

    // --- §824.21: what an auto-planned post is ABOUT ------------------------------------------
    // 🔑 Without these three the scheduler cannot tell "already planned" from "plan it again", and a
    // timer that re-plans every tick would fill the queue with duplicates of one announcement.

    /// <summary>§824.1 — which of the five post types this is.</summary>
    /// <remarks>
    /// Null on rows created before the scheduler existed and on ad-hoc posts a human wrote.
    /// Deliberately ALONGSIDE <see cref="Type"/> rather than replacing it: <c>Type</c>'s three values
    /// are already persisted on live rows, and renumbering an enum under existing data is how a
    /// sponsor post silently becomes a speaker post.
    /// </remarks>
    public Integrations.SoMeTemplateKind? TemplateKind { get; set; }

    /// <summary>Stable id of the subject — a track name, a session id, a sponsor company id, a tier.</summary>
    public string? SubjectKey { get; set; }

    /// <summary>1-based: the 1st or 2nd time this subject is announced (§824.1 gives most types 2).</summary>
    public int? Occurrence { get; set; }

    /// <summary>
    /// The composed post BODY (set when <see cref="AutoGenerated"/> is true).
    /// </summary>
    /// <remarks>
    /// 🔒 §861 — <b>BODY ONLY. It does NOT include the organizer credit</b>, which is appended at
    /// publish time by <see cref="SoMePostCredit"/>. Storing it here is what froze the credit into
    /// posts 383 and 495 and would have opted them out of the §858 mention upgrade.
    /// </remarks>
    public string AutoText { get; set; } = string.Empty;

    /// <summary>
    /// §885 — the call-to-action phrase this post drew from <see cref="SoMeSettings.ActionCatalog"/>,
    /// resolving <c>{Action_catalog_random}</c>.
    /// </summary>
    /// <remarks>
    /// 🔒 <b>Rolled ONCE, then it is ordinary stored data.</b> "Random" means varied across the
    /// campaign, NOT different on every render: a phrase that re-rolled would make the preview
    /// disagree with the published post, and re-opening the editor would look like data loss.
    /// <para>⚠️ <b>Deliberately unlike the credit above.</b> The credit is resolved LATE so a post
    /// written months ago picks up today's rule (§864); this is frozen EARLY for the opposite and
    /// equally deliberate reason — he approves a specific sentence, and that is the one that goes
    /// out. A re-roll is an explicit action, not a side effect of opening the page.</para>
    /// </remarks>
    public string? ActionPhrase { get; set; }

    /// <summary>
    /// §901 — the AI opening paragraph this post was given when it was planned, resolving
    /// <c>{IntroText}</c> (§824.2D).
    /// </summary>
    /// <remarks>
    /// 🔒 <b>Stored for the same reason as <see cref="ActionPhrase"/> above, and it is the reason
    /// the planner can stop freezing the whole body.</b> Every other token resolves late (§864); this
    /// one cannot, because it is a generative call — re-running it at publish time would spend an AI
    /// round-trip per post and, worse, would publish a paragraph he never approved. So it is written
    /// ONCE at plan time and read back as an ordinary value by
    /// <see cref="Integrations.SoMePostComposer.ValuesForAsync"/>.
    /// <para>⚠️ <b>Null is an ordinary state, not a failure</b> — Type 5 never has one (§834.5, its
    /// copy is his own), and every AI failure path resolves to null by design. A known token holding
    /// null renders empty and the renderer tidies the blank line away, so the post is composed
    /// without its opening line and still publishes.</para>
    /// </remarks>
    public string? IntroText { get; set; }

    /// <summary>
    /// His edit of the post BODY. Blank = use <see cref="AutoText"/>.
    /// </summary>
    /// <remarks>
    /// ⚠️ §861 — operator 2026-08-05: <i>"i dont like that we talk about \"override\" — we have one
    /// single field for a post"</i>. <b>He is right, and "override" is not a concept to show him.</b>
    /// Two columns survive because the planner must be able to recompose a post he has never touched
    /// while never overwriting one he has; <b>the UI shows ONE field, and it edits the BODY.</b>
    /// </remarks>
    public string? ManualTextOverride { get; set; }

    /// <summary>
    /// A reference (URL / SharePoint path) to the branding image attached to the
    /// post. Auto-populated when <see cref="AutoGenerated"/> is true; an organizer
    /// can replace it. Null = text-only post.
    /// </summary>
    public string? ImageRef { get; set; }

    /// <summary>
    /// §844.3 — whether <see cref="ImageRef"/> names a GRAPHIC or a VIDEO, and therefore which
    /// library it is resolved from.
    /// </summary>
    /// <remarks>
    /// <para>🔒 <b>Explicit, not inferred from the file extension.</b> Extension-sniffing would work
    /// until the first <c>.mov</c>, the first uppercase <c>.MP4</c>, or the first graphic exported as
    /// something unexpected — and the failure would be a post publishing the wrong medium, or
    /// nothing. He asked to "switch type of either graphics or video", which is a decision, so it is
    /// stored as one.</para>
    ///
    /// <para>⚠️ <b>Defaults to <see cref="SoMePostMediaKind.Graphic"/>, which is what every existing
    /// row is.</b> The column is additive: no back-fill, and no existing post changes meaning.</para>
    /// </remarks>
    public SoMePostMediaKind MediaKind { get; set; } = SoMePostMediaKind.Graphic;

    /// <summary>
    /// The compliance-aware tag set, stored as a newline-separated list of LinkedIn
    /// member/organization handles or URNs (see <c>SoMeTagBuilder</c>). Sponsor
    /// posts tag signer + event coordinator + sponsor company; speaker posts tag
    /// organizers only.
    /// </summary>
    public string Tags { get; set; } = string.Empty;

    /// <summary>
    /// When true the text + branding image are auto-populated from the linked
    /// sponsor/speaker; when false the organizer's static/manual values win and a
    /// refresh leaves them alone. Auto-schedule branding is preferred but can be
    /// turned OFF per post.
    /// </summary>
    public bool AutoGenerated { get; set; } = true;

    // --- Dispatch audit (sent-marker / idempotency) --------------------------

    /// <summary>When the post was actually published (UTC). Null until published.</summary>
    public DateTimeOffset? PublishedAtUtc { get; set; }

    /// <summary>
    /// The LinkedIn post / share id returned by the publisher on success — the
    /// external sent-marker. Null until published (or while the seam is the null
    /// no-op publisher).
    /// </summary>
    public string? ExternalPostId { get; set; }

    /// <summary>The last publish error, recorded on a failed attempt (never dropped silently).</summary>
    public string? LastError { get; set; }

    /// <summary>
    /// True once the T-5-minute speaker pre-alert email has been sent for a
    /// Speaker post (the idempotency marker for the pre-alert, so the scheduled
    /// job emails the designated organizer exactly once). Always false for
    /// Sponsor / AdHoc posts (no pre-alert).
    /// </summary>
    public bool SpeakerPreAlertSent { get; set; }

    /// <summary>
    /// §1190 — when the "this publishes within 24 hours" alert was sent for THIS post. Null = not yet.
    /// </summary>
    /// <remarks>
    /// <para>Operator 2026-09-12: <i>"i need the notification for some post during next 24 hr to run
    /// every 10 min, as it comes way to late … today i have one 1 hr to react on the mail. i need
    /// close to 24 hr to react"</i>.</para>
    ///
    /// <para>🔴 <b>This column is what makes a 10-minute cadence survivable.</b> §1060(j) was a DAILY
    /// DIGEST — it listed everything publishing in the next 24 hours — so a post scheduled just after
    /// the daily run got barely an hour's warning. Running that same query every ten minutes would
    /// send <b>144 identical mails a day</b>, which is §1041b's lesson exactly: a correct mechanism
    /// reported too loudly becomes the problem, and he would start skimming past the one that matters.</para>
    ///
    /// <para>🔑 So the mail changes character: from <i>"here is today's list"</i> to <i>"these posts
    /// have JUST crossed the 24-hour line"</i>. Each post is announced <b>once</b>, the moment it
    /// enters the window, which is what gives him close to a full day to react.</para>
    ///
    /// <para>⚠️ <b>Cleared when a post moves back OUT of the window</b>, so a post pushed to next week
    /// and later brought back in is alerted again. Without that the stamp would silently suppress the
    /// warning for the one post whose date somebody had been fiddling with — the case most likely to
    /// need it.</para>
    /// </remarks>
    public DateTimeOffset? Next24NoticeSentAt { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? UpdatedAt { get; set; }
    public string? LastUpdatedByEmail { get; set; }

    // --- Derived helpers ------------------------------------------------------

    /// <summary>
    /// The post BODY as it stands: his edit when he has made one, else the composed text.
    /// </summary>
    /// <remarks>
    /// 🔴 §861 — <b>THIS IS NOT THE PUBLISHED TEXT.</b> The organizer credit is appended at publish
    /// time from settings (<see cref="SoMePostCredit.Compose"/>), so that a credit which becomes an
    /// @-mention tomorrow (§858) reaches EVERY post, including the ones he has edited.
    /// <b>Anything that shows or publishes the real post must compose; only summaries may use this
    /// alone.</b>
    /// </remarks>
    public string EffectiveText =>
        string.IsNullOrWhiteSpace(ManualTextOverride) ? AutoText : ManualTextOverride!.Trim();

    /// <summary>
    /// True when this is an auto post that has no branding image yet (REQUIREMENTS
    /// §18↔§19 link): the linked speaker/session graphic is missing or still behind
    /// the organizer RELEASE gate, so the auto path attached no image rather than a
    /// broken ref. A clear "awaiting approved graphic" signal for the queue UI /
    /// preview. Never true for a static post or one that already carries an image
    /// (a manual image or a released graphic clears it). Derived — not persisted.
    /// </summary>
    /// <remarks>
    /// 🔴 <b>§1168 — THIS IS THE PLANNER'S ANSWER, NOT THE PUBLISHER'S. Do not show it to a human on
    /// its own.</b> It reads only the STAMPED <see cref="ImageRef"/>, and §917 is explicit that the
    /// stamp is <i>"a default for the editor to show, not the answer"</i>: at send time
    /// <c>SoMeDispatchService</c> re-resolves the subject's CURRENT graphic and publishes that.
    ///
    /// <para>⇒ A post planned before its graphic was released has a null stamp for ever — nothing
    /// back-fills it — while publishing perfectly well WITH the image. Reported by the operator
    /// 2026-09-03: <i>"graphics has been released but it still says no graphics"</i>. He was right,
    /// and the post was fine; the BADGE was wrong.</para>
    ///
    /// <para>🔑 Use <c>SoMeQueueService.AwaitingGraphicAsync</c> for anything a person reads: it asks
    /// the same question the dispatcher will.</para>
    /// </remarks>
    [NotMapped]
    public bool IsAwaitingApprovedGraphic =>
        AutoGenerated && string.IsNullOrWhiteSpace(ImageRef);

    /// <summary>The tags split into a clean, de-duplicated, non-blank list.</summary>
    public IReadOnlyList<string> TagList =>
        string.IsNullOrWhiteSpace(Tags)
            ? Array.Empty<string>()
            : Tags.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                  .Distinct(StringComparer.OrdinalIgnoreCase)
                  .ToArray();
}
