using CommunityHub.Core.Evaluation;
using QRCoder;
using Xunit;
using ZXing;
using ZXing.Common;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §748 C5 — the per-session QR code, generated by US (operator 2026-07-31: *"qr must be gerated by
/// you"*, *"1 per session"*).
/// </summary>
/// <remarks>
/// <para>🔑 <b>These tests DECODE the generated code back, with an independent library</b>
/// (ZXing.Net, test-only), rather than asserting that some bytes came out. The same standard the
/// §743.14 PDF tests set by reading the PDF back with PdfPig: a QR code that renders but does not
/// scan is a stack of useless printed signs discovered on the morning of the event, and only a
/// decode proves otherwise.</para>
///
/// <para>The decode runs over the module matrix rather than the PNG pixels, so the test needs no
/// image-decoding backend — which is the same constraint that made
/// <see cref="PngByteQRCode"/> the right renderer in the first place.</para>
/// </remarks>
public sealed class SessionQrCodeServiceTests
{
    private const string BaseUrl = "https://hub.example.org";
    private const string Token = "9fJ2xQ7pLm4TvB1zR8sKdN3w";

    private static readonly SessionQrCodeService Svc = new();

    /// <summary>
    /// Decode a QR by rebuilding ZXing's bit matrix from QRCoder's module matrix — no PNG decoder,
    /// no imaging backend. Returns the decoded text, or null when nothing scans.
    /// </summary>
    private const int DecodeScale = 4;

    private static string? Decode(string url)
    {
        using var generator = new QRCodeGenerator();
        using var data = generator.CreateQrCode(url, SessionQrCodeService.ErrorCorrection);

        var modules = data.ModuleMatrix;
        var size = modules.Count;
        var width = size * DecodeScale;

        // Gray8 luminance straight from the module matrix: dark module = 0, light = 255. Scaled up
        // because the binariser needs more than one pixel per module to work with.
        var luminance = new byte[width * width];
        for (var y = 0; y < width; y++)
        {
            for (var x = 0; x < width; x++)
            {
                luminance[(y * width) + x] =
                    modules[y / DecodeScale][x / DecodeScale] ? (byte)0 : (byte)255;
            }
        }

        var source = new RGBLuminanceSource(
            luminance, width, width, RGBLuminanceSource.BitmapFormat.Gray8);

        var reader = new BarcodeReaderGeneric
        {
            Options = new DecodingOptions
            {
                PureBarcode = true,
                PossibleFormats = new[] { BarcodeFormat.QR_CODE },
            },
        };
        return reader.Decode(source)?.Text;
    }

    // ---- the code actually scans -------------------------------------------------------------

    /// <summary>🔑 The whole point: a scan lands the attendee on THIS session's feedback page.</summary>
    [Fact]
    public void Generated_code_decodes_back_to_the_feedback_url()
    {
        var url = SessionQrCodeService.FeedbackUrl(BaseUrl, Token);

        Assert.Equal(url, Decode(url));
    }

    /// <summary>
    /// 🔒 One code per SESSION — two sessions must never resolve to the same page. Obvious, and
    /// exactly the kind of thing a shared-token refactor breaks silently.
    /// </summary>
    [Fact]
    public void Two_sessions_encode_to_different_urls()
    {
        var a = SessionQrCodeService.FeedbackUrl(BaseUrl, "tokenAAAAAAAAAAAAAAAAAAA");
        var b = SessionQrCodeService.FeedbackUrl(BaseUrl, "tokenBBBBBBBBBBBBBBBBBBB");

        Assert.NotEqual(a, b);
        Assert.Equal(a, Decode(a));
        Assert.Equal(b, Decode(b));
    }

    // ---- the URL ----------------------------------------------------------------------------

    /// <summary>
    /// 🔒 The SHORT route. Every character raises the module density of a symbol that has to scan
    /// from the back of a room, which is why the brief exempts this one route from `/evaluation/v1`.
    /// </summary>
    [Fact]
    public void Url_uses_the_short_f_route()
    {
        Assert.Equal($"{BaseUrl}/f/{Token}", SessionQrCodeService.FeedbackUrl(BaseUrl, Token));
    }

    [Fact]
    public void Trailing_slash_on_the_base_url_does_not_double_up()
    {
        Assert.Equal(
            $"{BaseUrl}/f/{Token}",
            SessionQrCodeService.FeedbackUrl(BaseUrl + "/", Token));
    }

    // ---- the rendered files ------------------------------------------------------------------

    /// <summary>
    /// 🔒 Real PNG bytes, produced with NO <c>System.Drawing</c> anywhere in the path — that
    /// assembly is Windows-only from .NET 7 and would be a latent break on Linux.
    /// </summary>
    [Fact]
    public void Png_is_a_real_png()
    {
        var png = Svc.RenderPng(BaseUrl, Token);

        Assert.NotEmpty(png);
        // PNG signature: 89 50 4E 47 0D 0A 1A 0A
        Assert.Equal(new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A }, png[..8]);
    }

    /// <summary>A bigger module size must produce a bigger file, or the parameter does nothing.</summary>
    [Fact]
    public void Pixels_per_module_scales_the_image()
    {
        var small = Svc.RenderPng(BaseUrl, Token, pixelsPerModule: 4);
        var large = Svc.RenderPng(BaseUrl, Token, pixelsPerModule: 20);

        Assert.True(large.Length > small.Length,
            $"expected the 20px render ({large.Length}B) to exceed the 4px one ({small.Length}B)");
    }

    // ---- filenames ---------------------------------------------------------------------------

    /// <summary>
    /// 🔑 The title is in the filename because a folder of `qr-17.png` is unusable at print time —
    /// and cross-referencing ids by hand is exactly when a code gets taped to the wrong door.
    /// </summary>
    [Fact]
    public void Filename_carries_the_session_title()
    {
        Assert.Equal(
            "session-17-keeping-identity-boring-qr.png",
            SessionQrCodeService.FileName(17, "Keeping Identity Boring", "png"));
    }

    [Fact]
    public void Filename_survives_punctuation_and_accents_without_becoming_unsafe()
    {
        var name = SessionQrCodeService.FileName(4, "Zero Trust: what it *really* means (2027)", "png");

        Assert.StartsWith("session-4-", name, StringComparison.Ordinal);
        Assert.EndsWith(".png", name, StringComparison.Ordinal);
        Assert.All(name, c => Assert.True(
            char.IsLetterOrDigit(c) || c is '-' or '.', $"unsafe character '{c}' in '{name}'"));
        Assert.DoesNotContain("--", name, StringComparison.Ordinal);
    }

    /// <summary>A session with no usable title still gets a unique, sortable filename.</summary>
    [Fact]
    public void Filename_falls_back_when_the_title_yields_nothing()
    {
        Assert.Equal("session-9-qr.png", SessionQrCodeService.FileName(9, "***", "png"));
        Assert.Equal("session-9-qr.png", SessionQrCodeService.FileName(9, null, "png"));
    }

    /// <summary>A very long title must not produce a path a filesystem or SharePoint rejects.</summary>
    [Fact]
    public void Filename_is_bounded()
    {
        var name = SessionQrCodeService.FileName(3, new string('a', 400), "png");

        Assert.True(name.Length < 100, $"filename too long ({name.Length}): {name}");
        Assert.EndsWith("-qr.png", name, StringComparison.Ordinal);
    }
}
