using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §918 — AUTO-APPROVAL, AND THE THREE GUARDS IT MUST NOT BREAK.
/// </summary>
/// <remarks>
/// <para>Operator 2026-08-06: <i>"as they run from the templates, i see no reason why we should not
/// auto-approve them, concerns?"</i> — with 79 posts held and 1 approved, clicking each was not a
/// workflow. The concerns were about HOW, and each is a test here.</para>
///
/// <para>🔴 The first guard is the one with history: §889.1 saw him approve #495 whose 09:00 slot
/// had already passed, and it published <b>thirty seconds later</b>. Without a lead time,
/// auto-approving a queue does that to every overdue post at once.</para>
/// </remarks>
public sealed class SoMeAutoApproveTests
{
    private const int EventId = 1;
    private static readonly DateTimeOffset Now = new(2026, 8, 6, 9, 0, 0, TimeSpan.Zero);

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"autoapprove-{Guid.NewGuid():N}").Options);

    private static SoMeAutoApproveService NewService(CommunityHubDbContext db) =>
        new(db, new SoMeApprovalGate(db), new FixedClock(Now));

    private static async Task SeedAsync(
        CommunityHubDbContext db, bool enabled = true, int leadDays = 7)
    {
        db.Events.Add(new Event
        {
            Id = EventId, Code = "ELDK27", CommunityName = "ELDK", DisplayName = "ELDK 2027",
            StartDate = new DateOnly(2027, 2, 9), EndDate = new DateOnly(2027, 2, 10), IsActive = true,
        });
        db.SoMeSettings.Add(new SoMeSettings
        {
            EventId = EventId, Enabled = true,
            AutoApproveEnabled = enabled, AutoApproveLeadDays = leadDays,
        });
        await db.SaveChangesAsync();
    }

    private static SoMePost Planned(DateTimeOffset when, SoMeTemplateKind kind = SoMeTemplateKind.SpeakerTracks) =>
        new()
        {
            EventId = EventId, TemplateKind = kind, SubjectKey = $"track:T{when.Ticks}",
            Occurrence = 1, ScheduledAtUtc = when, Status = SoMePostStatus.Queued,
            IsActive = false, AutoGenerated = true, AutoText = "✨ {TrackName} ✨",
        };

    [Fact]
    public async Task It_does_nothing_at_all_until_he_switches_it_on()
    {
        using var db = NewDb();
        await SeedAsync(db, enabled: false);
        db.SoMePosts.Add(Planned(Now.AddDays(30)));
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.All(await db.SoMePosts.ToListAsync(), p => Assert.False(p.IsActive));
    }

    [Fact]
    public async Task A_post_far_enough_ahead_is_approved()
    {
        using var db = NewDb();
        await SeedAsync(db);
        db.SoMePosts.Add(Planned(Now.AddDays(30)));
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(1, result.Approved);
        Assert.True((await db.SoMePosts.FirstAsync()).IsActive);
    }

    /// <summary>🔴 GUARD 1 — the §889.1 case: an overdue post must never be switched on.</summary>
    [Fact]
    public async Task An_overdue_post_is_never_auto_approved()
    {
        using var db = NewDb();
        await SeedAsync(db);
        // Its slot passed an hour ago — approving it publishes on the next dispatch tick.
        db.SoMePosts.Add(Planned(Now.AddHours(-1)));
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.Equal(1, result.TooSoon);
        Assert.False((await db.SoMePosts.FirstAsync()).IsActive);
    }

    [Fact]
    public async Task A_post_inside_the_lead_window_is_left_for_him()
    {
        using var db = NewDb();
        await SeedAsync(db, leadDays: 7);
        db.SoMePosts.Add(Planned(Now.AddDays(3)));   // sooner than the lead
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.Equal(1, result.TooSoon);
    }

    /// <summary>
    /// 🔒 GUARD 3 — a post carrying a HUMAN's words keeps a human's approval, even though its type
    /// is template-built.
    /// </summary>
    [Fact]
    public async Task A_post_he_edited_still_waits_for_him()
    {
        using var db = NewDb();
        await SeedAsync(db);
        var post = Planned(Now.AddDays(30));
        post.ManualTextOverride = "my own words";
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.False((await db.SoMePosts.FirstAsync()).IsActive);
    }

    /// <summary>🔒 GUARD 3 — Type 5 is his own copy from the deck; never auto-approved.</summary>
    [Fact]
    public async Task An_event_post_is_never_auto_approved()
    {
        using var db = NewDb();
        await SeedAsync(db);
        db.SoMePosts.Add(Planned(Now.AddDays(30), SoMeTemplateKind.EventPost));
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
    }

    /// <summary>
    /// 🔒 GUARD 2 — the approval gate still applies. A sponsor who has delivered neither their
    /// social text nor a logo is not announced just because a rule was switched on.
    /// </summary>
    [Fact]
    public async Task A_sponsor_with_a_missing_dependency_is_reported_not_approved()
    {
        using var db = NewDb();
        await SeedAsync(db);
        db.SponsorInfos.Add(new SponsorInfo
        {
            EventId = EventId, SponsorCompanyId = "co-9", CompanyName = "Not Ready A/S",
            SponsorPackage = SponsorPackage.Gold,
            SocialMediaIntro = null,          // owes their text
        });
        var post = Planned(Now.AddDays(30), SoMeTemplateKind.Sponsor);
        post.SubjectKey = "sponsor:co-9";
        post.SponsorCompanyId = "co-9";
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.Equal(1, result.Blocked);
        Assert.False((await db.SoMePosts.FirstAsync()).IsActive);
    }

    /// <summary>
    /// ⚠️ A zero lead would mean "approve what is due now" — the very burst guard 1 exists to stop.
    /// Floored, so a misconfigured field cannot express it.
    /// </summary>
    [Fact]
    public async Task A_zero_lead_is_floored_rather_than_obeyed()
    {
        using var db = NewDb();
        await SeedAsync(db, leadDays: 0);
        db.SoMePosts.Add(Planned(Now.AddHours(2)));   // due today
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.Equal(1, result.TooSoon);
    }

    [Fact]
    public async Task An_already_published_post_is_left_alone()
    {
        using var db = NewDb();
        await SeedAsync(db);
        var post = Planned(Now.AddDays(30));
        post.Status = SoMePostStatus.Published;
        post.PublishedAtUtc = Now.AddDays(-1);
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        Assert.Equal(0, (await NewService(db).RunAsync(EventId)).Approved);
    }
}
