using System;
using System.Linq;
using System.Threading.Tasks;
using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §1028/§1029/§1032 — WHAT AN EXTERNAL AUDIENCE SEES ON THEIR OWN ANNOUNCEMENTS PAGE.
/// </summary>
/// <remarks>
/// <para>⚠️ <b><see cref="SoMeAnnouncementQuery"/> had no tests at all</b> until this file, while
/// being the ONE place that answers "which posts are about this subject" for four views — including
/// the two an external sponsor and speaker read. The class documents that as its whole reason for
/// existing; nothing held it to it.</para>
///
/// <para>🔒 What is pinned here is the part that leaks or misleads if it drifts: a sponsor sees
/// their OWN posts, APPROVED ones only, and only those they are ELIGIBLE for; the state badge says
/// "planned" until he has accepted the post into the plan; and the picture endpoint's gate is the
/// same scope as the list.</para>
/// </remarks>
public sealed class SoMeAnnouncementQueryTests
{
    private const int EventId = 1;
    private const string MyCompany = "co-mine";
    private const string OtherCompany = "co-other";

    private static readonly DateTimeOffset Slot =
        new(2026, 10, 1, 9, 0, 0, TimeSpan.Zero);

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"announcements-{Guid.NewGuid():N}").Options);

    /// <param name="socialText">
    /// 🔒 Defaults to DELIVERED. The eligibility rule is one test's subject; everywhere else a
    /// missing text would silently remove the post and make the test pass for the wrong reason.
    /// </param>
    private static async Task<int> SeedAsync(
        CommunityHubDbContext db, string? socialText = "We build things.")
    {
        db.Events.Add(new Event
        {
            Id = EventId, Code = "ELDK27", CommunityName = "ELDK", DisplayName = "ELDK 2027",
            StartDate = new DateOnly(2027, 2, 9), EndDate = new DateOnly(2027, 2, 10), IsActive = true,
        });

        foreach (var (id, name) in new[] { (MyCompany, "Mine A/S"), (OtherCompany, "Theirs A/S") })
        {
            db.SponsorInfos.Add(new SponsorInfo
            {
                EventId = EventId, SponsorCompanyId = id, CompanyName = name,
                SponsorPackage = SponsorPackage.Gold,
                SocialMediaIntro = socialText, LogoRasterFileName = "logo.png",
            });
        }

        var me = new Participant
        {
            EventId = EventId, Email = "sponsor@x.test", FullName = "Spon Sor",
            Role = ParticipantRole.Sponsor, IsActive = true, SponsorCompanyId = MyCompany,
        };
        db.Participants.Add(me);
        await db.SaveChangesAsync();
        return me.Id;
    }

    /// <summary>
    /// ⚠️ <c>IsActive</c> defaults to TRUE on a bare <c>new</c>, but the planner creates every post
    /// HELD (§824.21a). The fixture matches the planner, not the CLR.
    /// </summary>
    private static SoMePost SponsorPost(
        string companyId, bool approved = true,
        SoMePostPlanState plan = SoMePostPlanState.Scheduled,
        SoMePostStatus status = SoMePostStatus.Queued) =>
        new()
        {
            EventId = EventId, Type = SoMePostType.Sponsor,
            TemplateKind = SoMeTemplateKind.Sponsor, SubjectKey = $"sponsor:{companyId}",
            Occurrence = 1, ScheduledAtUtc = Slot, Status = status,
            IsActive = approved, PlanState = plan, AutoGenerated = true,
            AutoText = "Welcome!", ImageRef = "sponsor-12.png",
        };

    // ── §1028: approved only, eligible only ────────────────────────────────────────────────────

    [Fact]
    public async Task A_sponsor_sees_their_own_approved_post()
    {
        using var db = NewDb();
        await SeedAsync(db);
        db.SoMePosts.Add(SponsorPost(MyCompany));
        await db.SaveChangesAsync();

        var a = await new SoMeAnnouncementQuery(db).ForSponsorAsync(EventId, MyCompany);

        Assert.Single(a.Company);
        Assert.Equal(1, a.Total);
    }

    /// <summary>🔒 The scoping rule — another company's post is not theirs to read.</summary>
    [Fact]
    public async Task A_sponsor_never_sees_another_companys_post()
    {
        using var db = NewDb();
        await SeedAsync(db);
        db.SoMePosts.Add(SponsorPost(OtherCompany));
        await db.SaveChangesAsync();

        var a = await new SoMeAnnouncementQuery(db).ForSponsorAsync(EventId, MyCompany);

        Assert.Equal(0, a.Total);
    }

    /// <summary>
    /// 🔴 §1028 — approved only. Operator 2026-08-10: <i>"only show approved posts"</i>. An
    /// unapproved post's wording may still change, so showing it promises words he then edits.
    /// </summary>
    [Fact]
    public async Task An_unapproved_post_is_not_shown_to_the_sponsor()
    {
        using var db = NewDb();
        await SeedAsync(db);
        db.SoMePosts.Add(SponsorPost(MyCompany, approved: false));
        await db.SaveChangesAsync();

        var a = await new SoMeAnnouncementQuery(db).ForSponsorAsync(EventId, MyCompany);

        Assert.Equal(0, a.Total);
    }

    /// <summary>
    /// 🔴 §1028 — eligible only. Operator 2026-08-10: <i>"only show when sponsor is eligble fx have
    /// delviered some text"</i>. "Eligible" is the BLOCKER, which already expresses it.
    /// </summary>
    [Fact]
    public async Task A_post_the_sponsor_still_owes_something_for_is_not_shown()
    {
        using var db = NewDb();
        await SeedAsync(db, socialText: null);          // owes their social text
        // Not yet approved, so the gate is consulted — an approved post has nothing left to wait for.
        db.SoMePosts.Add(SponsorPost(MyCompany, approved: false));
        await db.SaveChangesAsync();

        var a = await new SoMeAnnouncementQuery(db).ForSponsorAsync(EventId, MyCompany);

        Assert.Equal(0, a.Total);
    }

    /// <summary>🔒 §916 — a deleted post is a tombstone (§853), not content, for any audience.</summary>
    [Fact]
    public async Task A_deleted_post_is_shown_to_nobody()
    {
        using var db = NewDb();
        await SeedAsync(db);
        var post = SponsorPost(MyCompany);
        post.IsDeleted = true;
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        Assert.Equal(0, (await new SoMeAnnouncementQuery(db).ForSponsorAsync(EventId, MyCompany)).Total);
    }

    // ── §1029: the state badge ─────────────────────────────────────────────────────────────────

    /// <summary>
    /// 🔴 §1029 — "scheduled" needs BOTH: accepted into the plan AND approved. Operator 2026-08-10:
    /// <i>"i am confused that a post for late sept is scheduled"</i>. Reading <c>IsApproved</c> alone
    /// conflated two independent facts, and 29 PROD posts he had never accepted said "scheduled".
    /// </summary>
    [Fact]
    public void A_proposed_post_says_planned_even_when_approved()
    {
        var proposed = Announcement(approved: true, SoMePostPlanState.Proposed);
        var accepted = Announcement(approved: true, SoMePostPlanState.Scheduled);
        var held = Announcement(approved: false, SoMePostPlanState.Scheduled);

        Assert.Equal("planned", proposed.State);
        Assert.Equal("scheduled", accepted.State);
        Assert.Equal("planned", held.State);
    }

    [Fact]
    public void A_published_post_says_published_whatever_the_plan_says()
    {
        var published = Announcement(
            approved: true, SoMePostPlanState.Proposed, SoMePostStatus.Published);

        Assert.Equal("published", published.State);
    }

    private static SoMeAnnouncement Announcement(
        bool approved, SoMePostPlanState plan,
        SoMePostStatus status = SoMePostStatus.Queued) =>
        new(1, SoMeTemplateKind.Sponsor, "Sponsor announcement", $"sponsor:{MyCompany}",
            Slot, status, approved, "text", null, "mentions", null, plan);

    // ── §1032: the picture endpoint's gate ─────────────────────────────────────────────────────

    /// <summary>🔑 §1032 — the sponsor may fetch the picture of a post on their own page.</summary>
    [Fact]
    public async Task The_picture_of_my_own_approved_post_is_fetchable()
    {
        using var db = NewDb();
        var me = await SeedAsync(db);
        var post = SponsorPost(MyCompany);
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        var visible = await new SoMeAnnouncementQuery(db)
            .VisibleMediaPostAsync(EventId, me, post.Id);

        Assert.NotNull(visible);
        Assert.Equal("sponsor-12.png", visible!.ImageRef);
    }

    /// <summary>
    /// 🔴 §1032 — the gate is the SCOPE, not merely "signed in". A sponsor who knows a post id must
    /// not be able to pull another company's campaign asset.
    /// </summary>
    [Fact]
    public async Task The_picture_of_another_companys_post_is_refused()
    {
        using var db = NewDb();
        var me = await SeedAsync(db);
        var post = SponsorPost(OtherCompany);
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        Assert.Null(await new SoMeAnnouncementQuery(db)
            .VisibleMediaPostAsync(EventId, me, post.Id));
    }

    /// <summary>
    /// 🔒 §1032 — the picture follows the LIST. A sponsor cannot see an unapproved post (§1028), so
    /// they cannot see its image either; otherwise the endpoint would leak exactly what the page
    /// withholds.
    /// </summary>
    [Fact]
    public async Task The_picture_of_an_unapproved_post_is_refused_to_a_sponsor()
    {
        using var db = NewDb();
        var me = await SeedAsync(db);
        var post = SponsorPost(MyCompany, approved: false);
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        Assert.Null(await new SoMeAnnouncementQuery(db)
            .VisibleMediaPostAsync(EventId, me, post.Id));
    }

    /// <summary>
    /// ⚠️ §1032 — a SPEAKER's rule is deliberately different: §916 shows them planned posts, so a
    /// picture that 404'd while its text was on the page would read as a broken preview.
    /// </summary>
    [Fact]
    public async Task A_speaker_may_fetch_the_picture_of_their_own_planned_session_post()
    {
        using var db = NewDb();
        await SeedAsync(db);

        var speaker = new Participant
        {
            EventId = EventId, Email = "spk@x.test", FullName = "Spea Ker",
            Role = ParticipantRole.Speaker, IsActive = true,
        };
        db.Participants.Add(speaker);
        var session = new Session { EventId = EventId, Title = "A talk" };
        db.Sessions.Add(session);
        await db.SaveChangesAsync();

        db.SessionSpeakers.Add(new SessionSpeaker
        {
            SessionId = session.Id, ParticipantId = speaker.Id,
        });
        var post = new SoMePost
        {
            EventId = EventId, Type = SoMePostType.Speaker,
            TemplateKind = SoMeTemplateKind.Session, SubjectKey = $"session:{session.Id}",
            Occurrence = 1, ScheduledAtUtc = Slot, Status = SoMePostStatus.Queued,
            IsActive = false, AutoGenerated = true, AutoText = "Talk!", ImageRef = "session-3.png",
        };
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        Assert.NotNull(await new SoMeAnnouncementQuery(db)
            .VisibleMediaPostAsync(EventId, speaker.Id, post.Id));
    }

    /// <summary>🔒 A deleted post's picture goes with it.</summary>
    [Fact]
    public async Task The_picture_of_a_deleted_post_is_refused()
    {
        using var db = NewDb();
        var me = await SeedAsync(db);
        var post = SponsorPost(MyCompany);
        post.IsDeleted = true;
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        Assert.Null(await new SoMeAnnouncementQuery(db)
            .VisibleMediaPostAsync(EventId, me, post.Id));
    }
}
