using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §1178 — THE GUARD. Operator 2026-09-12: <i>"guard needed. no test sessions or test sponsor or
/// excluded can exist in some planner"</i>.
///
/// <para>🔴 <b>A filter is not a guard.</b> The planner stopped PROPOSING an excluded subject and the
/// gate stopped it being APPROVED — but a post planned BEFORE the flag was set already sat in the
/// queue, and §1060(h)'s withdrawal only un-approved it, leaving it exactly where he could still see
/// it. These pin that it LEAVES, that history does not, and that it can come back.</para>
/// </summary>
public sealed class SoMeQueueGuardTests
{
    private const int EventId = 1;

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"some-guard-{Guid.NewGuid():N}").Options);

    private static SoMePost Post(
        int id, string subjectKey, SoMePostStatus status = SoMePostStatus.Queued,
        bool isActive = false, SoMeTemplateKind kind = SoMeTemplateKind.Session,
        // §1203 — the ROUND is half the duplicate key, so it has to be settable.
        int occurrence = 1, SoMePostPlanState plan = SoMePostPlanState.Proposed) => new()
    {
        Id = id,
        EventId = EventId,
        Type = SoMePostType.Speaker,
        TemplateKind = kind,
        SubjectKey = subjectKey,
        Occurrence = occurrence,
        PlanState = plan,
        Status = status,
        IsActive = isActive,
        AutoGenerated = true,
        PublishedAtUtc = status == SoMePostStatus.Published ? DateTimeOffset.UtcNow : null,
    };

    private static async Task<CommunityHubDbContext> WithTestSessionAsync(int sessionId)
    {
        var db = NewDb();
        db.Sessions.Add(new Session
        {
            Id = sessionId,
            EventId = EventId,
            Title = "Test Master Class",
            Track = "Security",
            UsedForTesting = true,
        });
        db.Participants.Add(new Participant
        {
            Id = 1, EventId = EventId, Email = "o1@example.test", FullName = "Organizer One",
            Role = ParticipantRole.Organizer,
        });
        db.SessionSpeakers.Add(new SessionSpeaker { SessionId = sessionId, ParticipantId = 1 });
        await db.SaveChangesAsync();
        return db;
    }

    /// <summary>🔴 The reported case: a held post for a test session is removed from the planner.</summary>
    [Fact]
    public async Task A_planned_post_for_a_test_session_is_removed()
    {
        using var db = await WithTestSessionAsync(10);
        db.SoMePosts.Add(Post(1, "session:10"));
        await db.SaveChangesAsync();

        var result = await new SoMeQueueGuard(db).EnforceAsync(EventId);

        Assert.Equal(1, result.Removed);
        var post = await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 1);
        Assert.True(post.IsDeleted);
        // ⚠️ A tombstone that stayed Active would be one restored flag away from publishing.
        Assert.False(post.IsActive);
    }

    /// <summary>
    /// 🔒 An APPROVED post is removed too — being switched on is the dangerous state, not a safe one.
    /// </summary>
    [Fact]
    public async Task An_approved_post_for_a_test_session_is_removed()
    {
        using var db = await WithTestSessionAsync(10);
        db.SoMePosts.Add(Post(2, "session:10", isActive: true));
        await db.SaveChangesAsync();

        Assert.Equal(1, (await new SoMeQueueGuard(db).EnforceAsync(EventId)).Removed);
        Assert.True((await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 2)).IsDeleted);
    }

    /// <summary>
    /// 🛑 A PUBLISHED post is NEVER touched. It is out; the record must keep saying so, and a
    /// tombstone over history would make the campaign lie about what went to LinkedIn.
    /// </summary>
    [Fact]
    public async Task A_published_post_is_never_touched()
    {
        using var db = await WithTestSessionAsync(10);
        db.SoMePosts.Add(Post(3, "session:10", SoMePostStatus.Published, isActive: true));
        await db.SaveChangesAsync();

        Assert.Equal(0, (await new SoMeQueueGuard(db).EnforceAsync(EventId)).Removed);
        Assert.False((await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 3)).IsDeleted);
    }

    /// <summary>A post for a REAL session is left alone — the failure that would cost something.</summary>
    [Fact]
    public async Task A_post_for_a_real_session_survives()
    {
        using var db = await WithTestSessionAsync(10);
        db.Sessions.Add(new Session
        {
            Id = 11, EventId = EventId, Title = "Zero Trust in Practice", Track = "Security",
        });
        db.SessionSpeakers.Add(new SessionSpeaker { SessionId = 11, ParticipantId = 1 });
        db.SoMePosts.Add(Post(4, "session:11"));
        await db.SaveChangesAsync();

        await new SoMeQueueGuard(db).EnforceAsync(EventId);

        Assert.False((await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 4)).IsDeleted);
    }

    /// <summary>A test SPONSOR's post goes the same way — he named all three categories.</summary>
    [Fact]
    public async Task A_post_for_a_test_sponsor_is_removed()
    {
        using var db = NewDb();
        db.SponsorInfos.Add(new SponsorInfo
        {
            EventId = EventId, SponsorCompanyId = "99", CompanyName = "Test-Silver", IsTestData = true,
        });
        db.SoMePosts.Add(Post(5, "sponsor:99", kind: SoMeTemplateKind.Sponsor));
        await db.SaveChangesAsync();

        Assert.Equal(1, (await new SoMeQueueGuard(db).EnforceAsync(EventId)).Removed);
    }

    /// <summary>
    /// Idempotent: a second pass removes nothing, so the planner job can run every tick without
    /// re-reporting the same removals for ever.
    /// </summary>
    [Fact]
    public async Task A_second_pass_removes_nothing()
    {
        using var db = await WithTestSessionAsync(10);
        db.SoMePosts.Add(Post(6, "session:10"));
        await db.SaveChangesAsync();

        Assert.Equal(1, (await new SoMeQueueGuard(db).EnforceAsync(EventId)).Removed);
        Assert.Equal(0, (await new SoMeQueueGuard(db).EnforceAsync(EventId)).Removed);
    }

    /// <summary>
    /// 🔒 REVERSIBLE, and provably so: clearing the flag and restoring the post brings it back with
    /// its words intact (§1042 — a capability that merely LOOKS gone costs an afternoon).
    /// </summary>
    [Fact]
    public async Task Clearing_the_flag_and_restoring_brings_the_post_back()
    {
        using var db = await WithTestSessionAsync(10);
        db.SoMePosts.Add(Post(7, "session:10"));
        await db.SaveChangesAsync();
        await new SoMeQueueGuard(db).EnforceAsync(EventId);

        var session = await db.Sessions.FirstAsync(s => s.Id == 10);
        session.UsedForTesting = false;
        var post = await db.SoMePosts.FirstAsync(p => p.Id == 7);
        post.IsDeleted = false;
        post.DeletedAt = null;
        post.DeletedByEmail = null;
        await db.SaveChangesAsync();

        // The guard must not take it away again now that the flag is gone.
        Assert.Equal(0, (await new SoMeQueueGuard(db).EnforceAsync(EventId)).Removed);
        Assert.False((await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 7)).IsDeleted);
    }

    /// <summary>The reason travels with the removal, so the planner message can name it (§854).</summary>
    [Fact]
    public async Task The_removal_carries_a_reason_naming_the_subject()
    {
        using var db = await WithTestSessionAsync(10);
        db.SoMePosts.Add(Post(8, "session:10"));
        await db.SaveChangesAsync();

        var result = await new SoMeQueueGuard(db).EnforceAsync(EventId);

        var reason = Assert.Single(result.Reasons);
        Assert.Contains("Test Master Class", reason);
        Assert.Contains("UsedForTesting", reason);
    }

    // ──────────────── §1203 — ONE POST PER SUBJECT PER ROUND ────────────────
    //
    // Operator 2026-09-12: *"and cleaned up, so we have only 1 per post"*, after §1201 found Type 5
    // posts being deleted and re-created every ten minutes.
    //
    // 🔑 A duplicate is the SAME subject AND the SAME round. The same subject on several DATES is
    // NOT a duplicate — those are different rounds, and for Type 5 they are the dated runs he wrote
    // in the deck. Deleting those would delete his own campaign.

    private static async Task<CommunityHubDbContext> WithEditionAsync()
    {
        var db = NewDb();
        db.Sessions.Add(new Session
        {
            Id = 10, EventId = EventId, Title = "Real Session", Track = "Security",
        });
        await db.SaveChangesAsync();
        return db;
    }

    [Fact]
    public async Task Two_posts_for_the_same_subject_and_round_leave_one()
    {
        using var db = await WithEditionAsync();
        db.SoMePosts.AddRange(Post(1, "session:10"), Post(2, "session:10"));
        await db.SaveChangesAsync();

        var result = await new SoMeQueueGuard(db).RemoveDuplicatesAsync(EventId);

        Assert.Equal(1, result.Removed);
        Assert.Single(await db.SoMePosts.Where(p => !p.IsDeleted).ToListAsync());
    }

    /// <summary>⚠️ The rule that protects his deck: different rounds are different posts.</summary>
    [Fact]
    public async Task The_same_subject_in_DIFFERENT_rounds_is_not_a_duplicate()
    {
        using var db = await WithEditionAsync();
        db.SoMePosts.AddRange(
            Post(1, "session:10", occurrence: 1),
            Post(2, "session:10", occurrence: 2),
            Post(3, "session:10", occurrence: 3));
        await db.SaveChangesAsync();

        var result = await new SoMeQueueGuard(db).RemoveDuplicatesAsync(EventId);

        Assert.Equal(0, result.Removed);
        Assert.Equal(3, await db.SoMePosts.CountAsync(p => !p.IsDeleted));
    }

    /// <summary>🛑 Two posts that both PUBLISHED are two things that happened.</summary>
    [Fact]
    public async Task A_published_duplicate_is_left_alone()
    {
        using var db = await WithEditionAsync();
        db.SoMePosts.AddRange(
            Post(1, "session:10", SoMePostStatus.Published),
            Post(2, "session:10", SoMePostStatus.Published));
        await db.SaveChangesAsync();

        var result = await new SoMeQueueGuard(db).RemoveDuplicatesAsync(EventId);

        Assert.Equal(0, result.Removed);
        Assert.Equal(2, await db.SoMePosts.CountAsync(p => !p.IsDeleted));
        Assert.Contains(result.Reasons, r => r.Contains("already PUBLISHED"));
    }

    /// <summary>🔒 Which copy survives is DECIDED: published is history and always wins.</summary>
    [Fact]
    public async Task The_PUBLISHED_copy_is_the_one_that_survives()
    {
        using var db = await WithEditionAsync();
        db.SoMePosts.AddRange(
            Post(1, "session:10"),                               // queued, lower id
            Post(2, "session:10", SoMePostStatus.Published));    // history
        await db.SaveChangesAsync();

        await new SoMeQueueGuard(db).RemoveDuplicatesAsync(EventId);

        var survivor = Assert.Single(await db.SoMePosts.Where(p => !p.IsDeleted).ToListAsync());
        Assert.Equal(2, survivor.Id);
    }

    /// <summary>🔒 Then a slot he ACCEPTED — a decision beats an id.</summary>
    [Fact]
    public async Task An_ACCEPTED_copy_beats_an_untouched_one()
    {
        using var db = await WithEditionAsync();
        db.SoMePosts.AddRange(
            Post(1, "session:10"),
            Post(2, "session:10", plan: SoMePostPlanState.Scheduled));
        await db.SaveChangesAsync();

        await new SoMeQueueGuard(db).RemoveDuplicatesAsync(EventId);

        var survivor = Assert.Single(await db.SoMePosts.Where(p => !p.IsDeleted).ToListAsync());
        Assert.Equal(2, survivor.Id);
    }

    /// <summary>§853 — tombstoned, not destroyed, and never publishable again.</summary>
    [Fact]
    public async Task The_loser_is_tombstoned_and_deactivated_not_destroyed()
    {
        using var db = await WithEditionAsync();
        db.SoMePosts.AddRange(Post(1, "session:10", isActive: true), Post(2, "session:10"));
        await db.SaveChangesAsync();

        await new SoMeQueueGuard(db).RemoveDuplicatesAsync(EventId);

        var loser = await db.SoMePosts.AsNoTracking().FirstAsync(p => p.IsDeleted);
        Assert.False(loser.IsActive);
        Assert.NotNull(loser.DeletedAt);
        Assert.Contains("1203", loser.DeletedByEmail);
    }

    [Fact]
    public async Task A_second_pass_removes_no_more_duplicates()
    {
        using var db = await WithEditionAsync();
        db.SoMePosts.AddRange(Post(1, "session:10"), Post(2, "session:10"));
        await db.SaveChangesAsync();

        var guard = new SoMeQueueGuard(db);
        await guard.RemoveDuplicatesAsync(EventId);
        var second = await guard.RemoveDuplicatesAsync(EventId);

        // 🔒 It runs on a ten-minute timer. A pass that kept finding work would eat the queue.
        Assert.Equal(0, second.Removed);
    }

    /// <summary>⚠️ Two TYPES sharing a subject key are not duplicates of each other.</summary>
    [Fact]
    public async Task Two_different_TYPES_for_one_subject_are_both_kept()
    {
        using var db = await WithEditionAsync();
        db.SoMePosts.AddRange(
            Post(1, "session:10", kind: SoMeTemplateKind.Session),
            Post(2, "session:10", kind: SoMeTemplateKind.SpeakerTracks));
        await db.SaveChangesAsync();

        var result = await new SoMeQueueGuard(db).RemoveDuplicatesAsync(EventId);

        Assert.Equal(0, result.Removed);
    }
}
