using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §1206 — "DOES THE 19 EXIST IN THE PLANNER … SHOW THEN AS NOT READY, LIKE SOME GRAPHICS MISSING".
///
/// <para>Operator 2026-09-12. They DO exist — a held-back post is a planned post with a date that
/// holds a seat in the capacity report — so the ask is the LABEL, not the row.</para>
///
/// <para>🔴 <b>The reason existed everywhere except where he works.</b> The gate composes a sentence
/// naming what is owed; a sponsor's own page renders it (§1027) and §1204 grouped it on the settings
/// page. The QUEUE carried one blocker out of a dozen ("no graphic") and the CALENDAR said "held —
/// not approved", which describes a post nobody has got to and a post nobody CAN approve in the same
/// words.</para>
///
/// <para>🔑 One class for all three screens (§1178's lesson: four definitions of "excluded" cost a
/// day). These pin the SET it asks about and the WORDING it produces.</para>
/// </summary>
public sealed class SoMeReadinessTests
{
    private const int EventId = 1;

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"some-ready-{Guid.NewGuid():N}").Options);

    /// <summary>A sponsor who owes their social text and logo — the live shape of the 19.</summary>
    private static async Task<CommunityHubDbContext> WithBlockedSponsorAsync()
    {
        var db = NewDb();
        db.Events.Add(new Event
        {
            Id = EventId, Code = "ELDK27", CommunityName = "ELDK", DisplayName = "ELDK 2027",
            VenueName = "Bella Center", StartDate = new DateOnly(2027, 2, 9),
            EndDate = new DateOnly(2027, 2, 10), IsActive = true,
        });
        db.SponsorInfos.Add(new SponsorInfo
        {
            EventId = EventId,
            SponsorCompanyId = "co-1",
            CompanyName = "A Sponsor",
            SponsorPackage = SponsorPackage.Gold,
            // Nothing delivered: no social text, no logo of either kind.
        });
        await db.SaveChangesAsync();
        return db;
    }

    private static SoMePost SponsorPost(
        int id, bool isActive = false, SoMePostStatus status = SoMePostStatus.Queued,
        DateTimeOffset? publishedAt = null) => new()
    {
        Id = id,
        EventId = EventId,
        Type = SoMePostType.Sponsor,
        TemplateKind = SoMeTemplateKind.Sponsor,
        SubjectKey = "sponsor:co-1",
        Occurrence = 1,
        SponsorCompanyId = "co-1",
        ScheduledAtUtc = new DateTimeOffset(2026, 10, 20, 9, 0, 0, TimeSpan.Zero),
        Status = status,
        IsActive = isActive,
        PublishedAtUtc = publishedAt,
        AutoGenerated = true,
        AutoText = "text",
    };

    /// <summary>🔴 The reported case: a held post that cannot be approved says why.</summary>
    [Fact]
    public async Task A_held_post_that_is_blocked_carries_its_reason()
    {
        using var db = await WithBlockedSponsorAsync();
        var post = SponsorPost(1);
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        var reasons = await new SoMeReadiness(db).HeldReasonsAsync([post]);

        Assert.True(reasons.ContainsKey(post.Id), "a blocked held post must report a reason");
        Assert.Contains("A Sponsor", reasons[post.Id], StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// 🔒 An APPROVED post is not asked about — its state already says it is ready, and the gate is
    /// a query per post.
    /// </summary>
    [Fact]
    public async Task An_APPROVED_post_is_not_asked_about()
    {
        using var db = await WithBlockedSponsorAsync();
        var post = SponsorPost(1, isActive: true);
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        var reasons = await new SoMeReadiness(db).HeldReasonsAsync([post]);

        Assert.Empty(reasons);
    }

    /// <summary>🛑 A PUBLISHED post is history; there is nothing left for it to wait for.</summary>
    [Fact]
    public async Task A_PUBLISHED_post_is_not_asked_about()
    {
        using var db = await WithBlockedSponsorAsync();
        var published = SponsorPost(
            1, status: SoMePostStatus.Published,
            publishedAt: new DateTimeOffset(2026, 9, 1, 9, 0, 0, TimeSpan.Zero));
        db.SoMePosts.Add(published);
        await db.SaveChangesAsync();

        var reasons = await new SoMeReadiness(db).HeldReasonsAsync([published]);

        Assert.Empty(reasons);
    }

    /// <summary>
    /// 🔑 A READY held post is ABSENT, not present with an empty string — so a caller cannot render
    /// a blank reason as a blocker.
    /// </summary>
    [Fact]
    public async Task A_ready_held_post_is_absent_from_the_result()
    {
        using var db = await WithBlockedSponsorAsync();

        // Deliver everything the gate asks a sponsor post for: the social text, the logo, and the
        // graphic the logo feeds (§1060(g) — a sponsor asset is born Generated and never released).
        var sponsor = await db.SponsorInfos.FirstAsync();
        sponsor.SocialMediaIntro = "We are delighted to sponsor.";
        sponsor.LogoRasterFileName = "logo.png";
        db.GraphicAssets.Add(new GraphicAsset
        {
            EventId = EventId,
            Type = GraphicAssetType.Sponsor,
            SponsorCompanyId = "co-1",
            FileName = "sponsor-co-1.png",
            Status = GraphicAssetStatus.Generated,
        });
        var post = SponsorPost(1);
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        var reasons = await new SoMeReadiness(db).HeldReasonsAsync([post]);

        Assert.Empty(reasons);
    }

    [Fact]
    public void A_deleted_post_is_not_held()
    {
        var post = SponsorPost(1);
        post.IsDeleted = true;

        // §853 — a tombstone is not queue content, so it is not a post waiting for anything.
        Assert.False(SoMeReadiness.IsHeld(post));
    }

    /// <summary>§1204 — the reassurance tail is cut; the SUBJECT is kept, because he chases it.</summary>
    [Fact]
    public void Short_keeps_the_action_and_drops_the_reassurance()
    {
        const string reason =
            "A Sponsor has not delivered their social-media text, so the post cannot be approved yet "
            + "and becomes approvable as soon as that is filled in.";

        var shortened = SoMeReadiness.Short(reason);

        Assert.Contains("A Sponsor", shortened, StringComparison.Ordinal);
        Assert.DoesNotContain("as soon as that is filled in", shortened, StringComparison.Ordinal);
    }

    [Fact]
    public void Short_of_nothing_is_nothing()
    {
        Assert.Equal(string.Empty, SoMeReadiness.Short(""));
        Assert.Equal(string.Empty, SoMeReadiness.Short("   "));
    }

    /// <summary>
    /// 🔑 His own words for the chip: *"show then as not ready, like some graphics missing"*.
    /// </summary>
    [Theory]
    [InlineData("waiting for the social-media graphic — this subject has no released artwork yet",
        "graphic missing")]
    [InlineData("waiting for the sponsor's LOGO — their social-media graphic is generated from it",
        "logo missing")]
    [InlineData("A Sponsor has not delivered their social-media text", "sponsor text missing")]
    [InlineData("waiting for the session description — the announcement is written from it",
        "description missing")]
    [InlineData("no speaker is linked to this sponsor session yet", "speaker missing")]
    public void Chip_names_the_category_of_what_is_missing(string reason, string expected)
    {
        Assert.Equal(expected, SoMeReadiness.Chip(reason));
    }

    /// <summary>
    /// ⚠️ An unrecognised sentence falls back to "not ready" rather than guessing. A wrong label
    /// would send him chasing the wrong person, which is worse than a generic one.
    /// </summary>
    [Fact]
    public void Chip_falls_back_rather_than_guessing()
    {
        Assert.Equal("not ready", SoMeReadiness.Chip("something nobody has worded yet"));
        Assert.Equal("not ready", SoMeReadiness.Chip(""));
    }

    /// <summary>
    /// 🔴 The calendar carries the reason, and the CHEAP path is unchanged — the opt-in is what
    /// keeps the gate's per-post cost off every other caller.
    /// </summary>
    [Fact]
    public async Task The_calendar_query_carries_the_reason_and_the_plain_one_does_not()
    {
        using var db = await WithBlockedSponsorAsync();
        db.SoMeSettings.Add(new SoMeSettings
        {
            EventId = EventId, Enabled = true,
            EventSystemUrl = "https://eldk27.example.test", EventTags = "#ELDK27",
            OrganizerCredits = "Organizer One",
        });
        db.SoMePosts.Add(SponsorPost(1));
        await db.SaveChangesAsync();

        var query = new SoMeAnnouncementQuery(db);

        var withReadiness = await query.ForEventWithReadinessAsync(EventId);
        Assert.All(withReadiness, a => Assert.False(string.IsNullOrWhiteSpace(a.Blocker)));

        var plain = await query.ForEventAsync(EventId);
        Assert.All(plain, a => Assert.Null(a.Blocker));
    }
}
