using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using CommunityHub.Core.Integrations.Graphics;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §1178 — A SPONSOR GRAPHIC COULD NEVER REACH ITS POST, and two pages disagreed about it.
///
/// <para>Operator 2026-09-12: <i>"linkedin planner is wrong or the linkedin post calender when it
/// comes to some graphics readiness. take surveil as example"</i>.</para>
///
/// <para>🔴 <b>He was right, and both pages were reporting honestly — they were asking different
/// questions.</b> The planner's plannability gate asks <c>GraphicAssets.FileName != null</c>; the
/// thing that supplies the picture (<see cref="SoMeSubjectGraphic"/>, §1060(g)) asked for
/// <c>Status == Released</c>. And <c>GraphicsService.InitialStatusFor</c> returns <c>Generated</c> for
/// <c>GraphicAssetType.Sponsor</c> ALONE, deliberately — sponsor artwork is internal-only and feeds
/// the branding gate. Nothing ever released it.</para>
///
/// <para>⇒ Every Type 4 sponsor post was planned as ready, stamped with a NULL image, badged "no
/// graphic", blocked by the approval gate on "waiting for the graphic", and would have published
/// text-only. Measured for Surveil (company 36): logo uploaded 2026-08-25 13:50, <c>sponsor-36.png</c>
/// rendered 13:55, and the campaign could not see it a fortnight later. §1143 predicted exactly this
/// and left it open pending a decision on auto-release.</para>
///
/// <para>🔒 <b>The fix does not auto-release sponsor artwork</b> — that would change which artwork the
/// branding surfaces pick up, which is a decision nobody has made. It says the narrower true thing:
/// <b>release is the BRANDING gate, not the ANNOUNCEMENT gate.</b> A gate nothing can pass is not a
/// control, it is an outage.</para>
/// </summary>
public sealed class SoMeSponsorGraphicReadinessTests
{
    private const int EventId = 1;

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"some-sponsor-graphic-{Guid.NewGuid():N}").Options);

    private static SoMePost SponsorPost(string companyId, string? imageRef = null) => new()
    {
        Id = 1,
        EventId = EventId,
        Type = SoMePostType.Sponsor,
        TemplateKind = SoMeTemplateKind.Sponsor,
        SubjectKey = $"sponsor:{companyId}",
        AutoGenerated = true,
        ImageRef = imageRef,
        Status = SoMePostStatus.Queued,
    };

    /// <summary>
    /// 🔴 THE SURVEIL CASE. A sponsor graphic as the sweep actually writes it — <c>Generated</c>,
    /// because that is what <c>InitialStatusFor</c> returns for a sponsor — must reach its post.
    /// </summary>
    [Fact]
    public async Task A_sponsor_graphic_is_found_even_though_sponsor_rows_are_born_Generated()
    {
        using var db = NewDb();
        db.GraphicAssets.Add(new GraphicAsset
        {
            EventId = EventId,
            Type = GraphicAssetType.Sponsor,
            SponsorCompanyId = "36",
            FileName = "sponsor-36.png",
            // Exactly what the production sweep stores — asserted below so this test fails if that
            // ever changes rather than silently testing a state that no longer occurs.
            Status = GraphicsService.InitialStatusFor(GraphicAssetType.Sponsor),
        });
        await db.SaveChangesAsync();

        Assert.Equal(GraphicAssetStatus.Generated,
            GraphicsService.InitialStatusFor(GraphicAssetType.Sponsor));

        var map = await new SoMeSubjectGraphic(db).FileNamesAsync(EventId);

        Assert.Equal("sponsor-36.png", SoMeSubjectGraphic.Lookup(map, "sponsor:36"));
    }

    /// <summary>
    /// 🔒 The §1060(g) release gate is UNCHANGED for speaker-facing artwork. A session graphic that has
    /// not been released must still never reach a company page.
    /// </summary>
    [Fact]
    public async Task An_unreleased_SESSION_graphic_is_still_refused()
    {
        using var db = NewDb();
        db.GraphicAssets.Add(new GraphicAsset
        {
            EventId = EventId,
            Type = GraphicAssetType.Session,
            SessionId = 12,
            FileName = "session-12.png",
            Status = GraphicAssetStatus.Generated,
        });
        await db.SaveChangesAsync();

        var map = await new SoMeSubjectGraphic(db).FileNamesAsync(EventId);

        Assert.Null(SoMeSubjectGraphic.Lookup(map, "session:12"));
    }

    /// <summary>A released session graphic is found, so the gate is a gate and not a wall.</summary>
    [Fact]
    public async Task A_released_session_graphic_is_found()
    {
        using var db = NewDb();
        db.GraphicAssets.Add(new GraphicAsset
        {
            EventId = EventId,
            Type = GraphicAssetType.Session,
            SessionId = 12,
            FileName = "session-12.gif",
            Status = GraphicAssetStatus.Released,
        });
        await db.SaveChangesAsync();

        var map = await new SoMeSubjectGraphic(db).FileNamesAsync(EventId);

        Assert.Equal("session-12.gif", SoMeSubjectGraphic.Lookup(map, "session:12"));
    }

    /// <summary>
    /// §1178 — <c>Effective</c> is the dispatcher's rule, so a preview and a publish cannot disagree:
    /// the subject's CURRENT graphic wins over the ref stamped at plan time.
    /// </summary>
    [Fact]
    public async Task Effective_prefers_the_subjects_current_graphic_over_the_stamp()
    {
        using var db = NewDb();
        db.GraphicAssets.Add(new GraphicAsset
        {
            EventId = EventId,
            Type = GraphicAssetType.Sponsor,
            SponsorCompanyId = "36",
            FileName = "sponsor-36.png",
            Status = GraphicAssetStatus.Generated,
        });
        await db.SaveChangesAsync();
        var map = await new SoMeSubjectGraphic(db).FileNamesAsync(EventId);

        // Planned before the artwork existed: the stamp is null, and the picture must still be found.
        Assert.Equal("sponsor-36.png", SoMeSubjectGraphic.Effective(map, SponsorPost("36")));
        // A stale stamp loses to the current file.
        Assert.Equal("sponsor-36.png",
            SoMeSubjectGraphic.Effective(map, SponsorPost("36", "sponsor-36-old.png")));
    }

    /// <summary>
    /// ⚠️ A Type 5 / ad-hoc post owns its picture, so the stamp IS the answer — overriding it would
    /// discard a choice somebody made deliberately.
    /// </summary>
    [Fact]
    public void Effective_keeps_a_hand_picked_picture_on_an_event_post()
    {
        var map = new Dictionary<string, string> { ["sponsor:36"] = "sponsor-36.png" };
        var post = new SoMePost
        {
            Id = 2,
            EventId = EventId,
            TemplateKind = SoMeTemplateKind.EventPost,
            SubjectKey = "sponsor:36",
            ImageRef = "500-tickets.png",
        };

        Assert.Equal("500-tickets.png", SoMeSubjectGraphic.Effective(map, post));
    }

    /// <summary>A blank stamp reads as "no picture", not as an empty file name.</summary>
    [Fact]
    public void Effective_treats_a_blank_stamp_as_no_picture()
    {
        var post = new SoMePost
        {
            Id = 3,
            EventId = EventId,
            TemplateKind = SoMeTemplateKind.EventPost,
            ImageRef = "   ",
        };

        Assert.Null(SoMeSubjectGraphic.Effective(new Dictionary<string, string>(), post));
    }
}
