using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §1168 — the queue said "no graphic" about posts that publish WITH one.
///
/// <para>Operator 2026-09-03: <i>"graphics has been released but it still says no graphic"</i>. He
/// was right about the badge, and the post was never broken.</para>
///
/// <para>🔴 <b>The queue was asking the PLANNER's question.</b> A post stamps <c>ImageRef</c> when it
/// is planned, and nothing back-fills it when the graphic is released afterwards —
/// <c>RefreshAutoAsync</c> could, but nothing in production calls it (only tests do). Meanwhile §917
/// has the dispatcher re-resolve the subject's CURRENT graphic at send time, so those posts go out
/// with the image regardless. The stamp is a default for the editor; the badge reported it as the
/// outcome.</para>
///
/// <para>🔑 The lesson is the one this codebase keeps meeting: <b>correct behaviour reported by the
/// wrong question looks like a bug, and a wrong question reported confidently is worse than
/// silence</b> — he had already been told once that this was fixed.</para>
/// </summary>
public sealed class SoMeAwaitingGraphicTests
{
    private const int EventId = 1;

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"some-graphic-{Guid.NewGuid():N}").Options);

    private static SoMePost SponsorPost(int id, string companyId, string? imageRef = null) => new()
    {
        Id = id,
        EventId = EventId,
        Type = SoMePostType.Sponsor,
        TemplateKind = SoMeTemplateKind.Sponsor,
        SubjectKey = $"sponsor:{companyId}",
        AutoGenerated = true,
        ImageRef = imageRef,
        Status = SoMePostStatus.Queued,
    };

    private static async Task<SoMeQueueService> NewServiceAsync(
        CommunityHubDbContext db, params (string SubjectKey, string FileName)[] releasedGraphics)
    {
        foreach (var (subjectKey, fileName) in releasedGraphics)
        {
            db.GraphicAssets.Add(new GraphicAsset
            {
                EventId = EventId,
                Type = GraphicAssetType.Sponsor,
                SponsorCompanyId = subjectKey,
                FileName = fileName,
                Status = GraphicAssetStatus.Released,
            });
        }
        await db.SaveChangesAsync();

        return new SoMeQueueService(db, TimeProvider.System);
    }

    /// <summary>
    /// 🔴 The reported case: planned before the graphic existed, released afterwards.
    /// </summary>
    /// <remarks>
    /// The stamp is still null — nothing back-fills it — but the dispatcher will attach the released
    /// graphic, so the badge must NOT say "no graphic".
    /// </remarks>
    [Fact]
    public async Task A_graphic_released_after_planning_clears_the_badge()
    {
        using var db = NewDb();
        var post = SponsorPost(1, "36");
        db.SoMePosts.Add(post);
        var svc = await NewServiceAsync(db, ("36", "sponsor-36.png"));

        var awaiting = await svc.AwaitingGraphicAsync(EventId, new[] { post });

        Assert.DoesNotContain(post.Id, awaiting);
        // 🔑 And the OLD question still answers the old way — the two genuinely disagree, which is
        // the whole defect rather than a subtlety.
        Assert.True(post.IsAwaitingApprovedGraphic);
    }

    /// <summary>
    /// 🔒 A subject with no released graphic is still reported. The fix must not silence the badge.
    /// </summary>
    /// <remarks>
    /// Turning a wrong warning off is not the same as making it right: a post that really will
    /// publish text-only is something he needs to see.
    /// </remarks>
    [Fact]
    public async Task A_subject_with_no_graphic_at_all_is_still_awaiting()
    {
        using var db = NewDb();
        var post = SponsorPost(2, "99");
        db.SoMePosts.Add(post);
        var svc = await NewServiceAsync(db, ("36", "sponsor-36.png"));

        Assert.Contains(post.Id, await svc.AwaitingGraphicAsync(EventId, new[] { post }));
    }

    /// <summary>
    /// ⚠️ A SPEAKER-FACING graphic that exists but is NOT released does not clear the badge.
    /// </summary>
    /// <remarks>
    /// <para>The dispatcher attaches Released only for track/session artwork, so an unreleased row
    /// means the post really does publish text-only — the badge is telling the truth there.</para>
    ///
    /// <para>🔴 <b>§1178 — THIS TEST USED A SPONSOR ROW, AND THAT MADE IT PIN THE BUG.</b> It asserted
    /// that a <c>Generated</c> sponsor graphic leaves the badge saying "no graphic" — which was true
    /// behaviour and a broken outcome, because <c>GraphicsService.InitialStatusFor</c> returns
    /// <c>Generated</c> for a sponsor row and NOTHING releases it. So the state this test called
    /// exceptional was the ONLY state a sponsor graphic ever reaches, and the test locked in an
    /// announcement path no sponsor could pass. Retargeted at a SESSION, where "unreleased" is a real
    /// and temporary state and the rule it protects is genuinely load-bearing.
    /// <c>[[separate-proven-from-inferred]]</c></para>
    /// </remarks>
    [Fact]
    public async Task An_unreleased_speaker_facing_graphic_does_not_clear_the_badge()
    {
        using var db = NewDb();
        var post = new SoMePost
        {
            Id = 3,
            EventId = EventId,
            Type = SoMePostType.Speaker,
            TemplateKind = SoMeTemplateKind.Session,
            SubjectKey = "session:12",
            AutoGenerated = true,
            Status = SoMePostStatus.Queued,
        };
        db.SoMePosts.Add(post);
        db.GraphicAssets.Add(new GraphicAsset
        {
            EventId = EventId,
            Type = GraphicAssetType.Session,
            SessionId = 12,
            FileName = "session-12.png",
            Status = GraphicAssetStatus.Generated,
        });
        await db.SaveChangesAsync();
        var svc = new SoMeQueueService(db, TimeProvider.System);

        Assert.Contains(post.Id, await svc.AwaitingGraphicAsync(EventId, new[] { post }));
    }

    /// <summary>
    /// 🔴 §1178 — the SURVEIL case, and the counterpart to the test above: a sponsor graphic as the
    /// sweep actually writes it (<c>Generated</c>) DOES clear the badge.
    /// </summary>
    /// <remarks>
    /// Operator 2026-09-12: <i>"linkedin planner is wrong or the linkedin post calender when it comes
    /// to some graphics readiness. take surveil as example"</i>. Release is the BRANDING gate for
    /// sponsor artwork, never the announcement gate — see
    /// <c>SoMeSponsorGraphicReadinessTests</c> for the full reasoning.
    /// </remarks>
    [Fact]
    public async Task A_generated_sponsor_graphic_clears_the_badge()
    {
        using var db = NewDb();
        var post = SponsorPost(3, "36");
        db.SoMePosts.Add(post);
        db.GraphicAssets.Add(new GraphicAsset
        {
            EventId = EventId,
            Type = GraphicAssetType.Sponsor,
            SponsorCompanyId = "36",
            FileName = "sponsor-36.png",
            Status = GraphicAssetStatus.Generated,
        });
        await db.SaveChangesAsync();
        var svc = new SoMeQueueService(db, TimeProvider.System);

        Assert.Empty(await svc.AwaitingGraphicAsync(EventId, new[] { post }));
    }

    /// <summary>
    /// A post that already carries an image is never "awaiting", released graphic or not.
    /// </summary>
    [Fact]
    public async Task A_post_with_its_own_image_is_never_awaiting()
    {
        using var db = NewDb();
        var post = SponsorPost(4, "99", imageRef: "chosen-by-hand.png");
        db.SoMePosts.Add(post);
        var svc = await NewServiceAsync(db);

        Assert.Empty(await svc.AwaitingGraphicAsync(EventId, new[] { post }));
    }

    /// <summary>
    /// 🔒 Nothing is asked of the database when no post could possibly be awaiting.
    /// </summary>
    /// <remarks>
    /// The queue page renders every post; a per-post lookup would be a query per row. This is one
    /// lookup for the page, and none at all when there is nothing to resolve.
    /// </remarks>
    [Fact]
    public async Task No_candidates_means_no_work()
    {
        using var db = NewDb();
        var svc = await NewServiceAsync(db);

        Assert.Empty(await svc.AwaitingGraphicAsync(EventId, Array.Empty<SoMePost>()));
    }
}
