using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §1183 — THE ANNOUNCEMENT DATES GOVERN POSTS THAT ALREADY EXIST, NOT ONLY NEW ONES.
///
/// <para>Operator 2026-09-12: <i>"decission update: planner must obey to the update date changes,
/// even though they are planned or approved related to type 1-4. we need to streamline this and move
/// the current wrong planned/approved some posts"</i>.</para>
///
/// <para>🔑 §848.2's discard re-plans an UN-APPROVED proposal, so a held post followed a changed date
/// by accident — but an auto-approved one is excluded from that discard on the principle that
/// approving is a decision, and kept whatever date it was born with. Setting "sponsors from 15
/// October" therefore left every already-approved sponsor post sitting in September.</para>
/// </summary>
public sealed class SoMeWindowRetimeTests
{
    private const int EventId = 1;
    private static readonly DateTimeOffset EventStart = new(2027, 2, 9, 0, 0, 0, TimeSpan.Zero);
    private static readonly DateOnly SponsorFloor = new(2026, 10, 15);

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"some-window-{Guid.NewGuid():N}").Options);

    /// <summary>"Now" is fixed well before the 15 October floor, so the window is genuinely ahead.</summary>
    private static readonly DateTimeOffset Now = new(2026, 9, 12, 8, 0, 0, TimeSpan.Zero);

    private static SoMeScheduleService NewService(CommunityHubDbContext db)
    {
        var clock = new FixedClock(Now);
        return new SoMeScheduleService(
            db, new SoMeTemplateService(db, clock), new SoMeVariableResolver(db), clock);
    }

    /// <summary>A sponsor post sitting in September, before the 15 October floor.</summary>
    private static SoMePost SponsorPost(
        int id, DateTimeOffset at, bool approved, SoMePostPlanState plan = SoMePostPlanState.Proposed,
        SoMePostStatus status = SoMePostStatus.Queued) => new()
        {
            Id = id,
            EventId = EventId,
            Type = SoMePostType.Sponsor,
            TemplateKind = SoMeTemplateKind.Sponsor,
            SubjectKey = $"sponsor:{id}",
            Occurrence = 1,
            ScheduledAtUtc = at,
            Status = status,
            IsActive = approved,
            PlanState = plan,
            AutoGenerated = true,
            PublishedAtUtc = status == SoMePostStatus.Published ? at : null,
        };

    private static async Task<CommunityHubDbContext> SeedAsync(params SoMePost[] posts)
    {
        var db = NewDb();
        db.Events.Add(new Event
        {
            Id = EventId, Code = "ELDK27", DisplayName = "Experts Live Denmark 2027",
            StartDate = new DateOnly(2027, 2, 9),
        });
        db.SoMeSettings.Add(new SoMeSettings
        {
            EventId = EventId,
            SponsorAnnouncementFrom = SponsorFloor,
            MaxPostsPerDay = 2,
            // The footer must be complete or the planner refuses to run at all (§824.23).
            EventSystemUrl = "https://example.test",
            EventTags = "#ELDK27",
            OrganizerCredits = "Organizers",
        });
        db.SoMePosts.AddRange(posts);
        await db.SaveChangesAsync();
        return db;
    }

    private static DateTimeOffset Floor =>
        SoMeSchedulePlanner.ToUtc(SponsorFloor, SoMeSchedulePlanner.PreferredTimes[0]);

    /// <summary>
    /// 🔴 THE REPORTED CASE — an AUTO-APPROVED sponsor post in September moves to the window.
    /// §848.2's discard cannot do this: it skips approved posts on purpose.
    /// </summary>
    [Fact]
    public async Task An_approved_post_before_the_window_is_moved_forward()
    {
        using var db = await SeedAsync(
            SponsorPost(1, new DateTimeOffset(2026, 9, 18, 9, 0, 0, TimeSpan.Zero), approved: true));

        var result = await NewService(db).RunAsync(EventId);

        var post = await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 1);
        Assert.True(post.ScheduledAtUtc >= Floor,
            $"post 1 is still on {post.ScheduledAtUtc:dd-MM-yyyy}, before the 15 Oct floor");
        // 🔑 A re-time is not a re-plan: the approval survives.
        Assert.True(post.IsActive, "moving a post must not withdraw its approval");
        Assert.Contains("moved forward into their", result.Message, StringComparison.Ordinal);
    }

    /// <summary>
    /// A merely PLANNED post obeys the date too — he named both states.
    /// </summary>
    /// <remarks>
    /// 🔑 <b>By a DIFFERENT mechanism, and the distinction is worth keeping straight.</b> A held,
    /// un-edited proposal is DISCARDED and re-planned by §848.2, so it obeys the new date as a NEW
    /// ROW rather than by being moved — which is why this asserts the outcome (no sponsor post before
    /// the floor) instead of one row's id. My first version asserted the id and failed with "sequence
    /// contains no elements", which is the discard working exactly as designed.
    /// <para>⇒ The two states are covered by two mechanisms: the discard handles held, §1183's
    /// re-time handles approved. Together they are what "planned or approved" means.</para>
    /// </remarks>
    [Fact]
    public async Task A_held_post_before_the_window_ends_up_inside_it()
    {
        using var db = await SeedAsync(
            SponsorPost(2, new DateTimeOffset(2026, 9, 18, 9, 0, 0, TimeSpan.Zero), approved: false));

        await NewService(db).RunAsync(EventId);

        // ⚠️ The set may legitimately be EMPTY here: this edition has no SponsorInfo row, so the
        // discarded proposal has no plannable subject to be re-created from (§854 — a sponsor with no
        // graphic is not planned at all). Either way the invariant holds, and it is the invariant he
        // asked for: nothing sponsor-shaped is left sitting before the date.
        var sponsorPosts = await db.SoMePosts.AsNoTracking()
            .Where(p => p.TemplateKind == SoMeTemplateKind.Sponsor && !p.IsDeleted)
            .ToListAsync();

        Assert.All(sponsorPosts, p => Assert.True(p.ScheduledAtUtc >= Floor,
            $"post {p.Id} is on {p.ScheduledAtUtc:dd-MM-yyyy}, before the 15 Oct floor"));
        Assert.DoesNotContain(sponsorPosts, p => p.Id == 2 && p.ScheduledAtUtc < Floor);
    }

    /// <summary>
    /// 🛑 A post he ACCEPTED keeps its date — §848.2's one inviolable rule. It is NAMED in the run
    /// message instead, because "3 posts" would be a dead end for the only person who can move them.
    /// </summary>
    [Fact]
    public async Task An_accepted_post_is_reported_and_never_moved()
    {
        var when = new DateTimeOffset(2026, 9, 18, 9, 0, 0, TimeSpan.Zero);
        using var db = await SeedAsync(
            SponsorPost(3, when, approved: true, plan: SoMePostPlanState.Scheduled));

        var result = await NewService(db).RunAsync(EventId);

        var post = await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 3);
        Assert.Equal(when, post.ScheduledAtUtc);
        Assert.Contains("#3", result.Message, StringComparison.Ordinal);
        Assert.Contains("you accepted those dates", result.Message, StringComparison.Ordinal);
    }

    /// <summary>🛑 A PUBLISHED post is history and is never touched, whatever its date.</summary>
    [Fact]
    public async Task A_published_post_is_never_moved()
    {
        var when = new DateTimeOffset(2026, 9, 18, 9, 0, 0, TimeSpan.Zero);
        using var db = await SeedAsync(
            SponsorPost(4, when, approved: true, status: SoMePostStatus.Published));

        await NewService(db).RunAsync(EventId);

        Assert.Equal(when, (await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 4)).ScheduledAtUtc);
    }

    /// <summary>
    /// ⚠️ ONLY FORWARD. A post already inside the window keeps its date — dragging a December post
    /// back to October because "the window opened" would re-plan a schedule he has been reading.
    /// </summary>
    [Fact]
    public async Task A_post_already_inside_the_window_is_left_exactly_where_it_is()
    {
        var when = new DateTimeOffset(2026, 12, 8, 11, 0, 0, TimeSpan.Zero);
        using var db = await SeedAsync(SponsorPost(5, when, approved: true));

        await NewService(db).RunAsync(EventId);

        Assert.Equal(when, (await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 5)).ScheduledAtUtc);
    }

    /// <summary>
    /// 🔒 Idempotent — a second run moves nothing, so the timer can keep running without a post
    /// drifting a little further every five minutes.
    /// </summary>
    [Fact]
    public async Task A_second_run_moves_nothing()
    {
        using var db = await SeedAsync(
            SponsorPost(6, new DateTimeOffset(2026, 9, 18, 9, 0, 0, TimeSpan.Zero), approved: true));

        var svc = NewService(db);
        await svc.RunAsync(EventId);
        var afterFirst = (await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 6)).ScheduledAtUtc;

        await svc.RunAsync(EventId);
        var afterSecond = (await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 6)).ScheduledAtUtc;

        Assert.Equal(afterFirst, afterSecond);
    }

    /// <summary>And it never lands them on the holidays — the passes compose.</summary>
    [Fact]
    public async Task A_moved_post_never_lands_on_the_holiday_blackout()
    {
        var early = new DateTimeOffset(2026, 9, 18, 9, 0, 0, TimeSpan.Zero);
        using var db = await SeedAsync(
            Enumerable.Range(10, 12).Select(i => SponsorPost(i, early, approved: true)).ToArray());

        await NewService(db).RunAsync(EventId);

        foreach (var p in await db.SoMePosts.AsNoTracking().ToListAsync())
        {
            var day = DateOnly.FromDateTime(
                TimeZoneInfo.ConvertTime(p.ScheduledAtUtc, SoMeSchedulePlanner.DanishTime).DateTime);
            Assert.False(SoMeBlackout.IsBlackedOut(day),
                $"post {p.Id} landed on {day:dd-MM-yyyy}, inside the holiday blackout");
        }
    }

    // ───────── §1213 — A WINDOW THAT HAS ALREADY OPENED IS NOT A PAST DATE ─────────
    //
    // ⚠️ Found while investigating *"and it also planned a post in the past"* — and it is NOT that
    // defect. This pass did not exist when that post was dated (§1183 shipped the same day as the
    // report), and REMOVING THE CLAMP STILL LEAVES THESE GREEN, because §1144's push runs first and
    // re-dates an overdue proposal before this pass ever sees it. Verified by reverting the clamp
    // and re-running, rather than assumed.
    //
    // 🔑 The hole is real anyway: a window can open on a day that has passed, and `RetimeIntoWindow`
    // packs from the WINDOW's opening day — comparing against the window and the event, never
    // against today. An accepted post, or a proposal the push could not place, reaches here. Every
    // other re-time in the service takes `now` (§928, §1144, §1179); this was the only one that did
    // not. ⇒ These pin the CLAMP, not a reproduction, and they say so.

    /// <summary>🔒 An already-open window never places a post in the past.</summary>
    [Fact]
    public async Task A_window_that_opened_in_the_PAST_never_places_a_post_before_today()
    {
        using var db = NewDb();
        db.Events.Add(new Event
        {
            Id = EventId, Code = "ELDK27", DisplayName = "Experts Live Denmark 2027",
            StartDate = new DateOnly(2027, 2, 9),
        });
        db.SoMeSettings.Add(new SoMeSettings
        {
            EventId = EventId,
            // 🔴 The window opened TEN DAYS AGO. Legitimate — a run-up moves on, and a round he
            // dated last week is still the round that is running.
            SponsorAnnouncementFrom = DateOnly.FromDateTime(Now.AddDays(-10).UtcDateTime),
            MaxPostsPerDay = 2,
            EventSystemUrl = "https://example.test",
            EventTags = "#ELDK27",
            OrganizerCredits = "Organizers",
        });

        // A post sitting even earlier, so this pass treats it as "before its window" and moves it.
        db.SoMePosts.Add(SponsorPost(1, Now.AddDays(-30), approved: true));
        await db.SaveChangesAsync();

        await NewService(db).RunAsync(EventId);

        var after = await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 1);

        Assert.True(after.ScheduledAtUtc >= Now,
            $"the post was moved INTO THE PAST: {after.ScheduledAtUtc:u} is before now ({Now:u})");
    }

    /// <summary>
    /// 🔒 And the clamp must not break the ordinary case: a window still in the FUTURE is obeyed
    /// exactly, not dragged forward to today.
    /// </summary>
    [Fact]
    public async Task A_future_window_is_still_obeyed_exactly()
    {
        using var db = await SeedAsync(SponsorPost(1, Now.AddDays(-30), approved: true));

        await NewService(db).RunAsync(EventId);

        var after = await db.SoMePosts.AsNoTracking().FirstAsync(p => p.Id == 1);

        Assert.True(after.ScheduledAtUtc >= Floor,
            $"post moved to {after.ScheduledAtUtc:u}, before its 15 Oct window");
    }
}
