using CommunityHub.Core.Domain;
using CommunityHub.Core.Email;
using CommunityHub.Core.Integrations;
using CommunityHub.Core.Integrations.Graphics;
using CommunityHub.Core.Tests.Scenario;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// Offline tests for the LinkedIn company-page SoMe scheduling queue
/// (REQUIREMENTS §19): queue CRUD + active/inactive gating, due-post dispatch
/// idempotency, auto-vs-static override, sponsor tag set vs speaker
/// organizer-only, T-5-minute pre-alert scheduling, notification-array on/off,
/// the gated publisher never posting when disabled, and ad-hoc create. EF Core
/// InMemory + a fixed clock + a recording sender + recording/throwing publishers.
/// </summary>
public sealed class SoMeQueueTests
{
    private static readonly DateTimeOffset Now =
        new(2026, 6, 15, 9, 0, 0, TimeSpan.Zero);

    private static readonly FixedClock Clock = new(Now);

    // ----- seed -------------------------------------------------------------

    private static async Task<(int eventId, int organizerId, int speakerId, int sessionId)>
        SeedAsync(Data.CommunityHubDbContext db)
    {
        var evt = new Event
        {
            Code = "T27", CommunityName = "Test Community",
            DisplayName = "Test Community 2027",
            StartDate = new DateOnly(2027, 2, 9), EndDate = new DateOnly(2027, 2, 10),
            IsActive = true,
        };
        db.Events.Add(evt);
        await db.SaveChangesAsync();

        var organizer = new Participant
        {
            EventId = evt.Id, Email = "org@example.test", FullName = "Olivia Organizer",
            Role = ParticipantRole.Organizer, IsActive = true,
        };
        var speaker = new Participant
        {
            EventId = evt.Id, Email = "spk@example.test", FullName = "Sam Speaker",
            Role = ParticipantRole.Speaker, IsActive = true,
        };
        db.Participants.AddRange(organizer, speaker);
        await db.SaveChangesAsync();

        var session = new Session
        {
            EventId = evt.Id, SessionizeId = "hub-x", Title = "Building Things",
            Type = SessionType.CommunityTechSession,
        };
        db.Sessions.Add(session);
        await db.SaveChangesAsync();

        return (evt.Id, organizer.Id, speaker.Id, session.Id);
    }

    private static SoMeQueueService NewQueue(Data.CommunityHubDbContext db) => new(db, Clock);
    private static SoMeQueueService NewQueue(
        Data.CommunityHubDbContext db, IBrandingGraphicsProvider graphics) => new(db, Clock, graphics);
    private static SoMeSettingsService NewSettings(Data.CommunityHubDbContext db) => new(db, Clock);

    private static SoMeDispatchService NewDispatch(
        Data.CommunityHubDbContext db, ILinkedInPostPublisher publisher,
        IEmailSender? sender = null) =>
        new(db, publisher, NewSettings(db), sender ?? new CapturingEmailSender(),
            Clock, new EmailContextAccessor());

    // ----- queue CRUD + ad-hoc create ---------------------------------------

    [Fact]
    public async Task AdHoc_create_lands_a_static_post_in_the_queue()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);

        var post = await queue.CreateAdHocPostAsync(
            eventId, "Hello world", "https://img.test/x.png",
            Now.AddDays(1), tags: new[] { "@org" }, byEmail: "org@example.test");

        Assert.Equal(SoMePostType.AdHoc, post.Type);
        Assert.False(post.AutoGenerated);              // ad-hoc is static
        Assert.Equal("Hello world", post.EffectiveText); // typed text wins
        Assert.True(post.IsActive);
        Assert.Equal(SoMePostStatus.Queued, post.Status);

        var list = await queue.ListAsync(eventId);
        Assert.Single(list);
    }

    [Fact]
    public async Task Speaker_create_auto_populates_text_and_organizer_only_tags()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, sessionId) = await SeedAsync(db);
        var queue = NewQueue(db);

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, sessionId, Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");

        Assert.True(post.AutoGenerated);
        Assert.Contains("Sam Speaker", post.AutoText);
        Assert.Contains("Building Things", post.AutoText);
        // Speaker post tags ORGANIZERS ONLY — never the speaker.
        Assert.Contains("Olivia Organizer", post.TagList);
        Assert.DoesNotContain("Sam Speaker", post.TagList);
    }

    [Fact]
    public void Sponsor_create_tags_signer_coordinator_and_company()
    {
        // The tag builder is the compliance authority — test it directly so the
        // sponsor rule is asserted regardless of integration data availability.
        var tags = SoMeTagBuilder.ForSponsor(
            signerHandle: "Signer Sam",
            eventCoordinatorHandle: "Coord Casey",
            companyPublicName: "Acme Public",
            companyLegalName: "Acme Legal A/S",
            companyBillingName: null,
            companyId: "42");

        Assert.Contains("Signer Sam", tags);
        Assert.Contains("Coord Casey", tags);
        Assert.Contains("Acme Public", tags);            // public name wins the chain
        Assert.DoesNotContain("Acme Legal A/S", tags);   // legal is only a fallback
    }

    [Fact]
    public void Speaker_tags_are_organizers_only_never_the_speaker()
    {
        var tags = SoMeTagBuilder.ForSpeaker(new[] { "Org One", "Org Two", "Org One" });
        Assert.Equal(2, tags.Count);                     // de-duplicated
        Assert.Contains("Org One", tags);
        Assert.Contains("Org Two", tags);
    }

    // ----- auto-vs-static override ------------------------------------------

    [Fact]
    public async Task Manual_override_wins_over_auto_text_and_refresh_never_flushes_it()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, sessionId) = await SeedAsync(db);
        var queue = NewQueue(db);

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, sessionId, Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");

        await queue.EditAsync(eventId, post.Id, "My hand-written post", null, "org@example.test");
        var edited = await queue.GetAsync(eventId, post.Id);
        Assert.Equal("My hand-written post", edited!.EffectiveText);

        // A refresh re-populates auto text but the override still wins.
        await queue.RefreshAutoAsync(eventId, post.Id);
        var refreshed = await queue.GetAsync(eventId, post.Id);
        Assert.Equal("My hand-written post", refreshed!.EffectiveText);
        Assert.Contains("Sam Speaker", refreshed.AutoText);  // auto text refreshed underneath

        // Clearing the override falls back to auto text.
        await queue.EditAsync(eventId, post.Id, "", null, "org@example.test");
        var cleared = await queue.GetAsync(eventId, post.Id);
        Assert.Contains("Sam Speaker", cleared!.EffectiveText);
    }

    [Fact]
    public async Task Static_post_refresh_is_a_no_op()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, _) = await SeedAsync(db);
        var queue = NewQueue(db);

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, null, Now.AddDays(2), autoGenerate: false, byEmail: "org@example.test");

        var refreshed = await queue.RefreshAutoAsync(eventId, post.Id);
        Assert.False(refreshed);                         // AutoGenerated off => no-op
    }

    // ----- active/inactive gating + reschedule ------------------------------

    [Fact]
    public async Task Inactive_post_is_skipped_by_the_dispatcher()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(eventId, true, "urn:li:organization:1", null, null, false, null);

        var post = await queue.CreateAdHocPostAsync(
            eventId, "due", null, Now.AddMinutes(-1), null, "org@example.test");
        await queue.SetActiveAsync(eventId, post.Id, false, "org@example.test");

        var publisher = new RecordingPublisher();
        var result = await NewDispatch(db, publisher).DispatchDueAsync(eventId);

        Assert.Equal(0, result.Published);
        Assert.Empty(publisher.Posted);                  // inactive => never reached
        var unchanged = await queue.GetAsync(eventId, post.Id);
        Assert.Equal(SoMePostStatus.Queued, unchanged!.Status);
    }

    [Fact]
    public async Task Preview_renders_the_exact_post_and_will_publish_flag()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        var post = await queue.CreateAdHocPostAsync(
            eventId, "Preview me", "img.png", Now.AddDays(1), new[] { "@org" }, "org@example.test");

        var preview = await queue.PreviewAsync(eventId, post.Id);
        Assert.NotNull(preview);
        Assert.Equal("Preview me", preview!.Text);
        Assert.Equal("img.png", preview.ImageRef);
        Assert.True(preview.WillPublish);                // active + queued

        await queue.SetActiveAsync(eventId, post.Id, false, "org@example.test");
        var preview2 = await queue.PreviewAsync(eventId, post.Id);
        Assert.False(preview2!.WillPublish);             // inactive => won't fire
    }

    [Fact]
    public async Task Reschedule_moves_the_publish_time()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        var post = await queue.CreateAdHocPostAsync(eventId, "x", null, Now.AddDays(1), null, "org@example.test");

        var newTime = Now.AddDays(5);
        await queue.RescheduleAsync(eventId, post.Id, newTime, "org@example.test");
        var moved = await queue.GetAsync(eventId, post.Id);
        Assert.Equal(newTime, moved!.ScheduledAtUtc);
    }

    // ----- dispatch idempotency + gating ------------------------------------

    [Fact]
    public async Task Due_active_post_publishes_once_and_re_run_never_double_posts()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(eventId, true, "urn:li:organization:1", null, null, false, null);
        var post = await queue.CreateAdHocPostAsync(
            eventId, "due now", null, Now.AddMinutes(-1), null, "org@example.test");

        var publisher = new RecordingPublisher();
        var dispatch = NewDispatch(db, publisher);

        var first = await dispatch.DispatchDueAsync(eventId);
        Assert.Equal(1, first.Published);
        Assert.Single(publisher.Posted);

        var published = await queue.GetAsync(eventId, post.Id);
        Assert.Equal(SoMePostStatus.Published, published!.Status);
        Assert.Equal("ext-1", published.ExternalPostId);

        // Second run: the status is the sent-marker — nothing re-publishes.
        var second = await dispatch.DispatchDueAsync(eventId);
        Assert.Equal(0, second.Published);
        Assert.Single(publisher.Posted);                 // still just one POST
    }

    [Fact]
    public async Task Failed_publish_is_recorded_not_dropped()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(eventId, true, "urn:li:organization:1", null, null, false, null);
        var post = await queue.CreateAdHocPostAsync(
            eventId, "boom", null, Now.AddMinutes(-1), null, "org@example.test");

        var result = await NewDispatch(db, new ThrowingPublisher()).DispatchDueAsync(eventId);

        Assert.Equal(1, result.Failed);
        var failed = await queue.GetAsync(eventId, post.Id);
        Assert.Equal(SoMePostStatus.Failed, failed!.Status);
        Assert.Contains("kaboom", failed.LastError);
    }

    [Fact]
    public async Task Gated_publisher_never_posts_when_posting_is_disabled()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        // Settings exist but Enabled = false.
        await NewSettings(db).SaveAsync(eventId, false, "urn:li:organization:1", null, null, false, null);
        await queue.CreateAdHocPostAsync(eventId, "due", null, Now.AddMinutes(-1), null, "org@example.test");

        var publisher = new RecordingPublisher();      // CanPublish = true, but disabled
        var result = await NewDispatch(db, publisher).DispatchDueAsync(eventId);

        Assert.Equal(0, result.Published);
        Assert.Equal(1, result.Skipped);
        Assert.Empty(publisher.Posted);
    }

    [Fact]
    public async Task Null_publisher_never_posts_even_when_enabled()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(eventId, true, "urn:li:organization:1", null, null, false, null);
        await queue.CreateAdHocPostAsync(eventId, "due", null, Now.AddMinutes(-1), null, "org@example.test");

        // The shipped default Null publisher: CanPublish=false, throws if called.
        var result = await NewDispatch(db, new NullLinkedInPostPublisher()).DispatchDueAsync(eventId);

        Assert.Equal(0, result.Published);
        Assert.Equal(1, result.Skipped);                 // nothing faked, post left Queued
    }

    [Fact]
    public async Task No_company_page_means_skipped_even_if_enabled_and_publisher_wired()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(eventId, true, companyPageUrlOrOrgId: null, null, null, false, null);
        await queue.CreateAdHocPostAsync(eventId, "due", null, Now.AddMinutes(-1), null, "org@example.test");

        var result = await NewDispatch(db, new RecordingPublisher()).DispatchDueAsync(eventId);
        Assert.Equal(1, result.Skipped);
    }

    // ----- T-5-minute speaker pre-alert -------------------------------------

    [Fact]
    public async Task Speaker_post_within_5_minutes_triggers_one_pre_alert_idempotently()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(
            eventId, true, "urn:li:organization:1",
            speakerPreAlertOrganizerEmail: "alert@example.test", null, false, null);

        // Scheduled in 3 minutes -> inside the 5-minute pre-alert window.
        await queue.CreateSpeakerPostAsync(
            eventId, speakerId, null, Now.AddMinutes(3), autoGenerate: true, byEmail: "org@example.test");

        var sender = new CapturingEmailSender();
        var dispatch = NewDispatch(db, new RecordingPublisher(), sender);

        var first = await dispatch.DispatchDueAsync(eventId);
        Assert.Equal(1, first.PreAlertsSent);
        Assert.Single(sender.Sent);
        Assert.Equal("alert@example.test", sender.Sent[0].To);

        // Re-run: already alerted -> no second email.
        var second = await dispatch.DispatchDueAsync(eventId);
        Assert.Equal(0, second.PreAlertsSent);
        Assert.Single(sender.Sent);
    }

    [Fact]
    public async Task No_pre_alert_when_no_designated_organizer_is_set()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(eventId, true, "urn:li:organization:1", null, null, false, null);
        await queue.CreateSpeakerPostAsync(
            eventId, speakerId, null, Now.AddMinutes(3), autoGenerate: true, byEmail: "org@example.test");

        var sender = new CapturingEmailSender();
        var result = await NewDispatch(db, new RecordingPublisher(), sender).DispatchDueAsync(eventId);

        Assert.Equal(0, result.PreAlertsSent);
        Assert.Empty(sender.Sent);
    }

    // ----- notification array on/off ----------------------------------------

    [Fact]
    public async Task Publish_notification_emails_the_array_when_on()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(
            eventId, true, "urn:li:organization:1", null,
            notificationEmails: "a@example.test; b@example.test", notifyOnPublish: true, null);
        await queue.CreateAdHocPostAsync(eventId, "due", null, Now.AddMinutes(-1), null, "org@example.test");

        var sender = new CapturingEmailSender();
        await NewDispatch(db, new RecordingPublisher(), sender).DispatchDueAsync(eventId);

        var notify = sender.Sent.Where(s => s.Subject.Contains("published")).ToList();
        Assert.Equal(2, notify.Count);                   // both recipients notified
    }

    [Fact]
    public async Task Publish_notification_is_silent_when_toggled_off()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var queue = NewQueue(db);
        await NewSettings(db).SaveAsync(
            eventId, true, "urn:li:organization:1", null,
            notificationEmails: "a@example.test", notifyOnPublish: false, null);
        await queue.CreateAdHocPostAsync(eventId, "due", null, Now.AddMinutes(-1), null, "org@example.test");

        var sender = new CapturingEmailSender();
        await NewDispatch(db, new RecordingPublisher(), sender).DispatchDueAsync(eventId);

        Assert.DoesNotContain(sender.Sent, s => s.Subject.Contains("published"));
    }

    // ----- settings: token is never a column --------------------------------

    [Fact]
    public async Task Settings_save_persists_config_and_never_a_token()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var settings = NewSettings(db);

        var saved = await settings.SaveAsync(
            eventId, true, "urn:li:organization:99", "a@example.test",
            "n@example.test", true, "org@example.test");

        Assert.True(saved.Enabled);
        Assert.Equal("urn:li:organization:99", saved.CompanyPageUrlOrOrgId);
        Assert.Single(saved.NotificationEmailList);
        // The SoMeSettings entity exposes no token field at all (compile-time
        // proof the secret can't be persisted here) — assert the config round-trips.
        var reread = await settings.GetAsync(eventId);
        Assert.Equal("a@example.test", reread!.SpeakerPreAlertOrganizerEmail);
    }

    // ----- AutoGenerated branding image wiring (REQUIREMENTS §18↔§19) --------

    [Fact]
    public async Task Auto_speaker_post_pulls_the_released_graphic_into_ImageRef()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, sessionId) = await SeedAsync(db);
        // Provider exposes a RELEASED graphic for this speaker (gate already applied).
        var graphics = new FakeBranding
        {
            Speaker = { [speakerId] = Ref("speaker:" + speakerId, "https://store.test/speaker.png") },
        };
        var queue = NewQueue(db, graphics);

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, sessionId, Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");

        Assert.Equal("https://store.test/speaker.png", post.ImageRef);
        Assert.False(post.IsAwaitingApprovedGraphic);     // image present => not awaiting
    }

    [Fact]
    public async Task Auto_session_post_prefers_the_session_graphic_over_the_speaker_graphic()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, sessionId) = await SeedAsync(db);
        var graphics = new FakeBranding
        {
            Speaker = { [speakerId] = Ref("speaker:" + speakerId, "https://store.test/speaker.png") },
            Session = { [(sessionId, speakerId)] = Ref("session", "https://store.test/session.png") },
        };
        var queue = NewQueue(db, graphics);

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, sessionId, Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");

        Assert.Equal("https://store.test/session.png", post.ImageRef);  // session graphic wins
    }

    [Fact]
    public async Task Gated_or_unreleased_graphic_leaves_no_image_and_an_awaiting_state()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, _) = await SeedAsync(db);
        var graphics = new FakeBranding();                // provider returns null (gated / none)
        var queue = NewQueue(db, graphics);

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, null, Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");

        Assert.Null(post.ImageRef);                        // never a broken ref
        Assert.True(post.IsAwaitingApprovedGraphic);       // clear "awaiting approved graphic" state
        Assert.Contains("Sam Speaker", post.AutoText);     // text still composed

        var preview = await queue.PreviewAsync(eventId, post.Id);
        Assert.True(preview!.AwaitingApprovedGraphic);
        Assert.Null(preview.ImageRef);
    }

    [Fact]
    public async Task A_released_graphic_clears_a_previously_awaiting_post_on_refresh()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, _) = await SeedAsync(db);
        var graphics = new FakeBranding();                 // start gated
        var queue = NewQueue(db, graphics);

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, null, Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");
        Assert.True(post.IsAwaitingApprovedGraphic);

        // Organizer releases the graphic -> provider now exposes it -> refresh pulls it.
        graphics.Speaker[speakerId] = Ref("speaker:" + speakerId, "https://store.test/late.png");
        await queue.RefreshAutoAsync(eventId, post.Id);
        var refreshed = await queue.GetAsync(eventId, post.Id);

        Assert.Equal("https://store.test/late.png", refreshed!.ImageRef);
        Assert.False(refreshed.IsAwaitingApprovedGraphic);
    }

    [Fact]
    public async Task Manual_image_override_is_never_clobbered_by_the_auto_graphic()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, _) = await SeedAsync(db);
        var graphics = new FakeBranding
        {
            Speaker = { [speakerId] = Ref("speaker:" + speakerId, "https://store.test/auto.png") },
        };
        var queue = NewQueue(db, graphics);

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, null, Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");
        // Organizer sets their own image.
        await queue.EditAsync(eventId, post.Id, null, "https://manual.test/chosen.png", "org@example.test");

        // A refresh must NOT overwrite the manual image with the auto graphic.
        await queue.RefreshAutoAsync(eventId, post.Id);
        var refreshed = await queue.GetAsync(eventId, post.Id);

        Assert.Equal("https://manual.test/chosen.png", refreshed!.ImageRef);  // manual wins
    }

    [Fact]
    public async Task Auto_off_static_post_never_pulls_a_graphic_even_when_one_is_released()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, _) = await SeedAsync(db);
        var graphics = new FakeBranding
        {
            Speaker = { [speakerId] = Ref("speaker:" + speakerId, "https://store.test/auto.png") },
        };
        var queue = NewQueue(db, graphics);

        // AutoGenerated OFF => static wins; the provider is never consulted.
        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, null, Now.AddDays(2), autoGenerate: false, byEmail: "org@example.test");

        Assert.Null(post.ImageRef);                        // static => no auto image pulled
        Assert.False(post.IsAwaitingApprovedGraphic);      // static is never "awaiting"
        var refreshed = await queue.RefreshAutoAsync(eventId, post.Id);
        Assert.False(refreshed);                            // refresh is a no-op for static
    }

    [Fact]
    public async Task Auto_sponsor_post_pulls_the_internal_sponsor_graphic()
    {
        using var db = TestDb.New();
        var (eventId, _, _, _) = await SeedAsync(db);
        var graphics = new FakeBranding
        {
            Sponsor = { ["42"] = Ref("sponsor:42", "https://store.test/sponsor.png") },
        };
        var queue = NewQueue(db, graphics);

        var post = await queue.CreateSponsorPostAsync(
            eventId, "42", Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");

        Assert.Equal("https://store.test/sponsor.png", post.ImageRef);
    }

    [Fact]
    public async Task No_provider_wired_leaves_auto_posts_awaiting_and_never_fakes_an_image()
    {
        using var db = TestDb.New();
        var (eventId, _, speakerId, _) = await SeedAsync(db);
        var queue = NewQueue(db);                           // no IBrandingGraphicsProvider

        var post = await queue.CreateSpeakerPostAsync(
            eventId, speakerId, null, Now.AddDays(2), autoGenerate: true, byEmail: "org@example.test");

        Assert.Null(post.ImageRef);
        Assert.True(post.IsAwaitingApprovedGraphic);
    }

    private static BrandingGraphicRef Ref(string key, string imageRef) =>
        new(key, GraphicAssetType.Speaker, imageRef, "x.png", "draft");

    /// <summary>
    /// A fake <see cref="IBrandingGraphicsProvider"/> that returns ONLY what the
    /// test placed in it (the gate is modelled by simply not adding an entry =
    /// gated/un-released => null). Lets the SoMe wiring be asserted without the
    /// graphics engine / ImageSharp.
    /// </summary>
    private sealed class FakeBranding : IBrandingGraphicsProvider
    {
        public Dictionary<int, BrandingGraphicRef> Speaker { get; } = new();
        public Dictionary<(int, int), BrandingGraphicRef> Session { get; } = new();
        public Dictionary<string, BrandingGraphicRef> Sponsor { get; } = new();

        public Task<BrandingGraphicRef?> GetSpeakerGraphicAsync(
            int eventId, int participantId, CancellationToken ct = default) =>
            Task.FromResult(Speaker.TryGetValue(participantId, out var r) ? r : null);

        public Task<BrandingGraphicRef?> GetSessionGraphicAsync(
            int eventId, int sessionId, int participantId, CancellationToken ct = default) =>
            Task.FromResult(Session.TryGetValue((sessionId, participantId), out var r) ? r : null);

        public Task<BrandingGraphicRef?> GetSponsorGraphicAsync(
            int eventId, string sponsorCompanyId, CancellationToken ct = default) =>
            Task.FromResult(Sponsor.TryGetValue(sponsorCompanyId, out var r) ? r : null);
    }

    // ----- helper publishers ------------------------------------------------

    private sealed class RecordingPublisher : ILinkedInPostPublisher
    {
        public List<LinkedInPost> Posted { get; } = new();
        public bool CanPublish => true;
        public Task<LinkedInPublishResult> PublishAsync(LinkedInPost post, CancellationToken ct = default)
        {
            Posted.Add(post);
            return Task.FromResult(new LinkedInPublishResult(true, $"ext-{Posted.Count}", "ok"));
        }
    }

    private sealed class ThrowingPublisher : ILinkedInPostPublisher
    {
        public bool CanPublish => true;
        public Task<LinkedInPublishResult> PublishAsync(LinkedInPost post, CancellationToken ct = default)
            => throw new InvalidOperationException("kaboom");
    }
}
