using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §913 — WHAT A DUPLICATED POST MUST BE, asserted against the planner that would otherwise eat it.
/// </summary>
/// <remarks>
/// <para>Operator 2026-08-06: <i>"request for feature duplication post button"</i>.</para>
///
/// <para>🔴 <b>The trap that would make the button look broken.</b> The planner DISCARDS its own
/// un-accepted proposals on every tick (§848.2). A duplicate created as <c>Proposed</c> — the
/// natural thing to copy from its source — would therefore vanish within five minutes, and the
/// person who pressed the button would have no way to know why.</para>
///
/// <para>🔒 The copy is his: <c>Scheduled</c> plan state, not auto-generated, no subject. This test
/// runs a REAL planning pass over it, because that is the only way to prove the button's output
/// survives the thing that would delete it.</para>
/// </remarks>
public sealed class SoMeDuplicatePostContractTests
{
    private const int EventId = 1;
    private static readonly DateTimeOffset Now = new(2026, 8, 6, 9, 0, 0, TimeSpan.Zero);

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"dup-{Guid.NewGuid():N}").Options);

    private static async Task SeedAsync(CommunityHubDbContext db)
    {
        db.Events.Add(new Event
        {
            Id = EventId, Code = "ELDK27", CommunityName = "ELDK", DisplayName = "ELDK 2027",
            VenueName = "Bella Center",
            StartDate = new DateOnly(2027, 2, 9), EndDate = new DateOnly(2027, 2, 10), IsActive = true,
        });
        db.SoMeSettings.Add(new SoMeSettings
        {
            EventId = EventId, Enabled = true,
            EventSystemUrl = "https://example.test", EventTags = "#ELDK27",
            OrganizerCredits = "Organizer One",
        });
        await db.SaveChangesAsync();
    }

    /// <summary>A duplicate as the editor creates it (mirrors OnPostDuplicateAsync).</summary>
    private static SoMePost DuplicateOf(SoMePost source, string resolvedText) => new()
    {
        EventId = source.EventId,
        Type = SoMePostType.AdHoc,
        ManualTextOverride = resolvedText,
        AutoText = string.Empty,
        ImageRef = source.ImageRef,
        AutoGenerated = false,
        PlanState = SoMePostPlanState.Scheduled,
        IsActive = false,
        Status = SoMePostStatus.Queued,
        ScheduledAtUtc = source.ScheduledAtUtc,
        CreatedAt = Now,
    };

    /// <summary>
    /// 🔴 THE ONE THAT MATTERS: the copy is still there after the planner runs.
    /// </summary>
    [Fact]
    public async Task A_duplicate_survives_the_next_planning_tick()
    {
        using var db = NewDb();
        await SeedAsync(db);

        var source = new SoMePost
        {
            EventId = EventId, TemplateKind = SoMeTemplateKind.SpeakerTracks,
            SubjectKey = "track:Azure", Occurrence = 1,
            ScheduledAtUtc = Now.AddDays(30), Status = SoMePostStatus.Queued,
            IsActive = false, AutoGenerated = true, PlanState = SoMePostPlanState.Proposed,
            AutoText = "✨ {TrackName} ✨",
        };
        db.SoMePosts.Add(source);
        await db.SaveChangesAsync();

        var copy = DuplicateOf(source, "✨ Azure ✨");
        db.SoMePosts.Add(copy);
        await db.SaveChangesAsync();
        var copyId = copy.Id;

        // A real planning pass — the thing that deletes un-accepted proposals.
        var clock = new FixedClock(Now);
        await new SoMeScheduleService(
            db, new SoMeTemplateService(db, clock), new SoMeVariableResolver(db), clock)
            .RunAsync(EventId);

        var survivor = await db.SoMePosts.FirstOrDefaultAsync(p => p.Id == copyId);
        Assert.NotNull(survivor);
        Assert.Equal("✨ Azure ✨", survivor!.ManualTextOverride);
    }

    /// <summary>
    /// 🔒 A duplicate of a PUBLISHED post is a NEW, unpublished post. Copying the external id would
    /// make CEH believe it had already gone out — and it would never publish.
    /// </summary>
    [Fact]
    public void A_duplicate_of_a_published_post_is_unpublished()
    {
        var source = new SoMePost
        {
            EventId = EventId, Status = SoMePostStatus.Published,
            PublishedAtUtc = Now.AddDays(-2), ExternalPostId = "urn:li:share:123",
            IsActive = true, ScheduledAtUtc = Now.AddDays(-2), AutoText = "x",
        };

        var copy = DuplicateOf(source, "x");

        Assert.Equal(SoMePostStatus.Queued, copy.Status);
        Assert.Null(copy.PublishedAtUtc);
        Assert.Null(copy.ExternalPostId);
        // 🔒 And HELD — duplicating an approved post must not queue a second publication.
        Assert.False(copy.IsActive);
    }

    /// <summary>
    /// ⚠️ No subject: two posts claiming the same (subject, occurrence) would be counted as one by
    /// the planner's "have I already planned this?" lookup.
    /// </summary>
    [Fact]
    public void A_duplicate_claims_no_subject()
    {
        var source = new SoMePost
        {
            EventId = EventId, TemplateKind = SoMeTemplateKind.Session,
            SubjectKey = "session:12", Occurrence = 1, AutoText = "x",
        };

        var copy = DuplicateOf(source, "x");

        Assert.Null(copy.SubjectKey);
        Assert.Null(copy.TemplateKind);
        Assert.Null(copy.Occurrence);
        Assert.False(copy.AutoGenerated);
    }
}
