using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CommunityHub.Core.Tests;

/// <summary>
/// §918/§1030 — AUTO-APPROVAL, AND THE THREE GUARDS IT MUST NOT BREAK.
/// </summary>
/// <remarks>
/// <para>Operator 2026-08-06: <i>"as they run from the templates, i see no reason why we should not
/// auto-approve them, concerns?"</i> — with 79 posts held and 1 approved, clicking each was not a
/// workflow. The concerns were about HOW, and each is a test here.</para>
///
/// <para>🔴 <b>§1030 (2026-08-10) INVERTED guard 1, and these tests were rewritten with it.</b> They
/// are not stale tests that were deleted — each one described the OLD comparison correctly, so each
/// was re-pointed at the new window. The rule is now: approve only when
/// <c>now &lt; ScheduledAtUtc &lt;= now + leadDays</c> — <i>"become auto-approved when it reaches the
/// time"</i>. The old code approved everything MORE than the lead away, which had auto-approved 29
/// posts 24–169 days out while the imminent ones waited for a click.</para>
///
/// <para>🔒 The past-dated half of the guard survived the inversion and is not optional: §889.1 saw
/// him approve #495 whose 09:00 slot had already passed, and it published <b>thirty seconds
/// later</b>. Approving an overdue post is indistinguishable from publishing it.</para>
///
/// <para>⚠️ Every fixture below is scheduled <b>inside</b> the window on purpose. Under the old rule
/// they sat 30 days out; after the inversion that is "not yet due", which would have made the
/// switched-off / edited / Type-5 / published / blocked tests pass for the wrong reason — green
/// without ever reaching the guard they name.</para>
/// </remarks>
public sealed class SoMeAutoApproveTests
{
    private const int EventId = 1;
    private static readonly DateTimeOffset Now = new(2026, 8, 6, 9, 0, 0, TimeSpan.Zero);

    private static CommunityHubDbContext NewDb() =>
        new(new DbContextOptionsBuilder<CommunityHubDbContext>()
            .UseInMemoryDatabase($"autoapprove-{Guid.NewGuid():N}").Options);

    private static SoMeAutoApproveService NewService(CommunityHubDbContext db) =>
        new(db, new SoMeApprovalGate(db), new FixedClock(Now));

    private static async Task SeedAsync(
        CommunityHubDbContext db, bool enabled = true, int leadDays = 7)
    {
        db.Events.Add(new Event
        {
            Id = EventId, Code = "ELDK27", CommunityName = "ELDK", DisplayName = "ELDK 2027",
            StartDate = new DateOnly(2027, 2, 9), EndDate = new DateOnly(2027, 2, 10), IsActive = true,
        });
        db.SoMeSettings.Add(new SoMeSettings
        {
            EventId = EventId, Enabled = true,
            AutoApproveEnabled = enabled, AutoApproveLeadDays = leadDays,
        });
        await db.SaveChangesAsync();
    }

    private static SoMePost Planned(DateTimeOffset when, SoMeTemplateKind kind = SoMeTemplateKind.SpeakerTracks) =>
        new()
        {
            EventId = EventId, TemplateKind = kind, SubjectKey = $"track:T{when.Ticks}",
            Occurrence = 1, ScheduledAtUtc = when, Status = SoMePostStatus.Queued,
            IsActive = false, AutoGenerated = true, AutoText = "✨ {TrackName} ✨",
        };

    [Fact]
    public async Task It_does_nothing_at_all_until_he_switches_it_on()
    {
        using var db = NewDb();
        await SeedAsync(db, enabled: false);
        db.SoMePosts.Add(Planned(Now.AddDays(3)));   // due — the switch is the only thing stopping it
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.All(await db.SoMePosts.ToListAsync(), p => Assert.False(p.IsActive));
    }

    /// <summary>🔑 §1030 — the post has reached its time. This is when a rule may approve it.</summary>
    [Fact]
    public async Task A_post_due_inside_the_window_is_approved()
    {
        using var db = NewDb();
        await SeedAsync(db, leadDays: 7);
        db.SoMePosts.Add(Planned(Now.AddDays(3)));
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(1, result.Approved);
        Assert.True((await db.SoMePosts.FirstAsync()).IsActive);
    }

    /// <summary>🔴 GUARD 1 — the §889.1 case: an overdue post must never be switched on.</summary>
    [Fact]
    public async Task An_overdue_post_is_never_auto_approved()
    {
        using var db = NewDb();
        await SeedAsync(db);
        // Its slot passed an hour ago — approving it publishes on the next dispatch tick.
        db.SoMePosts.Add(Planned(Now.AddHours(-1)));
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.Equal(1, result.NotYetDue);
        Assert.False((await db.SoMePosts.FirstAsync()).IsActive);
    }

    /// <summary>
    /// 🔴 §1030 — the inversion itself. A post months out stays PLANNED: he has not accepted it into
    /// the plan yet, and an approval nobody asked for freezes something still meant to move.
    /// </summary>
    [Fact]
    public async Task A_post_not_yet_due_is_left_planned()
    {
        using var db = NewDb();
        await SeedAsync(db, leadDays: 7);
        db.SoMePosts.Add(Planned(Now.AddDays(30)));   // further out than the lead
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.Equal(1, result.NotYetDue);
        Assert.False((await db.SoMePosts.FirstAsync()).IsActive);
    }

    /// <summary>
    /// The far edge, pinned: the lead day itself is inside the window, a minute past it is not.
    /// ⚠️ Written because the old rule's boundary was the same instant with the opposite meaning —
    /// an off-by-one here is silent and re-approves the whole backlog.
    /// </summary>
    [Fact]
    public async Task The_far_edge_of_the_window_is_inclusive()
    {
        using var db = NewDb();
        await SeedAsync(db, leadDays: 7);
        db.SoMePosts.Add(Planned(Now.AddDays(7)));                    // exactly due-by
        db.SoMePosts.Add(Planned(Now.AddDays(7).AddMinutes(1)));      // one minute too early
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(1, result.Approved);
        Assert.Equal(1, result.NotYetDue);
        Assert.True((await db.SoMePosts.OrderBy(p => p.ScheduledAtUtc).FirstAsync()).IsActive);
        Assert.False((await db.SoMePosts.OrderByDescending(p => p.ScheduledAtUtc).FirstAsync()).IsActive);
    }

    /// <summary>
    /// 🔒 GUARD 3 — a post carrying a HUMAN's words keeps a human's approval, even though its type
    /// is template-built.
    /// </summary>
    [Fact]
    public async Task A_post_he_edited_still_waits_for_him()
    {
        using var db = NewDb();
        await SeedAsync(db);
        var post = Planned(Now.AddDays(3));   // due — his words are the only thing stopping it
        post.ManualTextOverride = "my own words";
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.False((await db.SoMePosts.FirstAsync()).IsActive);
    }

    /// <summary>🔒 GUARD 3 — Type 5 is his own copy from the deck; never auto-approved.</summary>
    [Fact]
    public async Task An_event_post_is_never_auto_approved()
    {
        using var db = NewDb();
        await SeedAsync(db);
        db.SoMePosts.Add(Planned(Now.AddDays(3), SoMeTemplateKind.EventPost));   // due; Type 5 anyway
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
    }

    /// <summary>
    /// 🔒 GUARD 2 — the approval gate still applies. A sponsor who has delivered neither their
    /// social text nor a logo is not announced just because a rule was switched on.
    /// </summary>
    [Fact]
    public async Task A_sponsor_with_a_missing_dependency_is_reported_not_approved()
    {
        using var db = NewDb();
        await SeedAsync(db);
        db.SponsorInfos.Add(new SponsorInfo
        {
            EventId = EventId, SponsorCompanyId = "co-9", CompanyName = "Not Ready A/S",
            SponsorPackage = SponsorPackage.Gold,
            SocialMediaIntro = null,          // owes their text
        });
        // 🔑 Due inside the window, so the GATE is what stops it — not the clock.
        var post = Planned(Now.AddDays(3), SoMeTemplateKind.Sponsor);
        post.SubjectKey = "sponsor:co-9";
        post.SponsorCompanyId = "co-9";
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(0, result.Approved);
        Assert.Equal(1, result.Blocked);
        Assert.False((await db.SoMePosts.FirstAsync()).IsActive);
    }

    /// <summary>
    /// ⚠️ A zero or negative lead is floored to one day rather than obeyed — a misconfigured field
    /// must not decide the window. Post-§1030 the flooring reads the other way round: an obeyed zero
    /// would collapse the window to nothing and approve <i>none</i> of them, so what this pins is
    /// that the floor is applied at all, and that the resulting window is exactly one day.
    /// </summary>
    [Fact]
    public async Task A_zero_lead_is_floored_rather_than_obeyed()
    {
        using var db = NewDb();
        await SeedAsync(db, leadDays: 0);
        db.SoMePosts.Add(Planned(Now.AddHours(2)));   // inside the floored 1-day window
        db.SoMePosts.Add(Planned(Now.AddDays(2)));    // outside it — the floor is 1 day, not 2
        await db.SaveChangesAsync();

        var result = await NewService(db).RunAsync(EventId);

        Assert.Equal(1, result.Approved);
        Assert.Equal(1, result.NotYetDue);
        Assert.True((await db.SoMePosts.OrderBy(p => p.ScheduledAtUtc).FirstAsync()).IsActive);
    }

    [Fact]
    public async Task An_already_published_post_is_left_alone()
    {
        using var db = NewDb();
        await SeedAsync(db);
        // Due inside the window on purpose, so STATUS is what excludes it rather than the clock;
        // the slot then moved out (a re-schedule after publication), which is why the two disagree.
        var post = Planned(Now.AddDays(3));
        post.Status = SoMePostStatus.Published;
        post.PublishedAtUtc = Now.AddDays(-1);
        db.SoMePosts.Add(post);
        await db.SaveChangesAsync();

        Assert.Equal(0, (await NewService(db).RunAsync(EventId)).Approved);
    }
}
