using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace CommunityHub.Core.Integrations;

/// <summary>What one auto-approval pass did — the numbers the Jobs page and the log both show.</summary>
/// <param name="Approved">Posts turned on.</param>
/// <param name="NotYetDue">§1030 — skipped: NOT YET DUE, or already overdue (the §889.1 guard).
/// ⚠️ This was <c>TooSoon</c> until §1030 inverted the rule; the old name described the old
/// comparison and would have taught it to the next reader.</param>
/// <param name="Blocked">Skipped: the approval gate refused — a dependency is missing.</param>
/// <param name="Message">One sentence for a human.</param>
public sealed record SoMeAutoApproveResult(
    int Approved, int NotYetDue, int Blocked, string Message);

/// <summary>
/// §918 — APPROVE THE TEMPLATE-BUILT POSTS AUTOMATICALLY, under three guards.
/// </summary>
/// <remarks>
/// <para>Operator 2026-08-06: <i>"as they run from the templates, i see no reason why we should not
/// auto-approve them, concerns?"</i> — a fair question with 79 posts held and 1 approved. The
/// concerns were about HOW, and each became a guard below.</para>
///
/// <list type="number">
/// <item>🔴 <b>§1030 — APPROVE ONLY AS IT COMES DUE: inside the window, and never past-dated.</b>
/// Operator 2026-08-10: <i>"they must follow principles about first become eligble (deliver things
/// like some text) + become auto-approved when it reaches the time"</i>.
///
/// <para>⚠️ <b>This INVERTS the original guard, which approved everything MORE than
/// <see cref="SoMeSettings.AutoApproveLeadDays"/> away and left the near-term posts for him.</b>
/// Measured 2026-08-10: that had auto-approved <b>29 posts 24–169 days out</b>, all still
/// <c>PlanState.Proposed</c> — so posts he had never accepted into the plan were approved months
/// ahead, while the ones about to run waited for a click. He read the page and could not reconcile
/// it with the rule he thought he had asked for. He was right; the code was the wrong way round.</para>
///
/// <para>🔒 <b>The past-dated half of the old guard is KEPT, and it is not optional.</b> §889.1
/// happened once already: he approved #495 after its 09:00 slot had passed and it published
/// <b>thirty seconds later</b>. So the rule is a WINDOW — due within the lead time, and not yet
/// overdue — rather than a single comparison. An overdue post still waits for a human, because
/// approving one is indistinguishable from publishing it.</para>
///
/// <para>🔑 The plan also stays movable for longer, which is what <c>Proposed</c> is for: a post
/// far out is no longer frozen by an approval nobody asked for.</para></item>
///
/// <item>🔒 <b>THE APPROVAL GATE STILL APPLIES.</b> <see cref="SoMeApprovalGate"/> refuses a sponsor
/// or tier post whose company has not delivered its social text or logo (§850/§865.4). Auto-approve
/// asks the SAME question a human would; it is a shortcut past the CLICK, not past the CHECK.</item>
///
/// <item>⚠️ <b>TEMPLATE-BUILT POSTS ONLY.</b> <c>AutoGenerated</c> and a <c>TemplateKind</c> — his
/// reasoning was "they run from the templates". A post someone WROTE (ad-hoc, or an edited body)
/// carries a human's words and keeps a human's approval. Type 5 is excluded for the same reason:
/// the deck's copy is his own.</item>
/// </list>
///
/// <para>🔒 <b>Off unless he turns it on.</b> §824.8 Q2 is the safety model; this is him delegating
/// the approval to a rule he can read, not the rule assuming it.</para>
/// </remarks>
public sealed class SoMeAutoApproveService
{
    private readonly CommunityHubDbContext _db;
    private readonly SoMeApprovalGate _gate;
    private readonly TimeProvider _clock;
    private readonly ILogger<SoMeAutoApproveService>? _log;

    public SoMeAutoApproveService(
        CommunityHubDbContext db,
        SoMeApprovalGate gate,
        TimeProvider clock,
        ILogger<SoMeAutoApproveService>? log = null)
    {
        _db = db;
        _gate = gate;
        _clock = clock;
        _log = log;
    }

    /// <summary>The kinds a template builds. Type 5 is HIS copy and is deliberately absent.</summary>
    private static readonly SoMeTemplateKind[] TemplateBuilt =
    [
        SoMeTemplateKind.SpeakerTracks,
        SoMeTemplateKind.Session,
        SoMeTemplateKind.SponsorCategory,
        SoMeTemplateKind.Sponsor,
    ];

    public async Task<SoMeAutoApproveResult> RunAsync(int eventId, CancellationToken ct = default)
    {
        var settings = await _db.SoMeSettings
            .AsNoTracking()
            .Where(s => s.EventId == eventId)
            .Select(s => new { s.AutoApproveEnabled, s.AutoApproveLeadDays })
            .FirstOrDefaultAsync(ct);

        if (settings is null || !settings.AutoApproveEnabled)
        {
            return new SoMeAutoApproveResult(0, 0, 0, "Auto-approval is off — every post waits for you.");
        }

        // 🔒 A zero or negative lead is floored: a misconfigured field must never widen the window
        // to "everything", in either direction.
        var leadDays = Math.Max(1, settings.AutoApproveLeadDays);
        var now = _clock.GetUtcNow();
        // §1030 — the WINDOW: due within `leadDays`, and not already overdue.
        var dueBy = now.AddDays(leadDays);

        var candidates = await _db.SoMePosts
            .Where(p => p.EventId == eventId
                        && !p.IsDeleted
                        && !p.IsActive                                   // not already approved
                        && p.Status == SoMePostStatus.Queued             // never published/failed
                        && p.AutoGenerated                               // guard 3
                        && p.TemplateKind != null
                        && TemplateBuilt.Contains(p.TemplateKind.Value)
                        && p.ManualTextOverride == null)                 // his words keep his approval
            .ToListAsync(ct);

        var approved = 0;
        var notYet = 0;
        var blocked = 0;

        foreach (var post in candidates)
        {
            // Guard 1 (§1030) — the WINDOW.
            //
            // 🔴 OVERDUE STAYS WITH A HUMAN. §889.1: approving a post whose slot has passed
            // publishes it on the next dispatch tick — thirty seconds, in the incident. That is
            // indistinguishable from pressing publish, so a rule may never do it.
            if (post.ScheduledAtUtc <= now)
            {
                notYet++;
                continue;
            }

            // Not due yet — it stays PLANNED and the plan stays movable. This is the half that was
            // inverted: it used to be the condition for approving, and is now the condition for
            // waiting.
            if (post.ScheduledAtUtc > dueBy)
            {
                notYet++;
                continue;
            }

            // Guard 2 — the same question a human answers before clicking approve.
            if (await _gate.BlockedReasonAsync(post, ct) is { Length: > 0 })
            {
                blocked++;
                continue;
            }

            post.IsActive = true;
            post.LastUpdatedByEmail = "auto-approved";
            approved++;
        }

        if (approved > 0) await _db.SaveChangesAsync(ct);

        // §1030 — the sentence describes the WINDOW, or it teaches the old rule to whoever reads it.
        var message =
            $"Auto-approved {approved} post(s) due within {leadDays} day(s). "
            + $"{notYet} not yet due (or already overdue — those stay with you), "
            + $"{blocked} waiting on a missing dependency.";

        _log?.LogInformation(
            "§1030 auto-approve: {Approved} approved, {NotYet} not yet due, {Blocked} blocked "
            + "(lead {LeadDays}d, event {EventId}).",
            approved, notYet, blocked, leadDays, eventId);

        return new SoMeAutoApproveResult(approved, notYet, blocked, message);
    }
}
