using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace CommunityHub.Core.Integrations;

/// <summary>What one auto-approval pass did — the numbers the Jobs page and the log both show.</summary>
/// <param name="Approved">Posts turned on.</param>
/// <param name="TooSoon">Skipped: inside the lead window (or already past). The §889.1 guard.</param>
/// <param name="Blocked">Skipped: the approval gate refused — a dependency is missing.</param>
/// <param name="Message">One sentence for a human.</param>
public sealed record SoMeAutoApproveResult(
    int Approved, int TooSoon, int Blocked, string Message);

/// <summary>
/// §918 — APPROVE THE TEMPLATE-BUILT POSTS AUTOMATICALLY, under three guards.
/// </summary>
/// <remarks>
/// <para>Operator 2026-08-06: <i>"as they run from the templates, i see no reason why we should not
/// auto-approve them, concerns?"</i> — a fair question with 79 posts held and 1 approved. The
/// concerns were about HOW, and each became a guard below.</para>
///
/// <list type="number">
/// <item>🔴 <b>NOTHING PAST-DATED, AND NOTHING IMMINENT.</b> §889.1 already happened once: he
/// approved #495, its 09:00 slot had passed, and it published <b>thirty seconds later</b>. Approving
/// a whole queue would do that to every post whose time has gone by — a burst of publications with
/// no chance to look. A post must be at least <see cref="SoMeSettings.AutoApproveLeadDays"/> away,
/// which doubles as the window in which he can still catch one.</item>
///
/// <item>🔒 <b>THE APPROVAL GATE STILL APPLIES.</b> <see cref="SoMeApprovalGate"/> refuses a sponsor
/// or tier post whose company has not delivered its social text or logo (§850/§865.4). Auto-approve
/// asks the SAME question a human would; it is a shortcut past the CLICK, not past the CHECK.</item>
///
/// <item>⚠️ <b>TEMPLATE-BUILT POSTS ONLY.</b> <c>AutoGenerated</c> and a <c>TemplateKind</c> — his
/// reasoning was "they run from the templates". A post someone WROTE (ad-hoc, or an edited body)
/// carries a human's words and keeps a human's approval. Type 5 is excluded for the same reason:
/// the deck's copy is his own.</item>
/// </list>
///
/// <para>🔒 <b>Off unless he turns it on.</b> §824.8 Q2 is the safety model; this is him delegating
/// the approval to a rule he can read, not the rule assuming it.</para>
/// </remarks>
public sealed class SoMeAutoApproveService
{
    private readonly CommunityHubDbContext _db;
    private readonly SoMeApprovalGate _gate;
    private readonly TimeProvider _clock;
    private readonly ILogger<SoMeAutoApproveService>? _log;

    public SoMeAutoApproveService(
        CommunityHubDbContext db,
        SoMeApprovalGate gate,
        TimeProvider clock,
        ILogger<SoMeAutoApproveService>? log = null)
    {
        _db = db;
        _gate = gate;
        _clock = clock;
        _log = log;
    }

    /// <summary>The kinds a template builds. Type 5 is HIS copy and is deliberately absent.</summary>
    private static readonly SoMeTemplateKind[] TemplateBuilt =
    [
        SoMeTemplateKind.SpeakerTracks,
        SoMeTemplateKind.Session,
        SoMeTemplateKind.SponsorCategory,
        SoMeTemplateKind.Sponsor,
    ];

    public async Task<SoMeAutoApproveResult> RunAsync(int eventId, CancellationToken ct = default)
    {
        var settings = await _db.SoMeSettings
            .AsNoTracking()
            .Where(s => s.EventId == eventId)
            .Select(s => new { s.AutoApproveEnabled, s.AutoApproveLeadDays })
            .FirstOrDefaultAsync(ct);

        if (settings is null || !settings.AutoApproveEnabled)
        {
            return new SoMeAutoApproveResult(0, 0, 0, "Auto-approval is off — every post waits for you.");
        }

        // 🔒 A zero or negative lead would defeat guard 1 entirely, so it is floored rather than
        // trusted: a misconfigured field must not become "publish everything now".
        var leadDays = Math.Max(1, settings.AutoApproveLeadDays);
        var now = _clock.GetUtcNow();
        var earliest = now.AddDays(leadDays);

        var candidates = await _db.SoMePosts
            .Where(p => p.EventId == eventId
                        && !p.IsDeleted
                        && !p.IsActive                                   // not already approved
                        && p.Status == SoMePostStatus.Queued             // never published/failed
                        && p.AutoGenerated                               // guard 3
                        && p.TemplateKind != null
                        && TemplateBuilt.Contains(p.TemplateKind.Value)
                        && p.ManualTextOverride == null)                 // his words keep his approval
            .ToListAsync(ct);

        var approved = 0;
        var tooSoon = 0;
        var blocked = 0;

        foreach (var post in candidates)
        {
            // Guard 1 — far enough out. Covers past-dated posts too: they are not "soon", they are
            // already overdue, and approving one publishes it on the next dispatch tick.
            if (post.ScheduledAtUtc < earliest)
            {
                tooSoon++;
                continue;
            }

            // Guard 2 — the same question a human answers before clicking approve.
            if (await _gate.BlockedReasonAsync(post, ct) is { Length: > 0 })
            {
                blocked++;
                continue;
            }

            post.IsActive = true;
            post.LastUpdatedByEmail = "auto-approved";
            approved++;
        }

        if (approved > 0) await _db.SaveChangesAsync(ct);

        var message =
            $"Auto-approved {approved} post(s) scheduled more than {leadDays} day(s) out. "
            + $"{tooSoon} left for you (too soon or overdue), {blocked} waiting on a missing dependency.";

        _log?.LogInformation(
            "§918 auto-approve: {Approved} approved, {TooSoon} too soon, {Blocked} blocked "
            + "(lead {LeadDays}d, event {EventId}).",
            approved, tooSoon, blocked, leadDays, eventId);

        return new SoMeAutoApproveResult(approved, tooSoon, blocked, message);
    }
}
