using CommunityHub.Core.Data;
using CommunityHub.Core.Domain;
using CommunityHub.Core.Integrations.Graphics;
using Microsoft.EntityFrameworkCore;

namespace CommunityHub.Core.Integrations;

/// <summary>One post rendered exactly as it will publish (the Preview, §19).</summary>
/// <param name="Text">The body that will publish (override ?? auto).</param>
/// <param name="ImageRef">The branding image reference, or null (text-only).</param>
/// <param name="Tags">The compliance-aware tag set.</param>
/// <param name="ScheduledAtUtc">When it will publish.</param>
/// <param name="WillPublish">
/// True only if it would actually publish on its schedule: Active + Queued. An
/// Inactive or already-Published/Failed post previews but won't fire.
/// </param>
/// <param name="AwaitingApprovedGraphic">
/// True when this auto post has no branding image yet — the linked speaker/session
/// graphic is missing or still behind the organizer release gate (REQUIREMENTS
/// §18↔§19). The post still previews/publishes as text-only; the flag tells the
/// organizer an approved graphic is pending.
/// </param>
public sealed record SoMePostPreview(
    string Text,
    string? ImageRef,
    IReadOnlyList<string> Tags,
    DateTimeOffset ScheduledAtUtc,
    bool WillPublish,
    bool AwaitingApprovedGraphic);

/// <summary>
/// The organizer curation authority for the LinkedIn company-page SoMe queue
/// (REQUIREMENTS §19): create/edit/fine-tune posts, the Active/Inactive toggle,
/// reschedule, auto-vs-static text (override wins), ad-hoc one-off posts, and the
/// Preview (render the exact post that will publish). Event-scoped throughout.
///
/// It deliberately does NOT publish — that is <c>SoMeDispatchService</c> (the job
/// path). This service is the curation half so the read/write rules live in one
/// place and stay independently testable with no email/LinkedIn dependency.
/// </summary>
public sealed class SoMeQueueService
{
    private readonly CommunityHubDbContext _db;
    private readonly TimeProvider _clock;
    private readonly IBrandingGraphicsProvider? _graphics;

    /// <summary>
    /// The branding-graphics consumer seam (REQUIREMENTS §18) the auto path pulls
    /// the post's <see cref="SoMePost.ImageRef"/> from. Optional: when null the
    /// queue still composes text + tags but never attaches an image (the auto post
    /// stays in the "awaiting approved graphic" state until a provider is wired) —
    /// nothing is ever faked.
    /// </summary>
    public SoMeQueueService(
        CommunityHubDbContext db,
        TimeProvider clock,
        IBrandingGraphicsProvider? graphics = null)
    {
        _db = db;
        _clock = clock;
        _graphics = graphics;
    }

    /// <summary>The edition's queue, newest-scheduled last (calendar order).</summary>
    public async Task<IReadOnlyList<SoMePost>> ListAsync(
        int eventId, CancellationToken ct = default) =>
        await _db.SoMePosts
            .Where(p => p.EventId == eventId)
            .OrderBy(p => p.ScheduledAtUtc)
            .ToListAsync(ct);

    /// <summary>Get one post (edition-scoped), or null.</summary>
    public Task<SoMePost?> GetAsync(int eventId, int postId, CancellationToken ct = default) =>
        _db.SoMePosts.FirstOrDefaultAsync(p => p.Id == postId && p.EventId == eventId, ct);

    /// <summary>
    /// Create a SPEAKER post for the queue. When <paramref name="autoGenerate"/>
    /// is true (the preferred default) the text + tags are auto-populated from the
    /// linked speaker/session/organizers; an organizer can fine-tune afterwards
    /// (the override then wins). When false, static/manual values win.
    /// </summary>
    public async Task<SoMePost> CreateSpeakerPostAsync(
        int eventId,
        int participantId,
        int? sessionId,
        DateTimeOffset scheduledAtUtc,
        bool autoGenerate,
        string? byEmail,
        CancellationToken ct = default)
    {
        var post = new SoMePost
        {
            EventId = eventId,
            Type = SoMePostType.Speaker,
            ParticipantId = participantId,
            SessionId = sessionId,
            ScheduledAtUtc = scheduledAtUtc,
            AutoGenerated = autoGenerate,
            IsActive = true,
            Status = SoMePostStatus.Queued,
            CreatedAt = _clock.GetUtcNow(),
            LastUpdatedByEmail = byEmail,
        };
        _db.SoMePosts.Add(post);
        if (autoGenerate) await PopulateAutoAsync(post, ct);
        await _db.SaveChangesAsync(ct);
        return post;
    }

    /// <summary>
    /// Create a SPONSOR post for the queue (see
    /// <see cref="CreateSpeakerPostAsync"/> for the auto-vs-static contract).
    /// </summary>
    public async Task<SoMePost> CreateSponsorPostAsync(
        int eventId,
        string sponsorCompanyId,
        DateTimeOffset scheduledAtUtc,
        bool autoGenerate,
        string? byEmail,
        CancellationToken ct = default)
    {
        var post = new SoMePost
        {
            EventId = eventId,
            Type = SoMePostType.Sponsor,
            SponsorCompanyId = sponsorCompanyId,
            ScheduledAtUtc = scheduledAtUtc,
            AutoGenerated = autoGenerate,
            IsActive = true,
            Status = SoMePostStatus.Queued,
            CreatedAt = _clock.GetUtcNow(),
            LastUpdatedByEmail = byEmail,
        };
        _db.SoMePosts.Add(post);
        if (autoGenerate) await PopulateAutoAsync(post, ct);
        await _db.SaveChangesAsync(ct);
        return post;
    }

    /// <summary>
    /// Create an AD-HOC one-off post (REQUIREMENTS §19): an organizer composes a
    /// post (image + text + schedule) directly into the same queue. Ad-hoc posts
    /// are always static (the text the organizer typed wins; no auto-refresh).
    /// </summary>
    public async Task<SoMePost> CreateAdHocPostAsync(
        int eventId,
        string text,
        string? imageRef,
        DateTimeOffset scheduledAtUtc,
        IReadOnlyList<string>? tags,
        string? byEmail,
        CancellationToken ct = default)
    {
        var post = new SoMePost
        {
            EventId = eventId,
            Type = SoMePostType.AdHoc,
            ScheduledAtUtc = scheduledAtUtc,
            // Ad-hoc is static: the typed text is the override (wins), AutoGenerated off.
            AutoGenerated = false,
            ManualTextOverride = string.IsNullOrWhiteSpace(text) ? null : text.Trim(),
            ImageRef = string.IsNullOrWhiteSpace(imageRef) ? null : imageRef.Trim(),
            Tags = tags is null ? string.Empty : string.Join('\n', tags),
            IsActive = true,
            Status = SoMePostStatus.Queued,
            CreatedAt = _clock.GetUtcNow(),
            LastUpdatedByEmail = byEmail,
        };
        _db.SoMePosts.Add(post);
        await _db.SaveChangesAsync(ct);
        return post;
    }

    /// <summary>
    /// Fine-tune a post's text + image (REQUIREMENTS §19). A non-blank
    /// <paramref name="textOverride"/> becomes the manual override that WINS over
    /// the auto text; passing blank clears the override (back to auto text). Never
    /// touches the schedule or the active flag.
    /// </summary>
    public async Task<bool> EditAsync(
        int eventId,
        int postId,
        string? textOverride,
        string? imageRef,
        string? byEmail,
        CancellationToken ct = default)
    {
        var post = await GetAsync(eventId, postId, ct);
        if (post is null) return false;

        post.ManualTextOverride = string.IsNullOrWhiteSpace(textOverride) ? null : textOverride.Trim();
        post.ImageRef = string.IsNullOrWhiteSpace(imageRef) ? null : imageRef.Trim();
        Touch(post, byEmail);
        await _db.SaveChangesAsync(ct);
        return true;
    }

    /// <summary>Flip the Active/Inactive toggle (an Inactive post never publishes).</summary>
    public async Task<bool> SetActiveAsync(
        int eventId, int postId, bool isActive, string? byEmail, CancellationToken ct = default)
    {
        var post = await GetAsync(eventId, postId, ct);
        if (post is null) return false;
        post.IsActive = isActive;
        Touch(post, byEmail);
        await _db.SaveChangesAsync(ct);
        return true;
    }

    /// <summary>Reschedule a post to a new date/time.</summary>
    public async Task<bool> RescheduleAsync(
        int eventId, int postId, DateTimeOffset scheduledAtUtc, string? byEmail,
        CancellationToken ct = default)
    {
        var post = await GetAsync(eventId, postId, ct);
        if (post is null) return false;
        post.ScheduledAtUtc = scheduledAtUtc;
        Touch(post, byEmail);
        await _db.SaveChangesAsync(ct);
        return true;
    }

    /// <summary>
    /// Render the exact post that will publish (the Preview button). For an
    /// auto post with no override this shows the auto text; the override (when
    /// set) wins. <c>WillPublish</c> is true only when it would actually fire
    /// (Active + Queued).
    /// </summary>
    public async Task<SoMePostPreview?> PreviewAsync(
        int eventId, int postId, CancellationToken ct = default)
    {
        var post = await GetAsync(eventId, postId, ct);
        if (post is null) return null;
        return new SoMePostPreview(
            post.EffectiveText,
            post.ImageRef,
            post.TagList,
            post.ScheduledAtUtc,
            post.IsActive && post.Status == SoMePostStatus.Queued,
            post.IsAwaitingApprovedGraphic);
    }

    /// <summary>
    /// Re-populate the auto text + auto tags from the linked sponsor/speaker for an
    /// auto post (e.g. after the linked data changed). NEVER touches the manual
    /// override (override wins) and is a no-op when <see cref="SoMePost.AutoGenerated"/>
    /// is off — static values win.
    /// </summary>
    public async Task<bool> RefreshAutoAsync(
        int eventId, int postId, CancellationToken ct = default)
    {
        var post = await GetAsync(eventId, postId, ct);
        if (post is null || !post.AutoGenerated) return false;
        await PopulateAutoAsync(post, ct);
        await _db.SaveChangesAsync(ct);
        return true;
    }

    // --- auto population (text + tags) ---------------------------------------

    /// <summary>
    /// Fill <see cref="SoMePost.AutoText"/>, <see cref="SoMePost.Tags"/> and (when
    /// empty) the image from the linked sponsor/speaker. Pure-data assembly; the
    /// caller saves. The manual override + an explicitly-set image are never
    /// overwritten.
    /// </summary>
    private async Task PopulateAutoAsync(SoMePost post, CancellationToken ct)
    {
        var evt = await _db.Events
            .Where(e => e.Id == post.EventId)
            .Select(e => new { e.DisplayName })
            .FirstOrDefaultAsync(ct);
        var eventDisplay = evt?.DisplayName ?? string.Empty;

        if (post.Type == SoMePostType.Speaker && post.ParticipantId is int pid)
        {
            var speakerName = await _db.Participants
                .Where(p => p.Id == pid && p.EventId == post.EventId)
                .Select(p => p.FullName)
                .FirstOrDefaultAsync(ct) ?? string.Empty;

            string? sessionTitle = null;
            if (post.SessionId is int sid)
            {
                sessionTitle = await _db.Sessions
                    .Where(s => s.Id == sid && s.EventId == post.EventId)
                    .Select(s => s.Title)
                    .FirstOrDefaultAsync(ct);
            }

            post.AutoText = SoMeTextComposer.ForSpeaker(speakerName, sessionTitle, eventDisplay);

            // Speaker posts tag ORGANIZERS ONLY (the API can't tag external
            // speakers; the T-5 pre-alert handles the speaker handle manually).
            var organizerNames = await _db.Participants
                .Where(p => p.EventId == post.EventId
                            && p.Role == ParticipantRole.Organizer
                            && p.IsActive)
                .Select(p => p.FullName)
                .ToListAsync(ct);
            post.Tags = string.Join('\n', SoMeTagBuilder.ForSpeaker(organizerNames));

            // Branding image (REQUIREMENTS §18 link): pull the RELEASED speaker /
            // session graphic from the gated provider. A session post prefers the
            // per-session graphic, falling back to the speaker graphic. Gated /
            // un-released => null => no image (the post stays "awaiting approved
            // graphic", never a broken ref). A manually-set image always wins.
            if (_graphics is not null)
            {
                BrandingGraphicRef? graphic = null;
                if (post.SessionId is int gsid)
                {
                    graphic = await _graphics.GetSessionGraphicAsync(
                        post.EventId, gsid, pid, ct);
                }
                graphic ??= await _graphics.GetSpeakerGraphicAsync(post.EventId, pid, ct);
                ApplyAutoImage(post, graphic);
            }
        }
        else if (post.Type == SoMePostType.Sponsor)
        {
            var companyId = post.SponsorCompanyId ?? string.Empty;

            // The hub has no company table; the public name is resolved from any
            // SponsorInfo / participant company we hold, falling back to the chain.
            var publicName = await _db.SponsorInfos
                .Where(s => s.EventId == post.EventId && s.SponsorCompanyId == companyId)
                .Select(s => s.CompanyDescriptionShort)
                .FirstOrDefaultAsync(ct);

            var companyName = SponsorCompanyName.Resolve(publicName, null, null, companyId);
            post.AutoText = SoMeTextComposer.ForSponsor(companyName, eventDisplay);

            // Sponsor posts tag signer + event coordinator + the company. The
            // signer/coordinator handles come from Company Manager (operator
            // config / live integration); with none available the company tag is
            // still set so the post carries the company mention.
            post.Tags = string.Join('\n', SoMeTagBuilder.ForSponsor(
                signerHandle: null,
                eventCoordinatorHandle: null,
                companyPublicName: publicName,
                companyLegalName: null,
                companyBillingName: null,
                companyId: companyId));

            // Sponsor branding graphics are INTERNAL-ONLY (no speaker release gate)
            // — the provider returns one whenever it exists. A manually-set image
            // still wins; no graphic => no image (text-only sponsor post).
            if (_graphics is not null && !string.IsNullOrWhiteSpace(companyId))
            {
                var graphic = await _graphics.GetSponsorGraphicAsync(
                    post.EventId, companyId, ct);
                ApplyAutoImage(post, graphic);
            }
        }
    }

    /// <summary>
    /// Attach the branding graphic's image ref to the post, but ONLY when no image
    /// is already set — a manually-set / organizer-chosen image (the override)
    /// always wins and is never clobbered by an auto refresh. When the graphic is
    /// null (none / still behind the release gate) the image is left blank so the
    /// post stays in the clear "awaiting approved graphic" state
    /// (<see cref="SoMePost.IsAwaitingApprovedGraphic"/>) — never a broken ref.
    /// </summary>
    private static void ApplyAutoImage(SoMePost post, BrandingGraphicRef? graphic)
    {
        if (graphic is null) return;                              // gated / missing => awaiting
        if (!string.IsNullOrWhiteSpace(post.ImageRef)) return;   // manual image wins
        post.ImageRef = graphic.ImageRef;
    }

    private void Touch(SoMePost post, string? byEmail)
    {
        post.UpdatedAt = _clock.GetUtcNow();
        post.LastUpdatedByEmail = byEmail;
    }
}
